-- UPDATE script for table M_BANK (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 6

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK)
UPDATE T SET BANK_NAME = N'常陽銀行', BANK_NAME_RYAKU = N'常陽銀行', BANK_FURIGANA = N'ジョウヨウギンコウ', CREATE_USER = N'初回ログイン用', UPDATE_USER = N'初回ログイン用' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK)
UPDATE T SET BANK_NAME = N'つくば銀行', BANK_NAME_RYAKU = N'つくば銀行', BANK_FURIGANA = N'ツクバギンコウ', CREATE_USER = N'安田　彬', UPDATE_USER = N'安田　彬' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK)
UPDATE T SET BANK_NAME = N'みずほ銀行', BANK_NAME_RYAKU = N'みずほ銀行', BANK_FURIGANA = N'ミズホギンコウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK)
UPDATE T SET BANK_NAME = N'秋葉銀行', BANK_NAME_RYAKU = N'秋葉銀行', BANK_FURIGANA = N'アキバギンコウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK)
UPDATE T SET BANK_NAME = N'常陽銀行', BANK_NAME_RYAKU = N'常陽銀行', BANK_FURIGANA = N'ジョウヨウギンコウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK)
UPDATE T SET BANK_NAME = N'京都信用金庫', BANK_NAME_RYAKU = N'京都信用金庫', BANK_FURIGANA = N'キョウトシンヨウキンボキンコ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

