-- UPDATE script for table M_BANK_SHITEN (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 13

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK_SHITEN)
UPDATE T SET BANK_SHITEN_NAME = N'筑波支店', BANK_SHIETN_NAME_RYAKU = N'筑波支店', BANK_SHITEN_FURIGANA = N'ツクバシテシテン', KOUZA_NAME = N'エジソンショウジ（カ', CREATE_USER = N'初回ログイン用', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK_SHITEN)
UPDATE T SET BANK_SHITEN_NAME = N'筑波支店', BANK_SHIETN_NAME_RYAKU = N'筑波支店', BANK_SHITEN_FURIGANA = N'ツクバシテシテン', KOUZA_NAME = N'エジソンショウジ（カ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK_SHITEN)
UPDATE T SET BANK_SHITEN_NAME = N'筑波支店', BANK_SHIETN_NAME_RYAKU = N'筑波支店', BANK_SHITEN_FURIGANA = N'ツクバシテシテン', KOUZA_NAME = N'エジソンショウジ（カ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK_SHITEN)
UPDATE T SET BANK_SHITEN_NAME = N'竹園支店', BANK_SHIETN_NAME_RYAKU = N'竹園支店', BANK_SHITEN_FURIGANA = N'タケゾノシテン', KOUZA_NAME = N'エジソンショウジ（カ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK_SHITEN)
UPDATE T SET BANK_SHITEN_NAME = N'竹園支店２２２２２０１２３４５', BANK_SHIETN_NAME_RYAKU = N'竹園支店２２２２２０', BANK_SHITEN_FURIGANA = N'タケゾノシテン２２２２２０１２３４５', KOUZA_NAME = N'エジソンショウジ（カ', CREATE_USER = N'初回ログイン用', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK_SHITEN)
UPDATE T SET BANK_SHITEN_NAME = N'つくば支店', BANK_SHIETN_NAME_RYAKU = N'つくば支店', BANK_SHITEN_FURIGANA = N'ツウウバツクバシテン', KOUZA_NAME = N'エジソンショウジ（カ', CREATE_USER = N'安田　彬', UPDATE_USER = N'新川　拓哉' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK_SHITEN)
UPDATE T SET BANK_SHITEN_NAME = N'つくば並木', BANK_SHIETN_NAME_RYAKU = N'つくば並木', BANK_SHITEN_FURIGANA = N'ツクバナミキ', KOUZA_NAME = N'エジソンショウジ（カ', CREATE_USER = N'安田　彬', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK_SHITEN)
UPDATE T SET BANK_SHITEN_NAME = N'つくば支店', BANK_SHIETN_NAME_RYAKU = N'つくば支店', BANK_SHITEN_FURIGANA = N'ツクバシテン', KOUZA_NAME = N'エジソンショウジ（カ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK_SHITEN)
UPDATE T SET BANK_SHITEN_NAME = N'筑波銀行', BANK_SHIETN_NAME_RYAKU = N'筑波銀行', BANK_SHITEN_FURIGANA = N'ツクバギンコウ', KOUZA_NAME = N'ツクバ支店', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK_SHITEN)
UPDATE T SET BANK_SHITEN_NAME = N'つくば支店', BANK_SHIETN_NAME_RYAKU = N'つくば支店', BANK_SHITEN_FURIGANA = N'ツクバシテン', KOUZA_NAME = N'あ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK_SHITEN)
UPDATE T SET BANK_SHITEN_NAME = N'つくば支店', BANK_SHIETN_NAME_RYAKU = N'つくば支店', BANK_SHITEN_FURIGANA = N'ア', KOUZA_NAME = N'あ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK_SHITEN)
UPDATE T SET BANK_SHITEN_NAME = N'つくば支店', BANK_SHIETN_NAME_RYAKU = N'つくば支店', BANK_SHITEN_FURIGANA = N'ツクバシゲンツクバシテン', KOUZA_NAME = N'あ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BANK_SHITEN)
UPDATE T SET BANK_SHITEN_NAME = N'竹田支店', BANK_SHIETN_NAME_RYAKU = N'竹田支店', BANK_SHITEN_FURIGANA = N'タケダシテン', KOUZA_NAME = N'テストコウザメイギ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 13;

