-- UPDATE script for table M_BUSHO (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 5

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUSHO)
UPDATE T SET BUSHO_NAME = N'共通', BUSHO_NAME_RYAKU = N'共通', BUSHO_FURIGANA = N'キョウツウ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUSHO)
UPDATE T SET BUSHO_NAME = N'本社営業部', BUSHO_NAME_RYAKU = N'本社営業部', BUSHO_FURIGANA = N'ホンシャエイギョウブ', CREATE_USER = N'初回ログイン用', UPDATE_USER = N'初回ログイン用' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUSHO)
UPDATE T SET BUSHO_NAME = N'収集運搬部', BUSHO_NAME_RYAKU = N'収集運搬部', BUSHO_FURIGANA = N'シュウシュウウンパンブ', CREATE_USER = N'初回ログイン用', UPDATE_USER = N'初回ログイン用' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUSHO)
UPDATE T SET BUSHO_NAME = N'管理本部', BUSHO_NAME_RYAKU = N'管理本部', BUSHO_FURIGANA = N'カンリホンブ', CREATE_USER = N'初回ログイン用', UPDATE_USER = N'初回ログイン用' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUSHO)
UPDATE T SET BUSHO_NAME = N'全部署', BUSHO_NAME_RYAKU = N'全部署', BUSHO_FURIGANA = N'ゼンブショ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 5;

