-- UPDATE script for table M_BUNRUI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 17

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUNRUI)
UPDATE T SET BUNRUI_NAME = N'廃プラ', BUNRUI_NAME_RYAKU = N'廃プラ', BUNRUI_FURIGANA = N'コウザンハイプラサンギョウハイキブツハイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUNRUI)
UPDATE T SET BUNRUI_NAME = N'繊維くず', BUNRUI_NAME_RYAKU = N'繊維くず', BUNRUI_FURIGANA = N'オデセインセンイクズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUNRUI)
UPDATE T SET BUNRUI_NAME = N'金属くず', BUNRUI_NAME_RYAKU = N'金属くず', BUNRUI_FURIGANA = N'ドウケイイッパンキンゾククズ．', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUNRUI)
UPDATE T SET BUNRUI_NAME = N'ガラス陶磁器', BUNRUI_NAME_RYAKU = N'ガラス陶磁器', BUNRUI_FURIGANA = N'テツ・アエンガラストウジキ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUNRUI)
UPDATE T SET BUNRUI_NAME = N'ステンレス系', BUNRUI_NAME_RYAKU = N'ステンレス系', BUNRUI_FURIGANA = N'ステンレスケイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUNRUI)
UPDATE T SET BUNRUI_NAME = N'アルミ系', BUNRUI_NAME_RYAKU = N'アルミ系', BUNRUI_FURIGANA = N'アルミケイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUNRUI)
UPDATE T SET BUNRUI_NAME = N'雑品系', BUNRUI_NAME_RYAKU = N'雑品系', BUNRUI_FURIGANA = N'ザッピンケイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUNRUI)
UPDATE T SET BUNRUI_NAME = N'紹介料', BUNRUI_NAME_RYAKU = N'紹介料', BUNRUI_FURIGANA = N'ショウカイリョウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUNRUI)
UPDATE T SET BUNRUI_NAME = N'住宅建設系廃棄物', BUNRUI_NAME_RYAKU = N'住宅建設系廃棄物', BUNRUI_FURIGANA = N'ジュウタクケンセツケイハイキブツ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUNRUI)
UPDATE T SET BUNRUI_NAME = N'道路建設系廃棄物', BUNRUI_NAME_RYAKU = N'道路建設系廃棄物', BUNRUI_FURIGANA = N'ドウロケンセツケイハイキブツ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUNRUI)
UPDATE T SET BUNRUI_NAME = N'医療系廃棄物', BUNRUI_NAME_RYAKU = N'医療系廃棄物', BUNRUI_FURIGANA = N'イリョウケイハイキブツ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUNRUI)
UPDATE T SET BUNRUI_NAME = N'木材加工系廃棄物', BUNRUI_NAME_RYAKU = N'木材加工系廃棄物', BUNRUI_FURIGANA = N'モクザイカコウケイハイキブツ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUNRUI)
UPDATE T SET BUNRUI_NAME = N'金属加工系廃棄物', BUNRUI_NAME_RYAKU = N'金属加工系廃棄物', BUNRUI_FURIGANA = N'キンゾクカコウケイハイキブツ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUNRUI)
UPDATE T SET BUNRUI_NAME = N'薬品加工系廃棄物', BUNRUI_NAME_RYAKU = N'薬品加工系廃棄物', BUNRUI_FURIGANA = N'ヤクヒンカコウケイハイキブツ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUNRUI)
UPDATE T SET BUNRUI_NAME = N'飲食加工系廃棄物', BUNRUI_NAME_RYAKU = N'飲食加工系廃棄物', BUNRUI_FURIGANA = N'インショクカコウケイハイキブツ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUNRUI)
UPDATE T SET BUNRUI_NAME = N'産廃', BUNRUI_NAME_RYAKU = N'産廃', BUNRUI_FURIGANA = N'サンパイ', CREATE_USER = N'沢口　賢治', UPDATE_USER = N'沢口　賢治' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_BUNRUI)
UPDATE T SET BUNRUI_NAME = N'スクラップ', BUNRUI_NAME_RYAKU = N'スクラップ', BUNRUI_FURIGANA = N'スクラップ', CREATE_USER = N'沢口　賢治', UPDATE_USER = N'沢口　賢治' WHERE rn = 17;

