-- UPDATE script for table M_CHIIKIBETSU_SHOBUN (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 2

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_SHOBUN)
UPDATE T SET HOUKOKU_SHOBUN_HOUHOU_NAME = N'焼却', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_SHOBUN)
UPDATE T SET HOUKOKU_SHOBUN_HOUHOU_NAME = N'破砕', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

