-- UPDATE script for table M_CHIIKIBETSU_JUUSHO (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 128

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'北海道', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'青森県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'岩手県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'宮城県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'秋田県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'山形県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'福島県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'茨城県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'栃木県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'群馬県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'埼玉県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'千葉県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'東京都', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'神奈川県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'新潟県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'富山県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'石川県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'福井県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'山梨県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'長野県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'岐阜県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'静岡県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'愛知県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'三重県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'滋賀県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'京都府', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'大阪府', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'兵庫県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'奈良県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'和歌山県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'鳥取県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'島根県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'岡山県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'広島県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'山口県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'徳島県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'香川県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'愛媛県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'高知県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'福岡県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'佐賀県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'長崎県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'熊本県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'大分県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'宮崎県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'鹿児島県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'沖縄県', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'旭川市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'札幌市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'函館市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'仙台市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'千葉市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'横浜市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'川崎市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'横須賀市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'新潟市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'金沢市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'岐阜市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'静岡市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'浜松市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'名古屋市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'京都市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 62;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'大阪市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 63;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'堺市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 64;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'東大阪市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 65;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'神戸市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 66;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'姫路市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 67;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'尼崎市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 68;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'和歌山市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 69;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'広島市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 70;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'呉市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 71;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'下関市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 72;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'北九州市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 73;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'福岡市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 74;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'大牟田市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 75;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'長崎市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 76;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'佐世保市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 77;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'熊本市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 78;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'鹿児島市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 79;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'岡山市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 80;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'宇都宮市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 81;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'富山市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 82;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'秋田市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 83;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'郡山市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 84;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'大分市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 85;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'松山市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 86;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'豊田市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 87;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'福山市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 88;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'高知市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 89;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'宮崎市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 90;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'いわき市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 91;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'長野市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 92;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'豊橋市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 93;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'高松市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 94;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'相模原市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 95;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'西宮市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 96;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'倉敷市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 97;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'さいたま市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 98;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'奈良市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 99;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'川越市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 100;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'船橋市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 101;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'岡崎市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 102;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'高槻市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 103;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'青森市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 104;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'八王子市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 105;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'盛岡市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 106;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'柏市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 107;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'久留米市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 108;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'前橋市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 109;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'大津市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 110;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'高崎市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 111;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'豊中市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 112;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'那覇市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 113;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'枚方市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 114;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'越谷市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 115;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'八戸市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 116;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'福島市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 117;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'川口市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 118;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'八尾市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 119;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'明石市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 120;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'鳥取市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 121;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'松江市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 122;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'山形市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 123;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'福井市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 124;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'甲府市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 125;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'寝屋川市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 126;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'つくば市', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 127;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_JUUSHO)
UPDATE T SET HOUKOKU_JUUSHO_NAME = N'岩沼', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 128;

