-- UPDATE script for table M_CHIIKIBETSU_BUNRUI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 144

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'燃え殻', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'汚泥', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃油', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃酸', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃アルカリ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃プラスチック', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'紙くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'木くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'繊維くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'動・植物性残さ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'ゴムくず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'金属くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'ガラス・陶磁器くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'鉱さい', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'がれき類', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'動物のふん尿', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'動物の死体', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'ばいじん', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'１３号廃棄物', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'非飛散性アスベスト', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'動物系固形不要物', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'ガラスくず・コンクリートくず及び陶磁器くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'政令第１３号廃棄物', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'引火性廃油', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'強酸', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'強アルカリ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'感染性廃棄物', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'特定有害産業廃棄物', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃油（揮発油類、灯油類及び軽油類）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃酸（ph２．０以下のものに限る。）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃アルカリ（ph１２．５以上のものに限る。）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'感染性産業廃棄物', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃PCB', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'PCB汚染物', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'PCB処理物', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'指定下水汚泥等', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'鉱さい（有害物質を含む鉱さい）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃石綿等', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'ばいじん（有害物質を含むばいじん）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'燃え殻（有害物質を含む燃え殻）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃油（有害物質を含む廃油）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'汚泥（有害物質を含む汚泥）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃酸（有害物質を含む廃酸）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃アルカリ（有害物質を含む廃アルカリ）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'その他', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'燃え殻', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'汚泥', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃油', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃酸', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃アルカリ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃プラスチック', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'紙くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'木くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'繊維くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'動・植物性残さ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'ゴムくず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'金属くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'ガラス・陶磁器くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'鉱さい', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'がれき類', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'動物のふん尿', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'動物の死体', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 62;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'ばいじん', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 63;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'１３号廃棄物', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 64;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'非飛散性アスベスト', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 65;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'動物系固形不要物', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 66;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'ガラスくず・コンクリートくず及び陶磁器くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 67;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'政令第１３号廃棄物', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 68;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'引火性廃油', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 69;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'強酸', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 70;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'強アルカリ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 71;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'感染性廃棄物', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 72;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'特定有害産業廃棄物', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 73;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃油（揮発油類、灯油類及び軽油類）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 74;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃酸（ph２．０以下のものに限る。）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 75;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃アルカリ（ph１２．５以上のものに限る。）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 76;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'感染性産業廃棄物', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 77;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃PCB', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 78;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'PCB汚染物', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 79;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'PCB処理物', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 80;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'指定下水汚泥等', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 81;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'鉱さい（有害物質を含む鉱さい）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 82;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃石綿等', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 83;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'ばいじん（有害物質を含むばいじん）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 84;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'燃え殻（有害物質を含む燃え殻）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 85;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃油（有害物質を含む廃油）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 86;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'汚泥（有害物質を含む汚泥）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 87;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃酸（有害物質を含む廃酸）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 88;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃アルカリ（有害物質を含む廃アルカリ）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 89;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'その他', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 90;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'燃えがら', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 91;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'おでい', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 92;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃プラスチック類', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 93;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'紙くず類', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 94;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'木くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 95;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'繊維くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 96;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'ガラスくず・コンクリートくず及び陶磁器くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 97;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'がれき類', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 98;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'混合', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 99;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'燃え殻', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 100;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'汚泥', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 101;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃油', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 102;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃酸', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 103;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃アルカリ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 104;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃プラスチック', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 105;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'紙くず', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 106;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'木くず', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 107;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'繊維くず', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 108;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'動・植物性残さ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 109;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'ゴムくず', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 110;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'金属くず', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 111;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'ガラス・陶磁器くず', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 112;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'鉱さい', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 113;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'がれき類', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 114;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'動物のふん尿', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 115;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'動物の死体', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 116;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'ばいじん', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 117;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'１３号廃棄物', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 118;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'非飛散性アスベスト', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 119;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'動物系固形不要物', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 120;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'ガラスくず・コンクリートくず及び陶磁器くず', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 121;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'政令第１３号廃棄物', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 122;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'引火性廃油', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 123;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'強酸', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 124;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'強アルカリ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 125;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'感染性廃棄物', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 126;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'特定有害産業廃棄物', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 127;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃油（揮発油類、灯油類及び軽油類）', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 128;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃酸（ph２．０以下のものに限る。）', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 129;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃アルカリ（ph１２．５以上のものに限る。）', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 130;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'感染性産業廃棄物', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 131;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃PCB', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 132;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'PCB汚染物', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 133;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'PCB処理物', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 134;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'指定下水汚泥等', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 135;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'鉱さい（有害物質を含む鉱さい）', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 136;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃石綿等', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 137;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'ばいじん（有害物質を含むばいじん）', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 138;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'燃え殻（有害物質を含む燃え殻）', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 139;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃油（有害物質を含む廃油）', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 140;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'汚泥（有害物質を含む汚泥）', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 141;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃酸（有害物質を含む廃酸）', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 142;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'廃アルカリ（有害物質を含む廃アルカリ）', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 143;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_BUNRUI)
UPDATE T SET HOUKOKU_BUNRUI_NAME = N'その他', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 144;

