-- UPDATE script for table M_CHIIKIBETSU_GYOUSHU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 4

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_GYOUSHU)
UPDATE T SET HOUKOKU_GYOUSHU_NAME = N'陬ｽ騾讌ｭ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_GYOUSHU)
UPDATE T SET HOUKOKU_GYOUSHU_NAME = N'陬ｽ騾讌ｭ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_GYOUSHU)
UPDATE T SET HOUKOKU_GYOUSHU_NAME = N'蟒ｺ險ｭ讌ｭ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_GYOUSHU)
UPDATE T SET HOUKOKU_GYOUSHU_NAME = N'繧ｽ繝輔ヨ繧ｦ繧ｧ繧｢', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 4;

