-- UPDATE script for table M_CHIIKIBETSU_SHISETSU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 3

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_SHISETSU)
UPDATE T SET HOUKOKU_SHISETSU_NAME = N'逕｣讌ｭ蟒・｣・黄縺ｮ辟ｼ蜊ｴ譁ｽ險ｭ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_SHISETSU)
UPDATE T SET HOUKOKU_SHISETSU_NAME = N'譛ｨ縺上★蜿医・縺後ｌ縺埼｡槭・遐ｴ遐墓命險ｭ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKIBETSU_SHISETSU)
UPDATE T SET HOUKOKU_SHISETSU_NAME = N'遐ｴ遐輔→蝨ｧ邵ｮ蝗ｺ蛹悶・譁ｽ險ｭ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 3;

