-- UPDATE script for table M_CHIIKI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 127

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'北海道', CHIIKI_NAME_RYAKU = N'北海道', CHIIKI_FURIGANA = N'ホッカイドウ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'青森県', CHIIKI_NAME_RYAKU = N'青森県', CHIIKI_FURIGANA = N'アオモリケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'岩手県', CHIIKI_NAME_RYAKU = N'岩手県', CHIIKI_FURIGANA = N'イワテケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'宮城県', CHIIKI_NAME_RYAKU = N'宮城県', CHIIKI_FURIGANA = N'ミヤギケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'秋田県', CHIIKI_NAME_RYAKU = N'秋田県', CHIIKI_FURIGANA = N'アキタケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'山形県', CHIIKI_NAME_RYAKU = N'山形県', CHIIKI_FURIGANA = N'ヤマガタケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'福島県', CHIIKI_NAME_RYAKU = N'福島県', CHIIKI_FURIGANA = N'フクシマケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'茨城県', CHIIKI_NAME_RYAKU = N'茨城県', CHIIKI_FURIGANA = N'イバラキケン', GOV_OR_MAY_NAME = N'大井川　和彦', CREATE_USER = N'edison', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'栃木県', CHIIKI_NAME_RYAKU = N'栃木県', CHIIKI_FURIGANA = N'トチギケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'群馬県', CHIIKI_NAME_RYAKU = N'群馬県', CHIIKI_FURIGANA = N'グンマケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'埼玉県', CHIIKI_NAME_RYAKU = N'埼玉県', CHIIKI_FURIGANA = N'サイタマケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'千葉県', CHIIKI_NAME_RYAKU = N'千葉県', CHIIKI_FURIGANA = N'チバケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'東京都', CHIIKI_NAME_RYAKU = N'東京都', CHIIKI_FURIGANA = N'トウキョウト', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'神奈川県', CHIIKI_NAME_RYAKU = N'神奈川県', CHIIKI_FURIGANA = N'カナガワケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'新潟県', CHIIKI_NAME_RYAKU = N'新潟県', CHIIKI_FURIGANA = N'ニイガタケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'富山県', CHIIKI_NAME_RYAKU = N'富山県', CHIIKI_FURIGANA = N'トヤマケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'石川県', CHIIKI_NAME_RYAKU = N'石川県', CHIIKI_FURIGANA = N'イシカワケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'福井県', CHIIKI_NAME_RYAKU = N'福井県', CHIIKI_FURIGANA = N'フクイケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'山梨県', CHIIKI_NAME_RYAKU = N'山梨県', CHIIKI_FURIGANA = N'ヤマナシケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'長野県', CHIIKI_NAME_RYAKU = N'長野県', CHIIKI_FURIGANA = N'ナガノケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'岐阜県', CHIIKI_NAME_RYAKU = N'岐阜県', CHIIKI_FURIGANA = N'ギフケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'静岡県', CHIIKI_NAME_RYAKU = N'静岡県', CHIIKI_FURIGANA = N'シズオカケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'愛知県', CHIIKI_NAME_RYAKU = N'愛知県', CHIIKI_FURIGANA = N'アイチケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'三重県', CHIIKI_NAME_RYAKU = N'三重県', CHIIKI_FURIGANA = N'ミエケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'滋賀県', CHIIKI_NAME_RYAKU = N'滋賀県', CHIIKI_FURIGANA = N'シガケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'京都府', CHIIKI_NAME_RYAKU = N'京都府', CHIIKI_FURIGANA = N'キョウトフ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'大阪府', CHIIKI_NAME_RYAKU = N'大阪府', CHIIKI_FURIGANA = N'オオサカフ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'兵庫県', CHIIKI_NAME_RYAKU = N'兵庫県', CHIIKI_FURIGANA = N'ヒョウゴケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'奈良県', CHIIKI_NAME_RYAKU = N'奈良県', CHIIKI_FURIGANA = N'ナラケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'和歌山県', CHIIKI_NAME_RYAKU = N'和歌山県', CHIIKI_FURIGANA = N'ワカヤマケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'鳥取県', CHIIKI_NAME_RYAKU = N'鳥取県', CHIIKI_FURIGANA = N'トットリケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'島根県', CHIIKI_NAME_RYAKU = N'島根県', CHIIKI_FURIGANA = N'シマネケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'岡山県', CHIIKI_NAME_RYAKU = N'岡山県', CHIIKI_FURIGANA = N'オカヤマケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'広島県', CHIIKI_NAME_RYAKU = N'広島県', CHIIKI_FURIGANA = N'ヒロシマケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'山口県', CHIIKI_NAME_RYAKU = N'山口県', CHIIKI_FURIGANA = N'ヤマグチケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'徳島県', CHIIKI_NAME_RYAKU = N'徳島県', CHIIKI_FURIGANA = N'トクシマケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'香川県', CHIIKI_NAME_RYAKU = N'香川県', CHIIKI_FURIGANA = N'カガワケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'愛媛県', CHIIKI_NAME_RYAKU = N'愛媛県', CHIIKI_FURIGANA = N'エヒメケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'高知県', CHIIKI_NAME_RYAKU = N'高知県', CHIIKI_FURIGANA = N'コウチケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'福岡県', CHIIKI_NAME_RYAKU = N'福岡県', CHIIKI_FURIGANA = N'フクオカケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'佐賀県', CHIIKI_NAME_RYAKU = N'佐賀県', CHIIKI_FURIGANA = N'サガケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'長崎県', CHIIKI_NAME_RYAKU = N'長崎県', CHIIKI_FURIGANA = N'ナガサキケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'熊本県', CHIIKI_NAME_RYAKU = N'熊本県', CHIIKI_FURIGANA = N'クマモトケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'大分県', CHIIKI_NAME_RYAKU = N'大分県', CHIIKI_FURIGANA = N'オオイタケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'宮崎県', CHIIKI_NAME_RYAKU = N'宮崎県', CHIIKI_FURIGANA = N'ミヤザキケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'鹿児島県', CHIIKI_NAME_RYAKU = N'鹿児島県', CHIIKI_FURIGANA = N'カゴシマケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'沖縄県', CHIIKI_NAME_RYAKU = N'沖縄県', CHIIKI_FURIGANA = N'オキナワケン', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'旭川市', CHIIKI_NAME_RYAKU = N'旭川市', CHIIKI_FURIGANA = N'アサヒカワシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'札幌市', CHIIKI_NAME_RYAKU = N'札幌市', CHIIKI_FURIGANA = N'サッポロシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'函館市', CHIIKI_NAME_RYAKU = N'函館市', CHIIKI_FURIGANA = N'ハコダテシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'仙台市', CHIIKI_NAME_RYAKU = N'仙台市', CHIIKI_FURIGANA = N'センダイシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'千葉市', CHIIKI_NAME_RYAKU = N'千葉市', CHIIKI_FURIGANA = N'チバシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'横浜市', CHIIKI_NAME_RYAKU = N'横浜市', CHIIKI_FURIGANA = N'ヨコハマシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'川崎市', CHIIKI_NAME_RYAKU = N'川崎市', CHIIKI_FURIGANA = N'カワサキシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'横須賀市', CHIIKI_NAME_RYAKU = N'横須賀市', CHIIKI_FURIGANA = N'ヨコスカシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'新潟市', CHIIKI_NAME_RYAKU = N'新潟市', CHIIKI_FURIGANA = N'ニイガタシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'金沢市', CHIIKI_NAME_RYAKU = N'金沢市', CHIIKI_FURIGANA = N'カナザワシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'岐阜市', CHIIKI_NAME_RYAKU = N'岐阜市', CHIIKI_FURIGANA = N'ギフシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'静岡市', CHIIKI_NAME_RYAKU = N'静岡市', CHIIKI_FURIGANA = N'シズオカシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'浜松市', CHIIKI_NAME_RYAKU = N'浜松市', CHIIKI_FURIGANA = N'ハママツシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'名古屋市', CHIIKI_NAME_RYAKU = N'名古屋市', CHIIKI_FURIGANA = N'ナゴヤシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'京都市', CHIIKI_NAME_RYAKU = N'京都市', CHIIKI_FURIGANA = N'キョウトシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 62;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'大阪市', CHIIKI_NAME_RYAKU = N'大阪市', CHIIKI_FURIGANA = N'オオサカシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 63;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'堺市', CHIIKI_NAME_RYAKU = N'堺市', CHIIKI_FURIGANA = N'サカイシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 64;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'東大阪市', CHIIKI_NAME_RYAKU = N'東大阪市', CHIIKI_FURIGANA = N'ヒガシオオサカシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 65;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'神戸市', CHIIKI_NAME_RYAKU = N'神戸市', CHIIKI_FURIGANA = N'コウベシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 66;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'姫路市', CHIIKI_NAME_RYAKU = N'姫路市', CHIIKI_FURIGANA = N'ヒメジシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 67;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'尼崎市', CHIIKI_NAME_RYAKU = N'尼崎市', CHIIKI_FURIGANA = N'アマガサキシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 68;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'和歌山市', CHIIKI_NAME_RYAKU = N'和歌山市', CHIIKI_FURIGANA = N'ワカヤマシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 69;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'広島市', CHIIKI_NAME_RYAKU = N'広島市', CHIIKI_FURIGANA = N'ヒロシマシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 70;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'呉市', CHIIKI_NAME_RYAKU = N'呉市', CHIIKI_FURIGANA = N'クレシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 71;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'下関市', CHIIKI_NAME_RYAKU = N'下関市', CHIIKI_FURIGANA = N'シモノセキシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 72;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'北九州市', CHIIKI_NAME_RYAKU = N'北九州市', CHIIKI_FURIGANA = N'キタキュウシュウシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 73;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'福岡市', CHIIKI_NAME_RYAKU = N'福岡市', CHIIKI_FURIGANA = N'フクオカシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 74;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'長崎市', CHIIKI_NAME_RYAKU = N'長崎市', CHIIKI_FURIGANA = N'ナガサキシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 75;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'佐世保市', CHIIKI_NAME_RYAKU = N'佐世保市', CHIIKI_FURIGANA = N'サセボシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 76;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'熊本市', CHIIKI_NAME_RYAKU = N'熊本市', CHIIKI_FURIGANA = N'クマモトシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 77;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'鹿児島市', CHIIKI_NAME_RYAKU = N'鹿児島市', CHIIKI_FURIGANA = N'カゴシマシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 78;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'岡山市', CHIIKI_NAME_RYAKU = N'岡山市', CHIIKI_FURIGANA = N'オカヤマシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 79;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'宇都宮市', CHIIKI_NAME_RYAKU = N'宇都宮市', CHIIKI_FURIGANA = N'ウツノミヤシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 80;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'富山市', CHIIKI_NAME_RYAKU = N'富山市', CHIIKI_FURIGANA = N'トヤマシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 81;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'秋田市', CHIIKI_NAME_RYAKU = N'秋田市', CHIIKI_FURIGANA = N'アキタシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 82;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'郡山市', CHIIKI_NAME_RYAKU = N'郡山市', CHIIKI_FURIGANA = N'コオリヤマシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 83;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'大分市', CHIIKI_NAME_RYAKU = N'大分市', CHIIKI_FURIGANA = N'オオイタシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 84;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'松山市', CHIIKI_NAME_RYAKU = N'松山市', CHIIKI_FURIGANA = N'マツヤマシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 85;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'豊田市', CHIIKI_NAME_RYAKU = N'豊田市', CHIIKI_FURIGANA = N'トヨタシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 86;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'福山市', CHIIKI_NAME_RYAKU = N'福山市', CHIIKI_FURIGANA = N'フクヤマシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 87;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'高知市', CHIIKI_NAME_RYAKU = N'高知市', CHIIKI_FURIGANA = N'コウチシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 88;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'宮崎市', CHIIKI_NAME_RYAKU = N'宮崎市', CHIIKI_FURIGANA = N'ミヤザキシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 89;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'いわき市', CHIIKI_NAME_RYAKU = N'いわき市', CHIIKI_FURIGANA = N'イワキシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 90;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'長野市', CHIIKI_NAME_RYAKU = N'長野市', CHIIKI_FURIGANA = N'ナガノシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 91;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'豊橋市', CHIIKI_NAME_RYAKU = N'豊橋市', CHIIKI_FURIGANA = N'トヨハシシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 92;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'高松市', CHIIKI_NAME_RYAKU = N'高松市', CHIIKI_FURIGANA = N'タカマツシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 93;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'相模原市', CHIIKI_NAME_RYAKU = N'相模原市', CHIIKI_FURIGANA = N'サガミハラシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 94;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'西宮市', CHIIKI_NAME_RYAKU = N'西宮市', CHIIKI_FURIGANA = N'ニシノミヤシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 95;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'倉敷市', CHIIKI_NAME_RYAKU = N'倉敷市', CHIIKI_FURIGANA = N'クラシキシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 96;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'さいたま市', CHIIKI_NAME_RYAKU = N'さいたま市', CHIIKI_FURIGANA = N'サイタマシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 97;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'奈良市', CHIIKI_NAME_RYAKU = N'奈良市', CHIIKI_FURIGANA = N'ナラシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 98;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'川越市', CHIIKI_NAME_RYAKU = N'川越市', CHIIKI_FURIGANA = N'カワゴエシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 99;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'船橋市', CHIIKI_NAME_RYAKU = N'船橋市', CHIIKI_FURIGANA = N'フナバシシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 100;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'岡崎市', CHIIKI_NAME_RYAKU = N'岡崎市', CHIIKI_FURIGANA = N'オカザキシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 101;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'高槻市', CHIIKI_NAME_RYAKU = N'高槻市', CHIIKI_FURIGANA = N'タカツキシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 102;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'青森市', CHIIKI_NAME_RYAKU = N'青森市', CHIIKI_FURIGANA = N'アオモリシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 103;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'八王子市', CHIIKI_NAME_RYAKU = N'八王子市', CHIIKI_FURIGANA = N'ハチオウジシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 104;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'盛岡市', CHIIKI_NAME_RYAKU = N'盛岡市', CHIIKI_FURIGANA = N'モリオカシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 105;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'柏市', CHIIKI_NAME_RYAKU = N'柏市', CHIIKI_FURIGANA = N'カシワシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 106;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'久留米市', CHIIKI_NAME_RYAKU = N'久留米市', CHIIKI_FURIGANA = N'クルメシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 107;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'前橋市', CHIIKI_NAME_RYAKU = N'前橋市', CHIIKI_FURIGANA = N'マエバシシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 108;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'大津市', CHIIKI_NAME_RYAKU = N'大津市', CHIIKI_FURIGANA = N'オオツシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 109;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'高崎市', CHIIKI_NAME_RYAKU = N'高崎市', CHIIKI_FURIGANA = N'タカサキシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 110;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'豊中市', CHIIKI_NAME_RYAKU = N'豊中市', CHIIKI_FURIGANA = N'トヨナカシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 111;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'那覇市', CHIIKI_NAME_RYAKU = N'那覇市', CHIIKI_FURIGANA = N'ナハシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 112;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'枚方市', CHIIKI_NAME_RYAKU = N'枚方市', CHIIKI_FURIGANA = N'ヒラカタシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 113;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'越谷市', CHIIKI_NAME_RYAKU = N'越谷市', CHIIKI_FURIGANA = N'コシガヤシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 114;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'八戸市', CHIIKI_NAME_RYAKU = N'八戸市', CHIIKI_FURIGANA = N'ハチノヘシ ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 115;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'福島市', CHIIKI_NAME_RYAKU = N'福島市', CHIIKI_FURIGANA = N'フクシマシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 116;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'川口市', CHIIKI_NAME_RYAKU = N'川口市', CHIIKI_FURIGANA = N'カワグチシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 117;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'八尾市', CHIIKI_NAME_RYAKU = N'八尾市', CHIIKI_FURIGANA = N'ヤオシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 118;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'明石市', CHIIKI_NAME_RYAKU = N'明石市', CHIIKI_FURIGANA = N'アカシシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 119;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'鳥取市', CHIIKI_NAME_RYAKU = N'鳥取市', CHIIKI_FURIGANA = N'トットリシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 120;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'松江市', CHIIKI_NAME_RYAKU = N'松江市', CHIIKI_FURIGANA = N'マツエシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 121;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'山形市', CHIIKI_NAME_RYAKU = N'山形市', CHIIKI_FURIGANA = N'ヤマガタシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 122;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'福井市', CHIIKI_NAME_RYAKU = N'福井市', CHIIKI_FURIGANA = N'フクイシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 123;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'甲府市', CHIIKI_NAME_RYAKU = N'甲府市', CHIIKI_FURIGANA = N'コウフシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 124;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'寝屋川市', CHIIKI_NAME_RYAKU = N'寝屋川市', CHIIKI_FURIGANA = N'ネヤガワシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 125;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'つくば市', CHIIKI_NAME_RYAKU = N'つくば市', CHIIKI_FURIGANA = N'ツクバシ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 126;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CHIIKI)
UPDATE T SET CHIIKI_NAME = N'岩沼', CHIIKI_NAME_RYAKU = N'岩沼', CHIIKI_FURIGANA = N'イワヌマ', GOV_OR_MAY_NAME = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 127;

