-- UPDATE script for table M_CONTENA_JOUKYOU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 3

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA_JOUKYOU)
UPDATE T SET CONTENA_JOUKYOU_NAME = N'交換', CONTENA_JOUKYOU_NAME_RYAKU = N'交換', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA_JOUKYOU)
UPDATE T SET CONTENA_JOUKYOU_NAME = N'設置', CONTENA_JOUKYOU_NAME_RYAKU = N'設置', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA_JOUKYOU)
UPDATE T SET CONTENA_JOUKYOU_NAME = N'引揚', CONTENA_JOUKYOU_NAME_RYAKU = N'引揚', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

