-- UPDATE script for table M_COURSE_NIOROSHI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 51

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000001' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000001' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000002' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000003' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000004' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000006' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000010' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000010' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000010' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000022' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000099' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000102' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000102' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000106' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'001112' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'002500' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'002501' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'002502' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'002503' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'123456' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'123456' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000001' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000002' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000003' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000004' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000005' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000007' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000105' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000105' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'002501' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'666666' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000001' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000002' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000003' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000004' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000007' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000022' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000001' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000002' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000003' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000004' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000009' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000001' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000002' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000002' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000003' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000004' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000001' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000002' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000003' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NIOROSHI)
UPDATE T SET COURSE_NAME_CD = N'000004' WHERE rn = 51;

