-- UPDATE script for table M_CONTENA (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 18

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA)
UPDATE T SET CONTENA_NAME = N'2㎥コンテナ001', CONTENA_NAME_RYAKU = N'2㎥コンテナ001', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA)
UPDATE T SET CONTENA_NAME = N'一時配置用', CONTENA_NAME_RYAKU = N'一時配置用', CREATE_USER = N'佐藤　花子', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA)
UPDATE T SET CONTENA_NAME = N'4㎥コンテナ001', CONTENA_NAME_RYAKU = N'4㎥コンテナ001', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA)
UPDATE T SET CONTENA_NAME = N'4㎥コンテナ002', CONTENA_NAME_RYAKU = N'4㎥コンテナ002', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA)
UPDATE T SET CONTENA_NAME = N'4㎥コンテナ003', CONTENA_NAME_RYAKU = N'4㎥コンテナ003', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA)
UPDATE T SET CONTENA_NAME = N'004', CONTENA_NAME_RYAKU = N'004', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA)
UPDATE T SET CONTENA_NAME = N'4m3コンテナ005', CONTENA_NAME_RYAKU = N'4m3コンテナ005', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA)
UPDATE T SET CONTENA_NAME = N'8㎥コンテナ001', CONTENA_NAME_RYAKU = N'8㎥コンテナ001', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA)
UPDATE T SET CONTENA_NAME = N'8㎥コンテナ002', CONTENA_NAME_RYAKU = N'8㎥コンテナ002', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA)
UPDATE T SET CONTENA_NAME = N'コンテナ００８', CONTENA_NAME_RYAKU = N'コンテナ００８', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA)
UPDATE T SET CONTENA_NAME = N'8㎡コンテナ003', CONTENA_NAME_RYAKU = N'8㎡コンテナ003', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA)
UPDATE T SET CONTENA_NAME = N'1㎥缶００１', CONTENA_NAME_RYAKU = N'1㎥缶００１', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA)
UPDATE T SET CONTENA_NAME = N'ＢＯＸ１１３５', CONTENA_NAME_RYAKU = N'ＢＯＸ１１３５', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA)
UPDATE T SET CONTENA_NAME = N'ＢＯＸ３５２４', CONTENA_NAME_RYAKU = N'ＢＯＸ３５２４', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA)
UPDATE T SET CONTENA_NAME = N'ＢＯＸ３７２６', CONTENA_NAME_RYAKU = N'ＢＯＸ３７２６', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA)
UPDATE T SET CONTENA_NAME = N'ＢＯＸ６４１５', CONTENA_NAME_RYAKU = N'ＢＯＸ６４１５', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA)
UPDATE T SET CONTENA_NAME = N'ＢＯＸ６４１６', CONTENA_NAME_RYAKU = N'ＢＯＸ６４１６', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA)
UPDATE T SET CONTENA_NAME = N'仮設トイレ０００１', CONTENA_NAME_RYAKU = N'仮設トイレ０００１', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 18;

