-- UPDATE script for table M_COURSE_NAME (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 56

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000001', COURSE_NAME = N'一般　可燃コース①', COURSE_NAME_RYAKU = N'一般　可燃コース①', COURSE_NAME_FURIGANA = N'イッパンツチウラモリヤコースイッパンカネ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000002', COURSE_NAME = N'一般　可燃コース②', COURSE_NAME_RYAKU = N'一般　可燃コース②', COURSE_NAME_FURIGANA = N'イッパンカシワ・トリデ・ツクバコースイッ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000003', COURSE_NAME = N'NAVITIMEつくばコース', COURSE_NAME_RYAKU = N'NAVITIMEつくばコース', COURSE_NAME_FURIGANA = N'シゲンコースツクバ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'佐藤　花子' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000004', COURSE_NAME = N'NAVITIME土浦コース', COURSE_NAME_RYAKU = N'NAVITIME土浦コース', COURSE_NAME_FURIGANA = N'ツチウラシゲンコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'佐藤　花子' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000005', COURSE_NAME = N'廃プラコース', COURSE_NAME_RYAKU = N'廃プラコース', COURSE_NAME_FURIGANA = N'ハイプラコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000006', COURSE_NAME = N'葛飾コース', COURSE_NAME_RYAKU = N'葛飾コース', COURSE_NAME_FURIGANA = N'カツシカコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000007', COURSE_NAME = N'MAPBOXテスト', COURSE_NAME_RYAKU = N'MAPBOXテスト', COURSE_NAME_FURIGANA = N'ＭＡＰＢＯＸテスト', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000008', COURSE_NAME = N'ショートメッセージコース', COURSE_NAME_RYAKU = N'メッセージコース', COURSE_NAME_FURIGANA = N'ショートメッセージコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000009', COURSE_NAME = N'土浦コース', COURSE_NAME_RYAKU = N'土浦コース', COURSE_NAME_FURIGANA = N'ツチウラコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000010', COURSE_NAME = N'テスト', COURSE_NAME_RYAKU = N'テスト', COURSE_NAME_FURIGANA = N'テスト', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000011', COURSE_NAME = N'熊本市街コース１', COURSE_NAME_RYAKU = N'熊本市街コース１', COURSE_NAME_FURIGANA = N'クマモトシガイコース１', COURSE_NAME_BIKOU = N'テスト備考', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000012', COURSE_NAME = N'宇都宮コース', COURSE_NAME_RYAKU = N'宇都宮コース', COURSE_NAME_FURIGANA = N'ウツノミヤコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000020', COURSE_NAME = N'第一水曜日', COURSE_NAME_RYAKU = N'第一水曜日', COURSE_NAME_FURIGANA = N'ダイイチスイヨウビ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000022', COURSE_NAME = N'医廃‗東部コース', COURSE_NAME_RYAKU = N'医廃‗東部コース', COURSE_NAME_FURIGANA = N'イハイイハイトウブコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'鈴木　次郎' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000023', COURSE_NAME = N'医廃‗西部コース', COURSE_NAME_RYAKU = N'医廃‗西部コース', COURSE_NAME_FURIGANA = N'イハイセイブコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'鈴木　次郎' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000099', COURSE_NAME = N'手入力用', COURSE_NAME_RYAKU = N'手入力用', COURSE_NAME_FURIGANA = N'テニュウリョクヨウ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000100', COURSE_NAME = N'土浦　可燃物コース', COURSE_NAME_RYAKU = N'土浦　可燃物コース', COURSE_NAME_FURIGANA = N'ツチウラ　カネンブツコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000101', COURSE_NAME = N'土浦　不燃物コース', COURSE_NAME_RYAKU = N'土浦　不燃物コース', COURSE_NAME_FURIGANA = N'カヨウビセイニクテンコースツチウラフネン', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000102', COURSE_NAME = N'県央　可燃物コース', COURSE_NAME_RYAKU = N'県央　可燃物コース', COURSE_NAME_FURIGANA = N'スイヨウビセイニクテンコースケンオウカネ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000103', COURSE_NAME = N'県央　不燃物コース', COURSE_NAME_RYAKU = N'県央　不燃物コース', COURSE_NAME_FURIGANA = N'モクヨウビセイニクテンコースケンオウフネ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000104', COURSE_NAME = N'県央　ビンカンペットコース', COURSE_NAME_RYAKU = N'県央　ビンカンペット', COURSE_NAME_FURIGANA = N'キンヨウビセイニクテンコースケンオウビン', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000105', COURSE_NAME = N'県西　可燃物コース', COURSE_NAME_RYAKU = N'県西　可燃物コース', COURSE_NAME_FURIGANA = N'ケンセイカネンブツコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000106', COURSE_NAME = N'適用期間確認用', COURSE_NAME_RYAKU = N'適用期間確認用', COURSE_NAME_FURIGANA = N'テキヨウテキヨウキカンカクニンヨウ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000200', COURSE_NAME = N'カモメ運送', COURSE_NAME_RYAKU = N'カモメ運送', COURSE_NAME_FURIGANA = N'カモメウンソウ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000201', COURSE_NAME = N'ＪＥＭＳ運送', COURSE_NAME_RYAKU = N'ＪＥＭＳ運送', COURSE_NAME_FURIGANA = N'ＪＥＭＳウンソウ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000202', COURSE_NAME = N'仮コース（車両なし）', COURSE_NAME_RYAKU = N'仮コース（車両なし）', COURSE_NAME_FURIGANA = N'ｓｅｋｉｋｏ－カリコースシャリョウナシ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000203', COURSE_NAME = N'適用期間確認コース', COURSE_NAME_RYAKU = N'適用期間確認コース', COURSE_NAME_FURIGANA = N'テキヨウキカンカクニンコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000222', COURSE_NAME = N'広島市街', COURSE_NAME_RYAKU = N'広島市街', COURSE_NAME_FURIGANA = N'ヒロシマシガイ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000400', COURSE_NAME = N'スポット＆コース回収ドライバ', COURSE_NAME_RYAKU = N'スポット＆コース回収', COURSE_NAME_FURIGANA = N'スポットアンドコースカイシュウドライバ０', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'000999', COURSE_NAME = N'クリーン環境　月曜コース', COURSE_NAME_RYAKU = N'クリーン環境　月曜コ', COURSE_NAME_FURIGANA = N'クリーンカンキョウゲツヨウビコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'001000', COURSE_NAME = N'クリーン環境　火曜コース', COURSE_NAME_RYAKU = N'クリーン環境　火曜コ', COURSE_NAME_FURIGANA = N'クリーンカンキョウカヨウカヨウビコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'001001', COURSE_NAME = N'クリーン環境　水曜コース', COURSE_NAME_RYAKU = N'クリーン環境　水曜コ', COURSE_NAME_FURIGANA = N'クリーンカンキョウスイヨウビコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'001002', COURSE_NAME = N'クリーン環境　木曜コース', COURSE_NAME_RYAKU = N'クリーン環境　木曜コ', COURSE_NAME_FURIGANA = N'クリーンカンキョウモクヨウビコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'001111', COURSE_NAME = N'あいうえお地区敏感ペッ', COURSE_NAME_RYAKU = N'あいうえお地区敏感ペ', COURSE_NAME_FURIGANA = N'マルマルアイウエオチクビンカンペット', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'鈴木　次郎' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'001112', COURSE_NAME = N'秋葉　可燃コース', COURSE_NAME_RYAKU = N'秋葉　可燃コース', COURSE_NAME_FURIGANA = N'アキバカネンコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'001219', COURSE_NAME = N'池田商店回収', COURSE_NAME_RYAKU = N'池田商店回収', COURSE_NAME_FURIGANA = N'イケダショウテンカイシュウ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'001234', COURSE_NAME = N'町田月曜日コース', COURSE_NAME_RYAKU = N'町田月曜日コース', COURSE_NAME_FURIGANA = N'マチダゲツヨウビコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'001983', COURSE_NAME = N'車両1983コース', COURSE_NAME_RYAKU = N'車両1983コース', COURSE_NAME_FURIGANA = N'シャリョウＮｏＮｏ５６９シャリョウ１９８', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'安田　彬', UPDATE_USER = N'鈴木　次郎' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'002490', COURSE_NAME = N'北区　可燃物コース', COURSE_NAME_RYAKU = N'北区　可燃物コース', COURSE_NAME_FURIGANA = N'キタクカネンブツコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'002500', COURSE_NAME = N'中区　古紙コース', COURSE_NAME_RYAKU = N'中区　古紙コース', COURSE_NAME_FURIGANA = N'ナカクカネンブツコースコシカイシュウ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'002501', COURSE_NAME = N'中区　一般廃コース', COURSE_NAME_RYAKU = N'中区　一般廃コース', COURSE_NAME_FURIGANA = N'ナカクイッパンパイハイコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'002502', COURSE_NAME = N'北区　ダンボール', COURSE_NAME_RYAKU = N'北区　ダンボール', COURSE_NAME_FURIGANA = N'キタクキタクボールダン', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'002503', COURSE_NAME = N'池田商店（月極）コース', COURSE_NAME_RYAKU = N'池田（月極）', COURSE_NAME_FURIGANA = N'イケダホクブイケダショウテンツキギメツキ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'002504', COURSE_NAME = N'JEMSエンジニアリング', COURSE_NAME_RYAKU = N'JEMSエンジニアリング', COURSE_NAME_FURIGANA = N'フジエンジニアリングＪＥＭＳ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'025001', COURSE_NAME = N'下妻　可燃物コース', COURSE_NAME_RYAKU = N'下妻　可燃物コース', COURSE_NAME_FURIGANA = N'シモツマカネンブツコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'100000', COURSE_NAME = N'産廃　プラコース', COURSE_NAME_RYAKU = N'産廃　プラコース', COURSE_NAME_FURIGANA = N'ゲツサンパイプラプララコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'123121', COURSE_NAME = N'岩槻区横根家庭ごみ可燃コース', COURSE_NAME_RYAKU = N'岩槻区横根家庭ごみ可', COURSE_NAME_FURIGANA = N'イワツキクヨコネカテイケイカテイゴミカネ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'123455', COURSE_NAME = N'デモコース作成用', COURSE_NAME_RYAKU = N'デモコース作成用', COURSE_NAME_FURIGANA = N'デモコースサクセイヨウ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'123456', COURSE_NAME = N'外注依頼用', COURSE_NAME_RYAKU = N'外注依頼用', COURSE_NAME_FURIGANA = N'ガイチュウイライヨウガイチュウイライヨウ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'240708', COURSE_NAME = N'新規仮作成', COURSE_NAME_RYAKU = N'新規仮作成', COURSE_NAME_FURIGANA = N'シンキカリサクセイカリサクセイ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'666666', COURSE_NAME = N'テストコース', COURSE_NAME_RYAKU = N'テストコース', COURSE_NAME_FURIGANA = N'テストコース', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'777777', COURSE_NAME = N'手入力', COURSE_NAME_RYAKU = N'手入力', COURSE_NAME_FURIGANA = N'テニュウリョク', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'800000', COURSE_NAME = N'テストコース広島', COURSE_NAME_RYAKU = N'テストコース広島', COURSE_NAME_FURIGANA = N'テストコースヒロシマ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'888888', COURSE_NAME = N'テスト①', COURSE_NAME_RYAKU = N'テスト①', COURSE_NAME_FURIGANA = N'テスト１', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'999998', COURSE_NAME = N'テスト', COURSE_NAME_RYAKU = N'テスト', COURSE_NAME_FURIGANA = N'テスト', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE_NAME)
UPDATE T SET COURSE_NAME_CD = N'999999', COURSE_NAME = N'外注依頼用', COURSE_NAME_RYAKU = N'外注依頼用', COURSE_NAME_FURIGANA = N'ガイチュウイライヨウガイチュウイライヨウ', COURSE_NAME_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 56;

