-- UPDATE script for table M_COURSE (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 88

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000001', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000002', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000003', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000004', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000005', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000006', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000007', CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000010', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000011', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000012', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000022', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000099', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000100', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000102', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000103', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000106', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000200', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000202', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000203', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000222', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000400', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000999', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'001112', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'001219', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'001983', CREATE_USER = N'安田　彬', UPDATE_USER = N'安田　彬' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'002500', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'002501', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'002502', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'002503', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'123121', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'123455', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'123456', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'240708', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'666666', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'999998', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'999999', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000001', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000002', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000003', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000004', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000005', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000007', CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000099', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000105', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000222', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'001000', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'002501', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'002504', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'123121', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'666666', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000001', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000002', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000003', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000004', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000007', CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000022', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000099', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000222', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'001001', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'002490', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'002501', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'999999', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 62;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000001', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 63;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000002', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 64;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000003', CREATE_USER = N'西田　栄一', UPDATE_USER = N'鈴木　次郎' WHERE rn = 65;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000004', CREATE_USER = N'西田　栄一', UPDATE_USER = N'鈴木　次郎' WHERE rn = 66;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000007', CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 67;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000009', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 68;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000099', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 69;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000100', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 70;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000222', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 71;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'002501', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 72;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'888888', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 73;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000001', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 74;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000002', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 75;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000003', CREATE_USER = N'西田　栄一', UPDATE_USER = N'鈴木　次郎' WHERE rn = 76;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000004', CREATE_USER = N'西田　栄一', UPDATE_USER = N'鈴木　次郎' WHERE rn = 77;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000007', CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 78;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000008', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 79;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000099', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 80;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'123121', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 81;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'123456', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 82;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000001', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 83;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000002', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 84;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000003', CREATE_USER = N'西田　栄一', UPDATE_USER = N'鈴木　次郎' WHERE rn = 85;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'000004', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 86;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'888888', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 87;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_COURSE)
UPDATE T SET COURSE_NAME_CD = N'001983', CREATE_USER = N'沢口　賢治', UPDATE_USER = N'沢口　賢治' WHERE rn = 88;

