-- UPDATE script for table M_CONTENA_SHURUI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 10

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA_SHURUI)
UPDATE T SET CONTENA_SHURUI_NAME = N'2m3コンテナ', CONTENA_SHURUI_NAME_RYAKU = N'2m3コンテナ', CONTENA_SHURUI_FURIGANA = N'２リュウベイコンテナ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA_SHURUI)
UPDATE T SET CONTENA_SHURUI_NAME = N'4m3コンテナ', CONTENA_SHURUI_NAME_RYAKU = N'4m3コンテナ', CONTENA_SHURUI_FURIGANA = N'４リュウベイコンテナ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA_SHURUI)
UPDATE T SET CONTENA_SHURUI_NAME = N'8m3コンテナ', CONTENA_SHURUI_NAME_RYAKU = N'8m3コンテナ', CONTENA_SHURUI_FURIGANA = N'８リュウベイコンテナ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA_SHURUI)
UPDATE T SET CONTENA_SHURUI_NAME = N'フレコンバック', CONTENA_SHURUI_NAME_RYAKU = N'フレコンバック', CONTENA_SHURUI_FURIGANA = N'フレコンバック', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA_SHURUI)
UPDATE T SET CONTENA_SHURUI_NAME = N'20リットルBOX', CONTENA_SHURUI_NAME_RYAKU = N'20リットルBOX', CONTENA_SHURUI_FURIGANA = N'２０リットルＢＯＸ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA_SHURUI)
UPDATE T SET CONTENA_SHURUI_NAME = N'8m3コンテナ　ドア付', CONTENA_SHURUI_NAME_RYAKU = N'8m3コンテナ　ド', CONTENA_SHURUI_FURIGANA = N'テナナドアツキツキ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA_SHURUI)
UPDATE T SET CONTENA_SHURUI_NAME = N'1㎥缶', CONTENA_SHURUI_NAME_RYAKU = N'1㎥缶', CONTENA_SHURUI_FURIGANA = N'１リュウベイカン', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA_SHURUI)
UPDATE T SET CONTENA_SHURUI_NAME = N'2㎥缶', CONTENA_SHURUI_NAME_RYAKU = N'2㎥缶', CONTENA_SHURUI_FURIGANA = N'２リュウベイカン', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA_SHURUI)
UPDATE T SET CONTENA_SHURUI_NAME = N'ＢＯＸ', CONTENA_SHURUI_NAME_RYAKU = N'ＢＯＸ', CONTENA_SHURUI_FURIGANA = N'ＢＯＸ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CONTENA_SHURUI)
UPDATE T SET CONTENA_SHURUI_NAME = N'仮設トイレ', CONTENA_SHURUI_NAME_RYAKU = N'仮設トイレ', CONTENA_SHURUI_FURIGANA = N'カセツトイレ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

