-- UPDATE script for table M_CO2_HAIKIBUTSU_KEISUU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 19

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'燃えがら', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'汚泥', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'廃油', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'廃酸', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'廃アルカリ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'廃プラスチック類', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'紙くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'木くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'繊維くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'動植物性残渣注1', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'動物系固形不要物', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'ゴムくず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'金属くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'ガラス陶磁器くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'鉱さい', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'がれき類', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'動物のふん尿', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'動物の死体', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_HAIKIBUTSU_KEISUU)
UPDATE T SET GVCPF_NAME = N'ばいじん', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 19;

