-- UPDATE script for table M_CO2_SYS_INFO (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 1

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_CO2_SYS_INFO)
UPDATE T SET CREATE_USER = NULL, UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

