-- UPDATE script for table M_DENSHI_HAIKI_SHURUI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 131

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'燃え殻', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'焼却灰', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'石炭灰', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃棄物の焼却灰', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃カーボン・活性炭', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'汚泥（泥状のもの）', CREATE_USER = N'edison', UPDATE_USER = N'新川　拓哉' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'有機性汚泥', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'下水汚泥', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'無機性汚泥', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'建設汚泥（残土を除く）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'上水汚泥', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃油', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'一般廃油', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'鉱物性油', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'動植物性油', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃溶剤', CREATE_USER = N'edison', UPDATE_USER = N'新川　拓哉' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'固形油', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'油でい', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃酸', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'写真定着廃液', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃アルカリ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'写真現像廃液', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃プラスチック類', CREATE_USER = N'edison', UPDATE_USER = N'新川　拓哉' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃タイヤ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'自動車用プラスチックバンパー', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃農業用ビニール', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'プラスチック製廃容器包装', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'発泡スチロール', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'発泡ウレタン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'発泡ポリスチレン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'塩化ビニル製建設資材', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'紙くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'建設工事の紙くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ダンボール', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'木くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'建設工事の木くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'伐採材・伐根材', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'繊維くず（天然繊維くず）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'建設工事の繊維くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'動・植物性残渣', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ゴムくず（天然ゴムくず）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'金属くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'鉄くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'非鉄金属くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'鉛製の管又は板', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'電線くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ガラスくず、コンクリートくず及び陶磁器くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ガラスくず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'カレット', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃ブラウン管（側面部）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ガラス製廃容器包装', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ロックウール', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'石綿（非飛散性）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'グラスウール', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'岩綿吸音板', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'陶磁器くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'コンクリートくず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'石膏ボード', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ＡＬＣ（軽量気泡コンクリート）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'鉱さい', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'スラグ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'がれき類（工作物の新築、改築又は除去に伴って生じた不要物）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 62;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'コンクリート破片', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 63;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'アスファルト・コンクリート破片', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 64;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'動物のふん尿（畜産農業から排出されたもの）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 65;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'動物の死体（畜産農業から排出されたもの）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 66;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ばいじん（工場の排ガスを処理して得られるばいじん）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 67;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'処分するために処理したもの（１３号廃棄物）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 68;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'建設混合廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 69;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'安定型建設混合廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 70;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'管理型建設混合廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 71;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'新築系混合廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 72;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'解体系混合廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 73;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'安定型混合廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 74;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'管理型混合廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 75;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'シュレッダーダスト', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 76;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'建設混合廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 77;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ガラスくず、コンクリートくず及び陶磁器くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 78;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃プラスチック類', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 79;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'がれき類（工作物の新築、改築又は除去に伴って生じた不要物）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 80;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'紙くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 81;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'木くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 82;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'繊維くず（天然繊維くず）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 83;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'汚泥', CREATE_USER = N'jems', UPDATE_USER = N'jems' WHERE rn = 84;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃自動車', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 85;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃二輪車', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 86;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'バイク', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 87;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'自転車', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 88;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃電気機械器具', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 89;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃パチンコ機及び廃パチスロ機', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 90;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'プリント配線板', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 91;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'テレビジョン受信機', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 92;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'エアーコンディショナー', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 93;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'冷蔵庫', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 94;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'洗濯機', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 95;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'電子レンジ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 96;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'パーソナルコンピュータ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 97;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'電話機', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 98;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'自動販売機', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 99;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'蛍光灯', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 100;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'冷凍庫', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 101;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'水銀体温計', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 102;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'水銀血圧計', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 103;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃電池類', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 104;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'鉛蓄電池', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 105;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'乾電池', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 106;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'複合材', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 107;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'動物系固形不要物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 108;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'燃えやすい廃油', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 109;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'燃えやすい廃油（基準値を超える有害物質を含むもの）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 110;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ph２．０以下の廃酸', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 111;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ph２．０以下の廃酸（基準値を超える有害物質を含むもの）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 112;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ph１２．５以上の廃アルカリ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 113;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ph１２．５以上の廃アルカリ（基準値を超える有害物質を含むも', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 114;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'感染性廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 115;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'特定有害産業廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 116;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃ＰＣＢ等・ＰＣＢ汚染物・ＰＣＢ処理物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 117;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃ＰＣＢ等', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 118;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ＰＣＢ汚染物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 119;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ＰＣＢ処理物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 120;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃石綿等（飛散性）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 121;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'指定下水汚泥', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 122;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'鉱さい（基準値を超える有害物質を含むもの）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 123;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'燃え殻（基準値を超える有害物質を含むもの）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 124;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃油（基準値を超える有害物質を含むもの）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 125;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'汚泥（基準値を超える有害物質を含むもの）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 126;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃酸（基準値を超える有害物質を含むもの）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 127;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃アルカリ（基準値を超える有害物質を含むもの）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 128;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ばいじん（基準値を超える有害物質を含むもの）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 129;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'処分するために処理したもの（基準値を超える有害物質を含むもの', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 130;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃水銀等（処分するために処理したものを含む）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 131;

