-- UPDATE script for table M_DENSHI_JIGYOUSHA (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 11

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUSHA)
UPDATE T SET JIGYOUSHA_NAME = N'王子マテリア株式会社　松本工場', JIGYOUSHA_POST = N'399-0033', JIGYOUSHA_ADDRESS1 = N'長野県', JIGYOUSHA_ADDRESS2 = N'松本市', JIGYOUSHA_ADDRESS3 = N'笹賀', JIGYOUSHA_ADDRESS4 = N'５２００－１', JIGYOUSHA_TEL = N'0263-25-5432', JIGYOUSHA_FAX = N'', CREATE_USER = N'西田　栄一', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUSHA)
UPDATE T SET JIGYOUSHA_NAME = N'王子マテリア株式会社　中津川・恵那工場', JIGYOUSHA_POST = N'508-8585', JIGYOUSHA_ADDRESS1 = N'岐阜県', JIGYOUSHA_ADDRESS2 = N'中津川市', JIGYOUSHA_ADDRESS3 = N'小川町', JIGYOUSHA_ADDRESS4 = N'２番３号', JIGYOUSHA_TEL = N'0573-66-1511', JIGYOUSHA_FAX = N'0573-66-7228', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUSHA)
UPDATE T SET JIGYOUSHA_NAME = N'本田', JIGYOUSHA_POST = N'321-0221', JIGYOUSHA_ADDRESS1 = N'栃木県', JIGYOUSHA_ADDRESS2 = N'下都賀郡壬生町', JIGYOUSHA_ADDRESS3 = N'藤井', JIGYOUSHA_ADDRESS4 = N'', JIGYOUSHA_TEL = N'', JIGYOUSHA_FAX = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUSHA)
UPDATE T SET JIGYOUSHA_NAME = N'株式会社中部建設', JIGYOUSHA_POST = N'460-0002', JIGYOUSHA_ADDRESS1 = N'愛知県', JIGYOUSHA_ADDRESS2 = N'名古屋市中区', JIGYOUSHA_ADDRESS3 = N'丸の内', JIGYOUSHA_ADDRESS4 = N'111', JIGYOUSHA_TEL = N'052-111-1111', JIGYOUSHA_FAX = N'052-222-2222', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUSHA)
UPDATE T SET JIGYOUSHA_NAME = N'三日月クリーン開発', JIGYOUSHA_POST = N'450-0002', JIGYOUSHA_ADDRESS1 = N'愛知県', JIGYOUSHA_ADDRESS2 = N'名古屋市中村区', JIGYOUSHA_ADDRESS3 = N'名駅（その他）', JIGYOUSHA_ADDRESS4 = N'', JIGYOUSHA_TEL = N'', JIGYOUSHA_FAX = N'', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUSHA)
UPDATE T SET JIGYOUSHA_NAME = N'セイコーエプソン株式会社', JIGYOUSHA_POST = N'392-8502', JIGYOUSHA_ADDRESS1 = N'長野県', JIGYOUSHA_ADDRESS2 = N'諏訪市', JIGYOUSHA_ADDRESS3 = N'大和３－３－５', JIGYOUSHA_ADDRESS4 = N'', JIGYOUSHA_TEL = N'', JIGYOUSHA_FAX = N'', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'西田　栄一' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUSHA)
UPDATE T SET JIGYOUSHA_NAME = N'事業者名称', JIGYOUSHA_POST = N'305-0033', JIGYOUSHA_ADDRESS1 = N'茨城県', JIGYOUSHA_ADDRESS2 = N'つくば市', JIGYOUSHA_ADDRESS3 = N'東新井３１－１３', JIGYOUSHA_ADDRESS4 = N'JEMSビル１F', JIGYOUSHA_TEL = N'029-863-7215', JIGYOUSHA_FAX = N'029-863-7216', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUSHA)
UPDATE T SET JIGYOUSHA_NAME = N'株式会社西尾商店', JIGYOUSHA_POST = N'508-0014', JIGYOUSHA_ADDRESS1 = N'岐阜県', JIGYOUSHA_ADDRESS2 = N'中津川市', JIGYOUSHA_ADDRESS3 = N'駒場町', JIGYOUSHA_ADDRESS4 = N'3番37号', JIGYOUSHA_TEL = N'0573-65-2708', JIGYOUSHA_FAX = N'0573-66-7255', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUSHA)
UPDATE T SET JIGYOUSHA_NAME = N'株式会社エジソン商事', JIGYOUSHA_POST = N'450-0002', JIGYOUSHA_ADDRESS1 = N'愛知県', JIGYOUSHA_ADDRESS2 = N'名古屋市中村区', JIGYOUSHA_ADDRESS3 = N'名駅（その他）', JIGYOUSHA_ADDRESS4 = N'', JIGYOUSHA_TEL = N'052', JIGYOUSHA_FAX = N'', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUSHA)
UPDATE T SET JIGYOUSHA_NAME = N'医療法人社団　みなみ病院', JIGYOUSHA_POST = N'300-1206', JIGYOUSHA_ADDRESS1 = N'茨城県', JIGYOUSHA_ADDRESS2 = N'牛久市', JIGYOUSHA_ADDRESS3 = N'ひたち野西', JIGYOUSHA_ADDRESS4 = N'', JIGYOUSHA_TEL = N'026-222-2222', JIGYOUSHA_FAX = N'', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUSHA)
UPDATE T SET JIGYOUSHA_NAME = N'株式会社大脇商店', JIGYOUSHA_POST = N'509-0125', JIGYOUSHA_ADDRESS1 = N'岐阜県', JIGYOUSHA_ADDRESS2 = N'各務原市', JIGYOUSHA_ADDRESS3 = N'鵜沼南町', JIGYOUSHA_ADDRESS4 = N'２－１８７', JIGYOUSHA_TEL = N'058-384-0340', JIGYOUSHA_FAX = N'058-370-3586', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 11;

