-- UPDATE script for table M_DENSHI_SHINSEI_NAIYOU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 3

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_SHINSEI_NAIYOU)
UPDATE T SET NAIYOU_NAME = N'取引先', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_SHINSEI_NAIYOU)
UPDATE T SET NAIYOU_NAME = N'業者', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_SHINSEI_NAIYOU)
UPDATE T SET NAIYOU_NAME = N'現場', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

