-- UPDATE script for table M_DENSHI_HAIKI_SHURUI_SAIBUNRUI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 1

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_SHURUI_SAIBUNRUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'鉛付産業廃棄物なんとか', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 1;

