-- UPDATE script for table M_DENSHI_SHINSEI_ROUTE_NAME (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 6

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_SHINSEI_ROUTE_NAME)
UPDATE T SET DENSHI_SHINSEI_ROUTE_NAME = N'WF通常', DENSHI_SHINSEI_ROUTE_FURIGANA = N'ワークフローケイロ１', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_SHINSEI_ROUTE_NAME)
UPDATE T SET DENSHI_SHINSEI_ROUTE_NAME = N'WF役員決裁', DENSHI_SHINSEI_ROUTE_FURIGANA = N'ワークフローケッサイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_SHINSEI_ROUTE_NAME)
UPDATE T SET DENSHI_SHINSEI_ROUTE_NAME = N'引合取引先', DENSHI_SHINSEI_ROUTE_FURIGANA = N'ヒキアイサキトリヒ', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_SHINSEI_ROUTE_NAME)
UPDATE T SET DENSHI_SHINSEI_ROUTE_NAME = N'引合業者', DENSHI_SHINSEI_ROUTE_FURIGANA = N'ヒキアイギョウシャ', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_SHINSEI_ROUTE_NAME)
UPDATE T SET DENSHI_SHINSEI_ROUTE_NAME = N'引合現場', DENSHI_SHINSEI_ROUTE_FURIGANA = N'ヒキアイゲンバ', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_SHINSEI_ROUTE_NAME)
UPDATE T SET DENSHI_SHINSEI_ROUTE_NAME = N'見積申請', DENSHI_SHINSEI_ROUTE_FURIGANA = N'ミツモリシンセイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

