-- UPDATE script for table M_DENSHU_KBN (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 39

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'受入', DENSHU_KBN_NAME_RYAKU = N'受入', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'出荷', DENSHU_KBN_NAME_RYAKU = N'出荷', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'売上支払', DENSHU_KBN_NAME_RYAKU = N'売上支払', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'共通', DENSHU_KBN_NAME_RYAKU = N'共通', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'入金', DENSHU_KBN_NAME_RYAKU = N'入金', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'出金', DENSHU_KBN_NAME_RYAKU = N'出金', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'請求', DENSHU_KBN_NAME_RYAKU = N'請求', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'請求締', DENSHU_KBN_NAME_RYAKU = N'請求締', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'支払', DENSHU_KBN_NAME_RYAKU = N'支払', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'支払締', DENSHU_KBN_NAME_RYAKU = N'支払締', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'紙マニフェスト', DENSHU_KBN_NAME_RYAKU = N'紙マニ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'電子マニフェスト', DENSHU_KBN_NAME_RYAKU = N'電マニ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'受付', DENSHU_KBN_NAME_RYAKU = N'受付', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'配車', DENSHU_KBN_NAME_RYAKU = N'配車', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'定期配車', DENSHU_KBN_NAME_RYAKU = N'定期配車', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'定期実績', DENSHU_KBN_NAME_RYAKU = N'定期実績', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'計量', DENSHU_KBN_NAME_RYAKU = N'計量', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'在庫', DENSHU_KBN_NAME_RYAKU = N'在庫', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'在庫締', DENSHU_KBN_NAME_RYAKU = N'在庫締', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'物販在庫', DENSHU_KBN_NAME_RYAKU = N'物販在庫', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'物販在庫締', DENSHU_KBN_NAME_RYAKU = N'物販在庫締', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'運賃', DENSHU_KBN_NAME_RYAKU = N'運賃', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'代納', DENSHU_KBN_NAME_RYAKU = N'代納', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'見積', DENSHU_KBN_NAME_RYAKU = N'見積', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'受注目標', DENSHU_KBN_NAME_RYAKU = N'受注目標', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'営業予算', DENSHU_KBN_NAME_RYAKU = N'営業予算', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'委託契約', DENSHU_KBN_NAME_RYAKU = N'委託契約', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'覚書一括', DENSHU_KBN_NAME_RYAKU = N'覚書一括', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'取引先', DENSHU_KBN_NAME_RYAKU = N'取引先', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'業者', DENSHU_KBN_NAME_RYAKU = N'業者', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'現場', DENSHU_KBN_NAME_RYAKU = N'現場', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'電マニ事業者', DENSHU_KBN_NAME_RYAKU = N'電子事業者', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'電マニ事業場', DENSHU_KBN_NAME_RYAKU = N'電子事業場', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'入金先', DENSHU_KBN_NAME_RYAKU = N'入金先', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'出金先', DENSHU_KBN_NAME_RYAKU = N'出金先', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'コース', DENSHU_KBN_NAME_RYAKU = N'コース', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'汎用CSV出力', DENSHU_KBN_NAME_RYAKU = N'汎用CSV出力', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'実績報告書', DENSHU_KBN_NAME_RYAKU = N'報告書', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHU_KBN)
UPDATE T SET DENSHU_KBN_NAME = N'電子区分', DENSHU_KBN_NAME_RYAKU = N'電子区分', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 39;

