-- UPDATE script for table M_DENSHI_KEIYAKU_SHORUI_INFO (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 10

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHORUI_INFO)
UPDATE T SET SHORUI_INFO_NAME = N'営業担当者', CREATE_USER = N'作成者', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHORUI_INFO)
UPDATE T SET SHORUI_INFO_NAME = N'', CREATE_USER = N'作成者', UPDATE_USER = N'更新者' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHORUI_INFO)
UPDATE T SET SHORUI_INFO_NAME = N'テスト項目名２', CREATE_USER = N'作成者', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHORUI_INFO)
UPDATE T SET SHORUI_INFO_NAME = N'', CREATE_USER = N'作成者', UPDATE_USER = N'更新者' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHORUI_INFO)
UPDATE T SET SHORUI_INFO_NAME = N'', CREATE_USER = N'作成者', UPDATE_USER = N'更新者' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHORUI_INFO)
UPDATE T SET SHORUI_INFO_NAME = N'', CREATE_USER = N'作成者', UPDATE_USER = N'更新者' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHORUI_INFO)
UPDATE T SET SHORUI_INFO_NAME = N'', CREATE_USER = N'作成者', UPDATE_USER = N'更新者' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHORUI_INFO)
UPDATE T SET SHORUI_INFO_NAME = N'', CREATE_USER = N'作成者', UPDATE_USER = N'更新者' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHORUI_INFO)
UPDATE T SET SHORUI_INFO_NAME = N'', CREATE_USER = N'作成者', UPDATE_USER = N'更新者' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHORUI_INFO)
UPDATE T SET SHORUI_INFO_NAME = N'', CREATE_USER = N'作成者', UPDATE_USER = N'更新者' WHERE rn = 10;

