-- UPDATE script for table M_DENPYOU_KBN (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 3

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENPYOU_KBN)
UPDATE T SET DENPYOU_KBN_NAME = N'売上', DENPYOU_KBN_NAME_RYAKU = N'売上', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENPYOU_KBN)
UPDATE T SET DENPYOU_KBN_NAME = N'支払', DENPYOU_KBN_NAME_RYAKU = N'支払', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENPYOU_KBN)
UPDATE T SET DENPYOU_KBN_NAME = N'共通', DENPYOU_KBN_NAME_RYAKU = N'共通', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

