-- UPDATE script for table M_DENSHI_HAIKI_NAME (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 10

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000001', HAIKI_NAME = N'廃プラテスト', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000005', HAIKI_NAME = N'石膏ボード', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'001100', HAIKI_NAME = N'汚泥', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000111', HAIKI_NAME = N'その他部品', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'001111', HAIKI_NAME = N'ＡＢＳ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'001112', HAIKI_NAME = N'ＰＥ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'001113', HAIKI_NAME = N'ＰＳ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'001114', HAIKI_NAME = N'液晶', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000012', HAIKI_NAME = N'感染性', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'900000', HAIKI_NAME = N'ソファー', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 10;

