-- UPDATE script for table M_DENSHI_KEIYAKU_SHANAI_KEIRO (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 11

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'1', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'2', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'2', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'2', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'3', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'3', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'4', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'5', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'5', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'6', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'7', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 11;

