-- UPDATE script for table M_DENSHI_SHINSEI_JYUYOUDO (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 3

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_SHINSEI_JYUYOUDO)
UPDATE T SET JYUYOUDO_NAME = N'通常顧客', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_SHINSEI_JYUYOUDO)
UPDATE T SET JYUYOUDO_NAME = N'重要顧客', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_SHINSEI_JYUYOUDO)
UPDATE T SET JYUYOUDO_NAME = N'その他', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 3;

