-- UPDATE script for table M_DENSHI_JIGYOUJOU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 13

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUJOU)
UPDATE T SET JIGYOUJOU_NAME = N'王子マテリア株式会社　松本工場', JIGYOUJOU_POST = N'399-0033', JIGYOUJOU_ADDRESS1 = N'長野県', JIGYOUJOU_ADDRESS2 = N'松本市', JIGYOUJOU_ADDRESS3 = N'笹賀', JIGYOUJOU_ADDRESS4 = N'５２００－１', JIGYOUJOU_TEL = N'0263-25-5432', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUJOU)
UPDATE T SET JIGYOUJOU_NAME = N'王子マテリア株式会社　恵那工場', JIGYOUJOU_POST = N'509-7201', JIGYOUJOU_ADDRESS1 = N'岐阜県', JIGYOUJOU_ADDRESS2 = N'恵那市', JIGYOUJOU_ADDRESS3 = N'大井町', JIGYOUJOU_ADDRESS4 = N'６９６番地', JIGYOUJOU_TEL = N'0573-26-1638', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUJOU)
UPDATE T SET JIGYOUJOU_NAME = N'浅井工務店', JIGYOUJOU_POST = N'305-0033', JIGYOUJOU_ADDRESS1 = N'茨城県', JIGYOUJOU_ADDRESS2 = N'つくば市', JIGYOUJOU_ADDRESS3 = N'東新井', JIGYOUJOU_ADDRESS4 = N'123－23', JIGYOUJOU_TEL = N'0298637215', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUJOU)
UPDATE T SET JIGYOUJOU_NAME = N'本田', JIGYOUJOU_POST = N'321-0813', JIGYOUJOU_ADDRESS1 = N'茨城県', JIGYOUJOU_ADDRESS2 = N'土浦市', JIGYOUJOU_ADDRESS3 = N'', JIGYOUJOU_ADDRESS4 = N'', JIGYOUJOU_TEL = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUJOU)
UPDATE T SET JIGYOUJOU_NAME = N'１号線黄金陸橋交差点舗装工事 3期', JIGYOUJOU_POST = N'450-0002', JIGYOUJOU_ADDRESS1 = N'愛知県', JIGYOUJOU_ADDRESS2 = N'名古屋市中村区', JIGYOUJOU_ADDRESS3 = N'名駅（その他）', JIGYOUJOU_ADDRESS4 = N'111', JIGYOUJOU_TEL = N'052-222-2222', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUJOU)
UPDATE T SET JIGYOUJOU_NAME = N'三日月リサイクルセンター', JIGYOUJOU_POST = N'450-0005', JIGYOUJOU_ADDRESS1 = N'愛知県', JIGYOUJOU_ADDRESS2 = N'名古屋市中村区', JIGYOUJOU_ADDRESS3 = N'西日置', JIGYOUJOU_ADDRESS4 = N'', JIGYOUJOU_TEL = N'052', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUJOU)
UPDATE T SET JIGYOUJOU_NAME = N'かきく', JIGYOUJOU_POST = N'460-0002', JIGYOUJOU_ADDRESS1 = N'', JIGYOUJOU_ADDRESS2 = N'', JIGYOUJOU_ADDRESS3 = N'', JIGYOUJOU_ADDRESS4 = N'', JIGYOUJOU_TEL = N'052', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUJOU)
UPDATE T SET JIGYOUJOU_NAME = N'かきく', JIGYOUJOU_POST = N'460-0002', JIGYOUJOU_ADDRESS1 = N'愛知県', JIGYOUJOU_ADDRESS2 = N'名古屋市中村区', JIGYOUJOU_ADDRESS3 = N'西日置', JIGYOUJOU_ADDRESS4 = N'', JIGYOUJOU_TEL = N'052', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUJOU)
UPDATE T SET JIGYOUJOU_NAME = N'松本事業所', JIGYOUJOU_POST = N'390-0863', JIGYOUJOU_ADDRESS1 = N'長野県', JIGYOUJOU_ADDRESS2 = N'松本市', JIGYOUJOU_ADDRESS3 = N'白板', JIGYOUJOU_ADDRESS4 = N'2-4-14', JIGYOUJOU_TEL = N'', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'鈴木　次郎' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUJOU)
UPDATE T SET JIGYOUJOU_NAME = N'株式会社西尾商店　 積替保管施設', JIGYOUJOU_POST = N'508-0014', JIGYOUJOU_ADDRESS1 = N'岐阜県', JIGYOUJOU_ADDRESS2 = N'中津川市', JIGYOUJOU_ADDRESS3 = N'駒場町', JIGYOUJOU_ADDRESS4 = N'961番2', JIGYOUJOU_TEL = N'0573-65-2708', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUJOU)
UPDATE T SET JIGYOUJOU_NAME = N'水戸中間処理場', JIGYOUJOU_POST = N'450-0002', JIGYOUJOU_ADDRESS1 = N'愛知県', JIGYOUJOU_ADDRESS2 = N'名古屋市中村区', JIGYOUJOU_ADDRESS3 = N'名駅（その他）', JIGYOUJOU_ADDRESS4 = N'', JIGYOUJOU_TEL = N'052', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUJOU)
UPDATE T SET JIGYOUJOU_NAME = N'医療法人社団　みなみ病院', JIGYOUJOU_POST = N'300-1206', JIGYOUJOU_ADDRESS1 = N'茨城県', JIGYOUJOU_ADDRESS2 = N'牛久市', JIGYOUJOU_ADDRESS3 = N'ひたち野西', JIGYOUJOU_ADDRESS4 = N'', JIGYOUJOU_TEL = N'', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_JIGYOUJOU)
UPDATE T SET JIGYOUJOU_NAME = N'（株）大脇商店　恵那工場', JIGYOUJOU_POST = N'509-7204', JIGYOUJOU_ADDRESS1 = N'岐阜県', JIGYOUJOU_ADDRESS2 = N'恵那市', JIGYOUJOU_ADDRESS3 = N'長島町永田', JIGYOUJOU_ADDRESS4 = N'木ノ下５４６－２５', JIGYOUJOU_TEL = N'0573-20-0366', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 13;

