-- UPDATE script for table M_DENSHI_KEIYAKU_SHANAI_KEIRO_NAME (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 7

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO_NAME)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'1', DENSHI_KEIYAKU_SHANAI_KEIRO_NAME = N'社内申請経路（上長）', DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_FURIGANA = N'シャナイシンセイケイ', CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO_NAME)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'2', DENSHI_KEIYAKU_SHANAI_KEIRO_NAME = N'申請（部長/社長含）', DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_FURIGANA = N'シャナイシンセイシャ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO_NAME)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'3', DENSHI_KEIYAKU_SHANAI_KEIRO_NAME = N'畠中テスト申請経路', DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_FURIGANA = N'ハタケナカハタケナカ', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO_NAME)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'4', DENSHI_KEIYAKU_SHANAI_KEIRO_NAME = N'申請経路テスト（Z）', DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_FURIGANA = N'シンセイケイロテスト', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO_NAME)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'5', DENSHI_KEIYAKU_SHANAI_KEIRO_NAME = N'社内申請経路（テスト', DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_FURIGANA = N'シャナイシンセイケイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO_NAME)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'6', DENSHI_KEIYAKU_SHANAI_KEIRO_NAME = N'WF（マニュアル用）', DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_FURIGANA = N'シャナイシンセイケイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_DENSHI_KEIYAKU_SHANAI_KEIRO_NAME)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'7', DENSHI_KEIYAKU_SHANAI_KEIRO_NAME = N'マニュアルテスト用', DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_FURIGANA = N'マニュアルテストヨウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

