-- UPDATE script for table M_ECODRAFT_HAIKI_SHURUI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 61

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'燃えがら', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'汚泥', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃油', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃酸', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃アルカリ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃プラスチック類', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'紙くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'木くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'繊維くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'動植物性残さ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ゴムくず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'金属くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ガラス/コンクリート・陶磁器くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'鉱さい', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'がれき類', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'家畜のふん尿', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'動物の死体', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ばいじん', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'13号廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'動物系固形不要物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'引火性廃油', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'引火性廃油（有害 ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'強酸', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'強酸（有害 ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'強アルカリ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'強アルカリ（有害 ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'感染性廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'PCB等', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃石棉等', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'指定下水汚泥', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'鉱さい（有害 ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'燃えがら（有害 ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃油（有害 ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'汚泥（有害 ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃酸（有害 ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃アルカリ（有害 ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ばいじん（有害 ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'13号廃棄物（有害 ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'コンクリートがら がれき類', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'アスファルト・コンクリートがら がれき類', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'その他がれき類 がれき類', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ガラスくず・コンクリートくず及び陶磁器くず 廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃プラスチック類 廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'金属くず 廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'紙くず 廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'木くず 廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'繊維くず 廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃石膏ボード 廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'建設汚泥 廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'安定型品目のみ 混合廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'管理型品目含む 混合廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'がれき類 石綿廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ガラスくず・コンクリートくず及び陶磁器くず 石綿廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃プラスチック類 石綿廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'その他 石綿廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'その他 廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃石綿等 特管廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ｶﾞﾗｽくず、ｺﾝｸﾘｰﾄくず及び陶磁器くず 水銀廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'金属くず 水銀廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'その他 水銀廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'その他 特管廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 61;

