-- UPDATE script for table M_ECODRAFT_KYOKA_HINMOKU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 58

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'燃えがら', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'汚泥', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'廃油', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'廃酸', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'廃アルカリ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'廃プラスチック類', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'紙くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'木くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'繊維くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'動植物性残さ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'ゴムくず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'金属くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'ガラス/コンクリート・陶磁器くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'鉱さい', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'がれき類', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'家畜のふん尿', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'動物の死体', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'ばいじん', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'13号廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'動物系固形不要物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'汚泥のコンクリート固形化物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'引火性廃油', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'強酸（有害）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'強アルカリ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'感染性廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'廃ポリ塩化ビフェニル(PCB)等', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'ポリ塩化ビフェニル(PCB)汚染物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'ポリ塩化ビフェニル(PCB)処理物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'指定下水汚泥', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'鉱さい（有害）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'汚泥（有害）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'コンクリートがら', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'アスコンがら', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'その他がれき類', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'ガラス・陶磁器くず', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'混合 (安定型のみ)', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'石綿含有産業廃棄物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'建設汚泥', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'廃石膏ボード', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'混合 (管理型含む)', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'廃石綿等', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'廃油(廃溶剤)', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'その他', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'廃水銀等', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'冷蔵庫(冷凍庫)', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'テレビ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'洗濯機', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'エアコン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'指定再資源化製品', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'パソコン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'小型二次電池', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'コンクリート塊(金属くず混じり含む)', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'アスファルト・コンクリート', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'木くず(土木建築に関する工事に使用する資材に限る)', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'廃自動車', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'クーラー', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'携帯電話', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT_KYOKA_HINMOKU)
UPDATE T SET KYOKA_HINMOKU_NAME = N'デジカメ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 58;

