-- UPDATE script for table M_ECODRAFT (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 36

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ECODRAFT)
UPDATE T SET COMPANY_NAME = N'', REPRESENTATIVE_NAME = N'', POST = N'', ADDRESS = N'' WHERE rn = 36;

