-- UPDATE script for table M_GENBAMEMO_HYOUDAI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 5

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBAMEMO_HYOUDAI)
UPDATE T SET GENBAMEMO_HYOUDAI_NAME = N'業務連絡', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBAMEMO_HYOUDAI)
UPDATE T SET GENBAMEMO_HYOUDAI_NAME = N'ゴミ回収情報', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBAMEMO_HYOUDAI)
UPDATE T SET GENBAMEMO_HYOUDAI_NAME = N'担当者確認事項', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBAMEMO_HYOUDAI)
UPDATE T SET GENBAMEMO_HYOUDAI_NAME = N'運転者確認事項', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBAMEMO_HYOUDAI)
UPDATE T SET GENBAMEMO_HYOUDAI_NAME = N'確認後折返連絡（緊急）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

