-- UPDATE script for table M_GENBAMEMO_BUNRUI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 10

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBAMEMO_BUNRUI)
UPDATE T SET GENBAMEMO_BUNRUI_NAME = N'クレーム', GENBAMEMO_BUNRUI_NAME_RYAKU = N'クレーム', GENBAMEMO_BUNRUI_FURIGANA = N'クレーム', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBAMEMO_BUNRUI)
UPDATE T SET GENBAMEMO_BUNRUI_NAME = N'顧客契約（受取資料）', GENBAMEMO_BUNRUI_NAME_RYAKU = N'顧客契約（受取資料）', GENBAMEMO_BUNRUI_FURIGANA = N'コキャクケイヤクテイキョウシリョウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBAMEMO_BUNRUI)
UPDATE T SET GENBAMEMO_BUNRUI_NAME = N'INXS連携（受取資料）', GENBAMEMO_BUNRUI_NAME_RYAKU = N'INXS連携（受取資料）', GENBAMEMO_BUNRUI_FURIGANA = N'ＩＮＸＳレンケイウケトリシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBAMEMO_BUNRUI)
UPDATE T SET GENBAMEMO_BUNRUI_NAME = N'受付', GENBAMEMO_BUNRUI_NAME_RYAKU = N'受付', GENBAMEMO_BUNRUI_FURIGANA = N'ウケツケウケトリ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBAMEMO_BUNRUI)
UPDATE T SET GENBAMEMO_BUNRUI_NAME = N'廃棄物回収前', GENBAMEMO_BUNRUI_NAME_RYAKU = N'廃棄物回収前', GENBAMEMO_BUNRUI_FURIGANA = N'カイシュウマエハイキブツ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBAMEMO_BUNRUI)
UPDATE T SET GENBAMEMO_BUNRUI_NAME = N'廃棄物回収後', GENBAMEMO_BUNRUI_NAME_RYAKU = N'廃棄物回収後', GENBAMEMO_BUNRUI_FURIGANA = N'カイシュウゴハイキブツ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBAMEMO_BUNRUI)
UPDATE T SET GENBAMEMO_BUNRUI_NAME = N'現場確認資料', GENBAMEMO_BUNRUI_NAME_RYAKU = N'現場確認資料', GENBAMEMO_BUNRUI_FURIGANA = N'ゲンバカクニンシリョウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBAMEMO_BUNRUI)
UPDATE T SET GENBAMEMO_BUNRUI_NAME = N'搬入許可証', GENBAMEMO_BUNRUI_NAME_RYAKU = N'搬入許可証', GENBAMEMO_BUNRUI_FURIGANA = N'ハンニュウキョカショウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBAMEMO_BUNRUI)
UPDATE T SET GENBAMEMO_BUNRUI_NAME = N'委託契約書', GENBAMEMO_BUNRUI_NAME_RYAKU = N'委託契約書', GENBAMEMO_BUNRUI_FURIGANA = N'イタクケイヤクショ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBAMEMO_BUNRUI)
UPDATE T SET GENBAMEMO_BUNRUI_NAME = N'受渡確認票', GENBAMEMO_BUNRUI_NAME_RYAKU = N'受渡確認票', GENBAMEMO_BUNRUI_FURIGANA = N'ウケワタシカクニンヒョウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

