-- UPDATE script for table M_GENBA_DIGI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 4

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_DIGI)
UPDATE T SET POINT_NAME = N'ｅｄｇｅ(エッジ)', POINT_KANA_NAME = N'ｅｄｇｅ', MAP_NAME = N'ｅｄｇｅ(エッジ)', POST_CODE = N'305-8577', ADDRESS1 = N'つくば市天王台一丁目1番地1', ADDRESS2 = N'', TEL_NO = N'029-853-2111', FAX_NO = N'', CONTACT_NAME = N'筑紫　聡', MAIL_ADDRESS = NULL, KEITAI_TEL = N'', GENBA_NAME1 = N'株式会社　edge', GENBA_NAME2 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_DIGI)
UPDATE T SET POINT_NAME = N'ＳＢＳ', POINT_KANA_NAME = N'テスト', MAP_NAME = N'ＳＢＳ', POST_CODE = N'300-1273', ADDRESS1 = N'つくば市下岩崎708-1', ADDRESS2 = N'', TEL_NO = N'029-876-5050', FAX_NO = N'029-876-5051', CONTACT_NAME = N'', MAIL_ADDRESS = NULL, KEITAI_TEL = N'', GENBA_NAME1 = N'ＳＢＳ株式会社', GENBA_NAME2 = N'', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_DIGI)
UPDATE T SET POINT_NAME = N'１０００', POINT_KANA_NAME = N'１０００', MAP_NAME = N'１０００', POST_CODE = N'532-0021', ADDRESS1 = N'大阪市淀川区田川北3-4-46', ADDRESS2 = N'', TEL_NO = N'', FAX_NO = N'', CONTACT_NAME = N'', MAIL_ADDRESS = NULL, KEITAI_TEL = N'', GENBA_NAME1 = N'１０００', GENBA_NAME2 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_DIGI)
UPDATE T SET POINT_NAME = N'モリ製作所', POINT_KANA_NAME = N'モリセイサクジョ', MAP_NAME = N'モリ製作所', POST_CODE = N'', ADDRESS1 = N'', ADDRESS2 = N'', TEL_NO = N'', FAX_NO = N'', CONTACT_NAME = N'', MAIL_ADDRESS = NULL, KEITAI_TEL = N'', GENBA_NAME1 = N'株式会社モリ製作所', GENBA_NAME2 = N'', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 4;

