-- UPDATE script for table M_GENBA_TSUKI_HINMEI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 96

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'ペットボトル超過分' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'紙くす　※超過あり' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'契約数量超過分' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'超過した時の品名' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'一般廃棄物　超過分' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'超過分　収集運搬費' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'aaaa' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'超過分　' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'超過分' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 62;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 63;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'超過分（紙くず）' WHERE rn = 64;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 65;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 66;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 67;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 68;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 69;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 70;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 71;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 72;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 73;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 74;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 75;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 76;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 77;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 78;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 79;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 80;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 81;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 82;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 83;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'可燃ごみ（超過分）' WHERE rn = 84;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'雑誌（超過分）' WHERE rn = 85;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'塵芥（超過分）' WHERE rn = 86;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 87;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'可燃物（契約重量超過）' WHERE rn = 88;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'不燃物（契約重量超過）' WHERE rn = 89;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 90;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 91;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 92;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 93;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'超過分不燃ごみ' WHERE rn = 94;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'' WHERE rn = 95;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENBA_TSUKI_HINMEI)
UPDATE T SET CHOUKA_HINMEI_NAME = N'超過料金分' WHERE rn = 96;

