-- UPDATE script for table M_GENCHAKU_TIME (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 13

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENCHAKU_TIME)
UPDATE T SET GENCHAKU_TIME_NAME = N'AM', GENCHAKU_TIME_NAME_RYAKU = N'AM', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENCHAKU_TIME)
UPDATE T SET GENCHAKU_TIME_NAME = N'PM', GENCHAKU_TIME_NAME_RYAKU = N'PM', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENCHAKU_TIME)
UPDATE T SET GENCHAKU_TIME_NAME = N'朝', GENCHAKU_TIME_NAME_RYAKU = N'朝', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENCHAKU_TIME)
UPDATE T SET GENCHAKU_TIME_NAME = N'昼', GENCHAKU_TIME_NAME_RYAKU = N'昼', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENCHAKU_TIME)
UPDATE T SET GENCHAKU_TIME_NAME = N'時間指定', GENCHAKU_TIME_NAME_RYAKU = N'時間指定', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENCHAKU_TIME)
UPDATE T SET GENCHAKU_TIME_NAME = N'いつでもOK', GENCHAKU_TIME_NAME_RYAKU = N'いつでもOK', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENCHAKU_TIME)
UPDATE T SET GENCHAKU_TIME_NAME = N'全部指定', GENCHAKU_TIME_NAME_RYAKU = N'全部指定', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENCHAKU_TIME)
UPDATE T SET GENCHAKU_TIME_NAME = N'折り返し', GENCHAKU_TIME_NAME_RYAKU = N'折り返し', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENCHAKU_TIME)
UPDATE T SET GENCHAKU_TIME_NAME = N'来週中', GENCHAKU_TIME_NAME_RYAKU = N'来週中', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENCHAKU_TIME)
UPDATE T SET GENCHAKU_TIME_NAME = N'3か月に1回', GENCHAKU_TIME_NAME_RYAKU = N'3か月に1回', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENCHAKU_TIME)
UPDATE T SET GENCHAKU_TIME_NAME = N'9～10', GENCHAKU_TIME_NAME_RYAKU = N'9～10', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENCHAKU_TIME)
UPDATE T SET GENCHAKU_TIME_NAME = N'11～12', GENCHAKU_TIME_NAME_RYAKU = N'11～12', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GENCHAKU_TIME)
UPDATE T SET GENCHAKU_TIME_NAME = N'12～13', GENCHAKU_TIME_NAME_RYAKU = N'12～13', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 13;

