-- UPDATE script for table M_GYOUSHU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 12

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GYOUSHU)
UPDATE T SET GYOUSHU_NAME = N'陬ｽ騾讌ｭ', GYOUSHU_NAME_RYAKU = N'陬ｽ騾讌ｭ', GYOUSHU_FURIGANA = N'セイゾウギョウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GYOUSHU)
UPDATE T SET GYOUSHU_NAME = N'蟒ｺ險ｭ讌ｭ', GYOUSHU_NAME_RYAKU = N'蟒ｺ險ｭ讌ｭ', GYOUSHU_FURIGANA = N'ケンセツギョウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GYOUSHU)
UPDATE T SET GYOUSHU_NAME = N'繧ｽ繝輔ヨ繧ｦ繧ｧ繧｢', GYOUSHU_NAME_RYAKU = N'繧ｽ繝輔ヨ繧ｦ繧ｧ繧｢', GYOUSHU_FURIGANA = N'ソフトウェア', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GYOUSHU)
UPDATE T SET GYOUSHU_NAME = N'譛ｨ騾蟒ｺ遽臥黄隗｣菴灘・蛻・･ｭ', GYOUSHU_NAME_RYAKU = N'譛ｨ騾蟒ｺ遽臥黄隗｣菴灘・蛻・･ｭ', GYOUSHU_FURIGANA = N'モクゾウケンチクブツカイタイショブンギョウ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GYOUSHU)
UPDATE T SET GYOUSHU_NAME = N'繝薙Ν隗｣菴捺･ｭ', GYOUSHU_NAME_RYAKU = N'繝薙Ν隗｣菴捺･ｭ', GYOUSHU_FURIGANA = N'ビルカイタイギョウ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GYOUSHU)
UPDATE T SET GYOUSHU_NAME = N'縺怜ｰｿ蜃ｦ逅・°謳ｬ讌ｭ', GYOUSHU_NAME_RYAKU = N'縺怜ｰｿ蜃ｦ逅・°謳ｬ讌ｭ', GYOUSHU_FURIGANA = N'シニョウショリウンパンギョウ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GYOUSHU)
UPDATE T SET GYOUSHU_NAME = N'荳闊ｬ蟒・｣・黄蜃ｦ逅・･ｭ', GYOUSHU_NAME_RYAKU = N'荳闊ｬ蟒・｣・黄蜃ｦ逅・･ｭ', GYOUSHU_FURIGANA = N'イッパンハイキブツショリギョウ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GYOUSHU)
UPDATE T SET GYOUSHU_NAME = N'縺怜ｰｿ蜃ｦ逅・･ｭ', GYOUSHU_NAME_RYAKU = N'縺怜ｰｿ蜃ｦ逅・･ｭ', GYOUSHU_FURIGANA = N'シニョウショリギョウ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GYOUSHU)
UPDATE T SET GYOUSHU_NAME = N'縺斐∩蜃ｦ逅・°謳ｬ讌ｭ', GYOUSHU_NAME_RYAKU = N'縺斐∩蜃ｦ逅・°謳ｬ讌ｭ', GYOUSHU_FURIGANA = N'ゴミショリウンパンギョウ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GYOUSHU)
UPDATE T SET GYOUSHU_NAME = N'縺斐∩蜃ｦ蛻・･ｭ', GYOUSHU_NAME_RYAKU = N'縺斐∩蜃ｦ蛻・･ｭ', GYOUSHU_FURIGANA = N'ゴミショブンギョウ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GYOUSHU)
UPDATE T SET GYOUSHU_NAME = N'縺昴・莉悶・蟒・｣・黄蜃ｦ蛻・･ｭ', GYOUSHU_NAME_RYAKU = N'縺昴・莉悶・蟒・｣・黄蜃ｦ蛻・･ｭ', GYOUSHU_FURIGANA = N'ソノタノハイキブツショブンギョウ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_GYOUSHU)
UPDATE T SET GYOUSHU_NAME = N'LYNA迴ｾ蝣ｴ', GYOUSHU_NAME_RYAKU = N'LYNA迴ｾ蝣ｴ', GYOUSHU_FURIGANA = N'ＬＹＮＡゲンバ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 12;

