-- UPDATE script for table M_HAIKI_NAME (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 23

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000001', HAIKI_NAME = N'廃プラA', HAIKI_NAME_RYAKU = N'廃プラA', HAIKI_NAME_FURIGANA = N'エンビハイプラＡ', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000002', HAIKI_NAME = N'廃プラB', HAIKI_NAME_RYAKU = N'廃プラB', HAIKI_NAME_FURIGANA = N'ハイプラＢ', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000003', HAIKI_NAME = N'非塩素系', HAIKI_NAME_RYAKU = N'非塩素系', HAIKI_NAME_FURIGANA = N'ヒエンソケイ', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'安田　彬' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000004', HAIKI_NAME = N'発砲', HAIKI_NAME_RYAKU = N'発砲', HAIKI_NAME_FURIGANA = N'ハッポウ', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000005', HAIKI_NAME = N'石膏ボード', HAIKI_NAME_RYAKU = N'石膏ボード', HAIKI_NAME_FURIGANA = N'セッコウボード', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000006', HAIKI_NAME = N'軟質プラ', HAIKI_NAME_RYAKU = N'軟質プラ', HAIKI_NAME_FURIGANA = N'エンビナンシツプラ', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000007', HAIKI_NAME = N'気泡系', HAIKI_NAME_RYAKU = N'気泡系', HAIKI_NAME_FURIGANA = N'キホウケイ', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'安田　彬' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000008', HAIKI_NAME = N'段ボール', HAIKI_NAME_RYAKU = N'段ボール', HAIKI_NAME_FURIGANA = N'ダンボール', HAIKI_NAME_BIKOU = N'テスト', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000010', HAIKI_NAME = N'廃プラ（橋本用）', HAIKI_NAME_RYAKU = N'廃プラ（橋本用）', HAIKI_NAME_FURIGANA = N'ハアイプラハイプラハシモトモトヨウ', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000011', HAIKI_NAME = N'廃プラ（長縄用）', HAIKI_NAME_RYAKU = N'廃プラ（長縄用）', HAIKI_NAME_FURIGANA = N'ハイプラナガナワヨウヨウ', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000012', HAIKI_NAME = N'感染性', HAIKI_NAME_RYAKU = N'感染性', HAIKI_NAME_FURIGANA = N'カンセンセイ', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000013', HAIKI_NAME = N'廃油', HAIKI_NAME_RYAKU = N'廃油', HAIKI_NAME_FURIGANA = N'ハイユ', HAIKI_NAME_BIKOU = N'テスト', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000100', HAIKI_NAME = N'混合廃棄物', HAIKI_NAME_RYAKU = N'混合廃棄物', HAIKI_NAME_FURIGANA = N'コンゴウハイキブツ', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000101', HAIKI_NAME = N'混合Ａ', HAIKI_NAME_RYAKU = N'混合Ａ', HAIKI_NAME_FURIGANA = N'コンゴウＡ', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000102', HAIKI_NAME = N'混合Ｂ', HAIKI_NAME_RYAKU = N'混合Ｂ', HAIKI_NAME_FURIGANA = N'コンゴウＢ', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000400', HAIKI_NAME = N'ガラス・陶磁器くず類', HAIKI_NAME_RYAKU = N'ガラス・陶磁器くず類', HAIKI_NAME_FURIGANA = N'ガラス・トウジキクズルイ', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'000800', HAIKI_NAME = N'鉄くず', HAIKI_NAME_RYAKU = N'鉄くず', HAIKI_NAME_FURIGANA = N'テツクズ', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'001100', HAIKI_NAME = N'汚泥', HAIKI_NAME_RYAKU = N'汚泥', HAIKI_NAME_FURIGANA = N'オデイ', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'001200', HAIKI_NAME = N'紙くず類', HAIKI_NAME_RYAKU = N'紙くず類', HAIKI_NAME_FURIGANA = N'カミルイクズルイ', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'001300', HAIKI_NAME = N'木くず類', HAIKI_NAME_RYAKU = N'木くず類', HAIKI_NAME_FURIGANA = N'キクズルイ', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'007550', HAIKI_NAME = N'住宅建材', HAIKI_NAME_RYAKU = N'住宅建材', HAIKI_NAME_FURIGANA = N'ジュウタクケンザイ', HAIKI_NAME_BIKOU = N'テスト', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'800000', HAIKI_NAME = N'ベットマット', HAIKI_NAME_RYAKU = N'ベットマット', HAIKI_NAME_FURIGANA = N'ベットベットマット', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_NAME)
UPDATE T SET HAIKI_NAME_CD = N'900000', HAIKI_NAME = N'ソファー', HAIKI_NAME_RYAKU = N'ソファー', HAIKI_NAME_FURIGANA = N'ベットソファー', HAIKI_NAME_BIKOU = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 23;

