-- UPDATE script for table M_HAIKI_SHURUI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 116

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'燃えがら', HAIKI_SHURUI_NAME_RYAKU = N'燃えがら', HAIKI_SHURUI_FURIGANA = N'モエガラ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'汚泥', HAIKI_SHURUI_NAME_RYAKU = N'汚泥', HAIKI_SHURUI_FURIGANA = N'オデイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃油', HAIKI_SHURUI_NAME_RYAKU = N'廃油', HAIKI_SHURUI_FURIGANA = N'ハイユ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃酸', HAIKI_SHURUI_NAME_RYAKU = N'廃酸', HAIKI_SHURUI_FURIGANA = N'ハイサン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃アルカリ', HAIKI_SHURUI_NAME_RYAKU = N'廃アルカリ', HAIKI_SHURUI_FURIGANA = N'ハイアルカリ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃プラスチック類', HAIKI_SHURUI_NAME_RYAKU = N'廃プラスチック類', HAIKI_SHURUI_FURIGANA = N'ハイプラスチックルイ', CREATE_USER = N'edison', UPDATE_USER = N'新川　拓哉' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃プラ（混合）', HAIKI_SHURUI_NAME_RYAKU = N'廃プラ（混合）', HAIKI_SHURUI_FURIGANA = N'ハイプラコンゴウ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'紙くず', HAIKI_SHURUI_NAME_RYAKU = N'紙くず', HAIKI_SHURUI_FURIGANA = N'カミクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'木くず', HAIKI_SHURUI_NAME_RYAKU = N'木くず', HAIKI_SHURUI_FURIGANA = N'キクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'繊維くず', HAIKI_SHURUI_NAME_RYAKU = N'繊維くず', HAIKI_SHURUI_FURIGANA = N'センイクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'動植物性残さ', HAIKI_SHURUI_NAME_RYAKU = N'動植物性残さ', HAIKI_SHURUI_FURIGANA = N'ドウショクブツセイザンサ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ゴムくず', HAIKI_SHURUI_NAME_RYAKU = N'ゴムくず', HAIKI_SHURUI_FURIGANA = N'ゴムクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'金属くず', HAIKI_SHURUI_NAME_RYAKU = N'金属くず', HAIKI_SHURUI_FURIGANA = N'キンゾククズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ｶﾞﾗｽくず･ｺﾝｸﾘｰﾄくず及び陶磁器くず', HAIKI_SHURUI_NAME_RYAKU = N'ｶﾞﾗｽ･ｺﾝｸﾘ･陶磁器くず', HAIKI_SHURUI_FURIGANA = N'ガラス・トウジキクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'鉱さい', HAIKI_SHURUI_NAME_RYAKU = N'鉱さい', HAIKI_SHURUI_FURIGANA = N'コウサイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'がれき類', HAIKI_SHURUI_NAME_RYAKU = N'がれき類', HAIKI_SHURUI_FURIGANA = N'ガレキルイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'家畜ふん尿', HAIKI_SHURUI_NAME_RYAKU = N'家畜ふん尿', HAIKI_SHURUI_FURIGANA = N'カチクフンニョウ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'家畜の死体', HAIKI_SHURUI_NAME_RYAKU = N'家畜の死体', HAIKI_SHURUI_FURIGANA = N'カチクノシタイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'石綿含有産業廃棄物', HAIKI_SHURUI_NAME_RYAKU = N'石綿含有産業廃棄物', HAIKI_SHURUI_FURIGANA = N'セキメンガンユウサンギョウハイキブツ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ばいじん', HAIKI_SHURUI_NAME_RYAKU = N'ばいじん', HAIKI_SHURUI_FURIGANA = N'バイジン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'１３号廃棄物', HAIKI_SHURUI_NAME_RYAKU = N'１３号廃棄物', HAIKI_SHURUI_FURIGANA = N'１３ゴウハイキブツ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'動物系固形不要物', HAIKI_SHURUI_NAME_RYAKU = N'動物系固形不要物', HAIKI_SHURUI_FURIGANA = N'ドウブツケイコケイフヨウブツ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'木屑（アスベスト含む）', HAIKI_SHURUI_NAME_RYAKU = N'木屑（アスベスト含む', HAIKI_SHURUI_FURIGANA = N'キクズ（アスベストフクム）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ガラスくず及び陶磁器くず（石綿含有）', HAIKI_SHURUI_NAME_RYAKU = N'ガラスくず及び陶磁器', HAIKI_SHURUI_FURIGANA = N'ガラス', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'紙くず（アスベスト含む）', HAIKI_SHURUI_NAME_RYAKU = N'紙くず（アスベスト含', HAIKI_SHURUI_FURIGANA = N'カミクズ（アスベストフクム）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'繊維くず（アスベスト含む）', HAIKI_SHURUI_NAME_RYAKU = N'繊維くず（アスベスト', HAIKI_SHURUI_FURIGANA = N'センイクズ（アスベストフクム）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'がれき類（アスベスト含む）', HAIKI_SHURUI_NAME_RYAKU = N'がれき類（アスベスト', HAIKI_SHURUI_FURIGANA = N'ガレキルイ（アスベストフクム）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'テスト浅沼', HAIKI_SHURUI_NAME_RYAKU = N'テスト浅沼', HAIKI_SHURUI_FURIGANA = N'テストアサヌマ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'引火性廃油', HAIKI_SHURUI_NAME_RYAKU = N'引火性廃油', HAIKI_SHURUI_FURIGANA = N'インカセイハイユ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'引火性廃油（有害）', HAIKI_SHURUI_NAME_RYAKU = N'引火性廃油（有害）', HAIKI_SHURUI_FURIGANA = N'インカセイハイユ（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'強酸', HAIKI_SHURUI_NAME_RYAKU = N'強酸', HAIKI_SHURUI_FURIGANA = N'キョウサン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'強酸（有害）', HAIKI_SHURUI_NAME_RYAKU = N'強酸（有害）', HAIKI_SHURUI_FURIGANA = N'キョウサン（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'強アルカリ', HAIKI_SHURUI_NAME_RYAKU = N'強アルカリ', HAIKI_SHURUI_FURIGANA = N'キョウアルカリ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'強アルカリ（有害）', HAIKI_SHURUI_NAME_RYAKU = N'強アルカリ（有害）', HAIKI_SHURUI_FURIGANA = N'キョウアルカリ（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'感染性廃棄物', HAIKI_SHURUI_NAME_RYAKU = N'感染性廃棄物', HAIKI_SHURUI_FURIGANA = N'カンセンセイハイキブツ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ＰＣＢ等', HAIKI_SHURUI_NAME_RYAKU = N'ＰＣＢ等', HAIKI_SHURUI_FURIGANA = N'ＰＣＢトウ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃石綿等', HAIKI_SHURUI_NAME_RYAKU = N'廃石綿等', HAIKI_SHURUI_FURIGANA = N'ハイセキメントウ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'指定下水汚泥', HAIKI_SHURUI_NAME_RYAKU = N'指定下水汚泥', HAIKI_SHURUI_FURIGANA = N'シテイゲスイオデイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'鉱さい（有害）', HAIKI_SHURUI_NAME_RYAKU = N'鉱さい（有害）', HAIKI_SHURUI_FURIGANA = N'コウサイ（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'燃えがら（有害）', HAIKI_SHURUI_NAME_RYAKU = N'燃えがら（有害）', HAIKI_SHURUI_FURIGANA = N'モエガラ（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃油（有害）', HAIKI_SHURUI_NAME_RYAKU = N'廃油（有害）', HAIKI_SHURUI_FURIGANA = N'ハイユ（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'汚泥（有害）', HAIKI_SHURUI_NAME_RYAKU = N'汚泥（有害）', HAIKI_SHURUI_FURIGANA = N'オデイ（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃酸（有害）', HAIKI_SHURUI_NAME_RYAKU = N'廃酸（有害）', HAIKI_SHURUI_FURIGANA = N'ハイサン（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃アルカリ（有害）', HAIKI_SHURUI_NAME_RYAKU = N'廃アルカリ（有害）', HAIKI_SHURUI_FURIGANA = N'ハイアルカリ（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ばいじん（有害）', HAIKI_SHURUI_NAME_RYAKU = N'ばいじん（有害）', HAIKI_SHURUI_FURIGANA = N'バイジン（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'１３号廃棄物（有害）', HAIKI_SHURUI_NAME_RYAKU = N'１３号廃棄物（有害）', HAIKI_SHURUI_FURIGANA = N'１３ゴウハイキブツ（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃水銀等', HAIKI_SHURUI_NAME_RYAKU = N'廃水銀等', HAIKI_SHURUI_FURIGANA = N'ハイスイギントウ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'建材廃棄物', HAIKI_SHURUI_NAME_RYAKU = N'建材廃棄物', HAIKI_SHURUI_FURIGANA = N'ケンザイハイキブツ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'混合', HAIKI_SHURUI_NAME_RYAKU = N'混合', HAIKI_SHURUI_FURIGANA = N'コンゴウ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'コンクリートがら', HAIKI_SHURUI_NAME_RYAKU = N'コンクリートがら', HAIKI_SHURUI_FURIGANA = N'コンクリートガラ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'アスコンがら', HAIKI_SHURUI_NAME_RYAKU = N'アスコンがら', HAIKI_SHURUI_FURIGANA = N'アスコンガラ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'その他がれき類', HAIKI_SHURUI_NAME_RYAKU = N'その他がれき類', HAIKI_SHURUI_FURIGANA = N'ソノタガレキルイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ガラス・陶磁器くず', HAIKI_SHURUI_NAME_RYAKU = N'ガラス・陶磁器くず', HAIKI_SHURUI_FURIGANA = N'ガラス・トウジキクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃プラスチック類', HAIKI_SHURUI_NAME_RYAKU = N'廃プラスチック類', HAIKI_SHURUI_FURIGANA = N'ハイプラスチックルイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'金属くず', HAIKI_SHURUI_NAME_RYAKU = N'金属くず', HAIKI_SHURUI_FURIGANA = N'キンゾククズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'混合（安定型のみ）', HAIKI_SHURUI_NAME_RYAKU = N'混合（安定型のみ）', HAIKI_SHURUI_FURIGANA = N'コンゴウ（アンテイガタノミ）', CREATE_USER = N'edison', UPDATE_USER = N'鈴木　次郎' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'石綿含有産業廃棄物', HAIKI_SHURUI_NAME_RYAKU = N'石綿含有産業廃棄物', HAIKI_SHURUI_FURIGANA = N'セキメンガンユウサンギョウハイキブツ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'あいうえお', HAIKI_SHURUI_NAME_RYAKU = N'あいうえお', HAIKI_SHURUI_FURIGANA = N'アイウエオ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'建設汚泥', HAIKI_SHURUI_NAME_RYAKU = N'建設汚泥', HAIKI_SHURUI_FURIGANA = N'ケンセツオデイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'紙くず', HAIKI_SHURUI_NAME_RYAKU = N'紙くず', HAIKI_SHURUI_FURIGANA = N'カミクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'木くず', HAIKI_SHURUI_NAME_RYAKU = N'木くず', HAIKI_SHURUI_FURIGANA = N'キクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'繊維くず', HAIKI_SHURUI_NAME_RYAKU = N'繊維くず', HAIKI_SHURUI_FURIGANA = N'センイクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 62;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃石膏ボード', HAIKI_SHURUI_NAME_RYAKU = N'廃石膏ボード', HAIKI_SHURUI_FURIGANA = N'ハイセッコウボード', CREATE_USER = N'edison', UPDATE_USER = N'新川　拓哉' WHERE rn = 63;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'混合（管理型含む）', HAIKI_SHURUI_NAME_RYAKU = N'混合（管理型含む）', HAIKI_SHURUI_FURIGANA = N'コンゴウカンリガタフクム', CREATE_USER = N'edison', UPDATE_USER = N'鈴木　次郎' WHERE rn = 64;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'石綿含有産業廃棄物', HAIKI_SHURUI_NAME_RYAKU = N'石綿含有産業廃棄物', HAIKI_SHURUI_FURIGANA = N'セキメンガンユウサンギョウハイキブツ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 65;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'水銀使用製品産業廃棄物', HAIKI_SHURUI_NAME_RYAKU = N'水銀使用製品産業廃棄', HAIKI_SHURUI_FURIGANA = N'スイギンシヨウセイヒンサンギョウハイキブ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 66;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃石綿等', HAIKI_SHURUI_NAME_RYAKU = N'廃石綿等', HAIKI_SHURUI_FURIGANA = N'ハイセキメントウ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 67;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'その他', HAIKI_SHURUI_NAME_RYAKU = N'その他', HAIKI_SHURUI_FURIGANA = N'ソノタ', CREATE_USER = N'edison', UPDATE_USER = N'鈴木　次郎' WHERE rn = 68;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃水銀等', HAIKI_SHURUI_NAME_RYAKU = N'廃水銀等', HAIKI_SHURUI_FURIGANA = N'ハイスイギントウ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 69;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'汚泥', HAIKI_SHURUI_NAME_RYAKU = N'汚泥', HAIKI_SHURUI_FURIGANA = N'オデイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 70;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'燃えがら', HAIKI_SHURUI_NAME_RYAKU = N'燃えがら', HAIKI_SHURUI_FURIGANA = N'モエガラ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 71;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'汚泥', HAIKI_SHURUI_NAME_RYAKU = N'汚泥', HAIKI_SHURUI_FURIGANA = N'オデイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 72;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃油', HAIKI_SHURUI_NAME_RYAKU = N'廃油', HAIKI_SHURUI_FURIGANA = N'ハイユ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 73;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃酸', HAIKI_SHURUI_NAME_RYAKU = N'廃酸', HAIKI_SHURUI_FURIGANA = N'ハイサン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 74;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃アルカリ', HAIKI_SHURUI_NAME_RYAKU = N'廃アルカリ', HAIKI_SHURUI_FURIGANA = N'ハイアルカリ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 75;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃プラスチック類', HAIKI_SHURUI_NAME_RYAKU = N'廃プラスチック類', HAIKI_SHURUI_FURIGANA = N'ハイプラスチックルイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 76;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'紙くず', HAIKI_SHURUI_NAME_RYAKU = N'紙くず', HAIKI_SHURUI_FURIGANA = N'カミクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 77;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'木くず', HAIKI_SHURUI_NAME_RYAKU = N'木くず', HAIKI_SHURUI_FURIGANA = N'キクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 78;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'繊維くず', HAIKI_SHURUI_NAME_RYAKU = N'繊維くず', HAIKI_SHURUI_FURIGANA = N'センイクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 79;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'動植物性残さ', HAIKI_SHURUI_NAME_RYAKU = N'動植物性残さ', HAIKI_SHURUI_FURIGANA = N'ドウショクブツセイザンサ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 80;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ゴムくず', HAIKI_SHURUI_NAME_RYAKU = N'ゴムくず', HAIKI_SHURUI_FURIGANA = N'ゴムクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 81;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'金属くず', HAIKI_SHURUI_NAME_RYAKU = N'金属くず', HAIKI_SHURUI_FURIGANA = N'キンゾククズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 82;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ガラス・陶磁器くず', HAIKI_SHURUI_NAME_RYAKU = N'ガラス・陶磁器くず', HAIKI_SHURUI_FURIGANA = N'ガラス・トウジキクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 83;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'鉱さい', HAIKI_SHURUI_NAME_RYAKU = N'鉱さい', HAIKI_SHURUI_FURIGANA = N'コウサイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 84;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'がれき類', HAIKI_SHURUI_NAME_RYAKU = N'がれき類', HAIKI_SHURUI_FURIGANA = N'ガレキルイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 85;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'家畜ふん尿', HAIKI_SHURUI_NAME_RYAKU = N'家畜ふん尿', HAIKI_SHURUI_FURIGANA = N'カチクフンニョウ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 86;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'家畜の死体', HAIKI_SHURUI_NAME_RYAKU = N'家畜の死体', HAIKI_SHURUI_FURIGANA = N'カチクノシタイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 87;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'石綿含有産業廃棄物', HAIKI_SHURUI_NAME_RYAKU = N'石綿含有産業廃棄物', HAIKI_SHURUI_FURIGANA = N'セキメンガンユウサンギョウハイキブツ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 88;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ばいじん', HAIKI_SHURUI_NAME_RYAKU = N'ばいじん', HAIKI_SHURUI_FURIGANA = N'バイジン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 89;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'１３号廃棄物', HAIKI_SHURUI_NAME_RYAKU = N'１３号廃棄物', HAIKI_SHURUI_FURIGANA = N'１３ゴウハイキブツ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 90;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'動物系固形不要物', HAIKI_SHURUI_NAME_RYAKU = N'動物系固形不要物', HAIKI_SHURUI_FURIGANA = N'ドウブツケイコケイフヨウブツ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 91;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'木屑（アスベスト含む）', HAIKI_SHURUI_NAME_RYAKU = N'木屑（アスベスト含む', HAIKI_SHURUI_FURIGANA = N'キクズ（アスベストフクム）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 92;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ガラスくず及び陶磁器くず（石綿含有）', HAIKI_SHURUI_NAME_RYAKU = N'ガラスくず及び陶磁器', HAIKI_SHURUI_FURIGANA = N'ガラス', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 93;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'紙くず（アスベスト含む）', HAIKI_SHURUI_NAME_RYAKU = N'紙くず（アスベスト含', HAIKI_SHURUI_FURIGANA = N'カミクズ（アスベストフクム）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 94;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'繊維くず（アスベスト含む）', HAIKI_SHURUI_NAME_RYAKU = N'繊維くず（アスベスト', HAIKI_SHURUI_FURIGANA = N'センイクズ（アスベストフクム）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 95;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'がれき類（アスベスト含む）', HAIKI_SHURUI_NAME_RYAKU = N'がれき類（アスベスト', HAIKI_SHURUI_FURIGANA = N'ガレキルイ（アスベストフクム）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 96;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'引火性廃油', HAIKI_SHURUI_NAME_RYAKU = N'引火性廃油', HAIKI_SHURUI_FURIGANA = N'インカセイハイユ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 97;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'引火性廃油（有害）', HAIKI_SHURUI_NAME_RYAKU = N'引火性廃油（有害）', HAIKI_SHURUI_FURIGANA = N'インカセイハイユ（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 98;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'強酸', HAIKI_SHURUI_NAME_RYAKU = N'強酸', HAIKI_SHURUI_FURIGANA = N'キョウサン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 99;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'強酸（有害）', HAIKI_SHURUI_NAME_RYAKU = N'強酸（有害）', HAIKI_SHURUI_FURIGANA = N'キョウサン（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 100;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'強アルカリ', HAIKI_SHURUI_NAME_RYAKU = N'強アルカリ', HAIKI_SHURUI_FURIGANA = N'キョウアルカリ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 101;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'強アルカリ（有害）', HAIKI_SHURUI_NAME_RYAKU = N'強アルカリ（有害）', HAIKI_SHURUI_FURIGANA = N'キョウアルカリ（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 102;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'感染性廃棄物', HAIKI_SHURUI_NAME_RYAKU = N'感染性廃棄物', HAIKI_SHURUI_FURIGANA = N'カンセンセイハイキブツ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 103;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ＰＣＢ等', HAIKI_SHURUI_NAME_RYAKU = N'ＰＣＢ等', HAIKI_SHURUI_FURIGANA = N'ＰＣＢトウ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 104;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃石綿等', HAIKI_SHURUI_NAME_RYAKU = N'廃石綿等', HAIKI_SHURUI_FURIGANA = N'ハイセキメントウ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 105;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'指定下水汚泥', HAIKI_SHURUI_NAME_RYAKU = N'指定下水汚泥', HAIKI_SHURUI_FURIGANA = N'シテイゲスイオデイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 106;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'鉱さい（有害）', HAIKI_SHURUI_NAME_RYAKU = N'鉱さい（有害）', HAIKI_SHURUI_FURIGANA = N'コウサイ（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 107;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'燃えがら（有害）', HAIKI_SHURUI_NAME_RYAKU = N'燃えがら（有害）', HAIKI_SHURUI_FURIGANA = N'モエガラ（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 108;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃油（有害）', HAIKI_SHURUI_NAME_RYAKU = N'廃油（有害）', HAIKI_SHURUI_FURIGANA = N'ハイユ（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 109;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'汚泥（有害）', HAIKI_SHURUI_NAME_RYAKU = N'汚泥（有害）', HAIKI_SHURUI_FURIGANA = N'オデイ（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 110;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃酸（有害）', HAIKI_SHURUI_NAME_RYAKU = N'廃酸（有害）', HAIKI_SHURUI_FURIGANA = N'ハイサン（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 111;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃アルカリ（有害）', HAIKI_SHURUI_NAME_RYAKU = N'廃アルカリ（有害）', HAIKI_SHURUI_FURIGANA = N'ハイアルカリ（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 112;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'ばいじん（有害）', HAIKI_SHURUI_NAME_RYAKU = N'ばいじん（有害）', HAIKI_SHURUI_FURIGANA = N'バイジン（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 113;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'１３号廃棄物（有害）', HAIKI_SHURUI_NAME_RYAKU = N'１３号廃棄物（有害）', HAIKI_SHURUI_FURIGANA = N'１３ゴウハイキブツ（ユウガイ）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 114;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'廃水銀等', HAIKI_SHURUI_NAME_RYAKU = N'廃水銀等', HAIKI_SHURUI_FURIGANA = N'ハイスイギントウ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 115;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_SHURUI)
UPDATE T SET HAIKI_SHURUI_NAME = N'混合', HAIKI_SHURUI_NAME_RYAKU = N'混合', HAIKI_SHURUI_FURIGANA = N'コンゴウ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 116;

