-- UPDATE script for table M_HAIKI_KBN (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 4

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_KBN)
UPDATE T SET HAIKI_KBN_NAME = N'産廃', HAIKI_KBN_NAME_RYAKU = N'産廃', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_KBN)
UPDATE T SET HAIKI_KBN_NAME = N'建廃', HAIKI_KBN_NAME_RYAKU = N'建廃', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_KBN)
UPDATE T SET HAIKI_KBN_NAME = N'積替', HAIKI_KBN_NAME_RYAKU = N'積替', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HAIKI_KBN)
UPDATE T SET HAIKI_KBN_NAME = N'電子', HAIKI_KBN_NAME_RYAKU = N'電子', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 4;

