-- UPDATE script for table M_HIKIAI_TORIHIKISAKI_SHIHARAI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 24

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = N'', FURIKOMI_SAKI_BANK_SHITEN_NAME = N'', FURIKOMI_SAKI_BANK_KOUZA_NAME = N'', FURI_KOMI_MOTO_NAME = N'' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = NULL, FURIKOMI_SAKI_BANK_SHITEN_NAME = NULL, FURIKOMI_SAKI_BANK_KOUZA_NAME = NULL, FURI_KOMI_MOTO_NAME = NULL WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = NULL, FURIKOMI_SAKI_BANK_SHITEN_NAME = NULL, FURIKOMI_SAKI_BANK_KOUZA_NAME = NULL, FURI_KOMI_MOTO_NAME = NULL WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = NULL, FURIKOMI_SAKI_BANK_SHITEN_NAME = NULL, FURIKOMI_SAKI_BANK_KOUZA_NAME = NULL, FURI_KOMI_MOTO_NAME = NULL WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = NULL, FURIKOMI_SAKI_BANK_SHITEN_NAME = NULL, FURIKOMI_SAKI_BANK_KOUZA_NAME = NULL, FURI_KOMI_MOTO_NAME = NULL WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = NULL, FURIKOMI_SAKI_BANK_SHITEN_NAME = NULL, FURIKOMI_SAKI_BANK_KOUZA_NAME = NULL, FURI_KOMI_MOTO_NAME = NULL WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = NULL, FURIKOMI_SAKI_BANK_SHITEN_NAME = NULL, FURIKOMI_SAKI_BANK_KOUZA_NAME = NULL, FURI_KOMI_MOTO_NAME = NULL WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = NULL, FURIKOMI_SAKI_BANK_SHITEN_NAME = NULL, FURIKOMI_SAKI_BANK_KOUZA_NAME = NULL, FURI_KOMI_MOTO_NAME = NULL WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = NULL, FURIKOMI_SAKI_BANK_SHITEN_NAME = NULL, FURIKOMI_SAKI_BANK_KOUZA_NAME = NULL, FURI_KOMI_MOTO_NAME = NULL WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = N'', FURIKOMI_SAKI_BANK_SHITEN_NAME = N'', FURIKOMI_SAKI_BANK_KOUZA_NAME = N'', FURI_KOMI_MOTO_NAME = N'' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = N'', FURIKOMI_SAKI_BANK_SHITEN_NAME = N'', FURIKOMI_SAKI_BANK_KOUZA_NAME = N'', FURI_KOMI_MOTO_NAME = N'' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = N'', FURIKOMI_SAKI_BANK_SHITEN_NAME = N'', FURIKOMI_SAKI_BANK_KOUZA_NAME = N'', FURI_KOMI_MOTO_NAME = N'' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = N'', FURIKOMI_SAKI_BANK_SHITEN_NAME = N'', FURIKOMI_SAKI_BANK_KOUZA_NAME = N'', FURI_KOMI_MOTO_NAME = N'' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = N'', FURIKOMI_SAKI_BANK_SHITEN_NAME = N'', FURIKOMI_SAKI_BANK_KOUZA_NAME = N'', FURI_KOMI_MOTO_NAME = N'' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = N'', FURIKOMI_SAKI_BANK_SHITEN_NAME = N'', FURIKOMI_SAKI_BANK_KOUZA_NAME = N'', FURI_KOMI_MOTO_NAME = N'' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = N'', FURIKOMI_SAKI_BANK_SHITEN_NAME = N'', FURIKOMI_SAKI_BANK_KOUZA_NAME = N'', FURI_KOMI_MOTO_NAME = N'' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = N'', FURIKOMI_SAKI_BANK_SHITEN_NAME = N'', FURIKOMI_SAKI_BANK_KOUZA_NAME = N'', FURI_KOMI_MOTO_NAME = N'' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = N'', FURIKOMI_SAKI_BANK_SHITEN_NAME = N'', FURIKOMI_SAKI_BANK_KOUZA_NAME = N'', FURI_KOMI_MOTO_NAME = N'' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = NULL, FURIKOMI_SAKI_BANK_SHITEN_NAME = NULL, FURIKOMI_SAKI_BANK_KOUZA_NAME = NULL, FURI_KOMI_MOTO_NAME = NULL WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = N'', FURIKOMI_SAKI_BANK_SHITEN_NAME = N'', FURIKOMI_SAKI_BANK_KOUZA_NAME = N'', FURI_KOMI_MOTO_NAME = N'' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = N'', FURIKOMI_SAKI_BANK_SHITEN_NAME = N'', FURIKOMI_SAKI_BANK_KOUZA_NAME = N'', FURI_KOMI_MOTO_NAME = N'' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = N'', FURIKOMI_SAKI_BANK_SHITEN_NAME = N'', FURIKOMI_SAKI_BANK_KOUZA_NAME = N'', FURI_KOMI_MOTO_NAME = N'' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = N'', FURIKOMI_SAKI_BANK_SHITEN_NAME = N'', FURIKOMI_SAKI_BANK_KOUZA_NAME = N'', FURI_KOMI_MOTO_NAME = N'' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SHIHARAI)
UPDATE T SET SHIHARAI_SOUFU_NAME1 = N'', SHIHARAI_SOUFU_NAME2 = N'', SHIHARAI_SOUFU_POST = N'', SHIHARAI_SOUFU_ADDRESS1 = N'', SHIHARAI_SOUFU_ADDRESS2 = N'', SHIHARAI_SOUFU_TANTOU = N'', SHIHARAI_SOUFU_TEL = N'', SHIHARAI_SOUFU_FAX = N'', FURIKOMI_SAKI_BANK_NAME = N'', FURIKOMI_SAKI_BANK_SHITEN_NAME = N'', FURIKOMI_SAKI_BANK_KOUZA_NAME = N'', FURI_KOMI_MOTO_NAME = N'' WHERE rn = 24;

