-- UPDATE script for table M_HIKIAI_TORIHIKISAKI_SEIKYUU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 24

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ繧ｫ繝悶す繧ｭ繧ｬ繧､繧ｷ繝｣', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'', KOUZA_NAME_3 = N'' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ繧ｫ繝悶す繧ｭ繧ｬ繧､繧ｷ繝｣', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = NULL, KOUZA_NAME_3 = NULL WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ繧ｫ繝悶す繧ｭ繧ｬ繧､繧ｷ繝｣', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = NULL, KOUZA_NAME_3 = NULL WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ繧ｫ繝悶す繧ｭ繧ｬ繧､繧ｷ繝｣', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = NULL, KOUZA_NAME_3 = NULL WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ繧ｫ繝悶す繧ｭ繧ｬ繧､繧ｷ繝｣', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = NULL, KOUZA_NAME_3 = NULL WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ繧ｫ繝悶す繧ｭ繧ｬ繧､繧ｷ繝｣', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = NULL, KOUZA_NAME_3 = NULL WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ繧ｫ繝悶す繧ｭ繧ｬ繧､繧ｷ繝｣', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'', KOUZA_NAME_3 = N'' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ繧ｫ繝悶す繧ｭ繧ｬ繧､繧ｷ繝｣', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'', KOUZA_NAME_3 = N'' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', KOUZA_NAME_3 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', KOUZA_NAME_3 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', KOUZA_NAME_3 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', KOUZA_NAME_3 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', KOUZA_NAME_3 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', KOUZA_NAME_3 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', KOUZA_NAME_3 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', KOUZA_NAME_3 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', KOUZA_NAME_3 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', KOUZA_NAME_3 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ繧ｫ繝悶す繧ｭ繧ｬ繧､繧ｷ繝｣', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'', KOUZA_NAME_3 = N'' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', KOUZA_NAME_3 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', KOUZA_NAME_3 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', KOUZA_NAME_3 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', KOUZA_NAME_3 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HIKIAI_TORIHIKISAKI_SEIKYUU)
UPDATE T SET KOUZA_NAME = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', SEIKYUU_SOUFU_NAME1 = N'', SEIKYUU_SOUFU_NAME2 = N'', SEIKYUU_SOUFU_POST = N'', SEIKYUU_SOUFU_ADDRESS1 = N'', SEIKYUU_SOUFU_ADDRESS2 = N'', SEIKYUU_SOUFU_TANTOU = N'', SEIKYUU_SOUFU_TEL = N'', SEIKYUU_SOUFU_FAX = N'', SEIKYUU_TANTOU = N'', FURIKOMI_NAME1 = N'', FURIKOMI_NAME2 = N'', KOUZA_NAME_2 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き', KOUZA_NAME_3 = N'繧ｨ繧ｸ繧ｽ繝ｳ繧ｷ繝ｧ繧ｦ繧ｸ・医き' WHERE rn = 24;

