-- UPDATE script for table M_HINMEI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 318

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', HINMEI_NAME_RYAKU = N'廃プラスチック類', HINMEI_FURIGANA = N'ハイプラスチックルイ', CREATE_USER = N'やまだ', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', HINMEI_NAME_RYAKU = N'廃プラ', HINMEI_FURIGANA = N'ハイプラスチックルイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'000001' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'クロス', HINMEI_NAME_RYAKU = N'クロス', HINMEI_FURIGANA = N'クロス', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', HINMEI_NAME_RYAKU = N'紙くず', HINMEI_FURIGANA = N'カミクズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ダンボール', HINMEI_NAME_RYAKU = N'ダンボール', HINMEI_FURIGANA = N'ダンボール', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', HINMEI_NAME_RYAKU = N'木くず', HINMEI_FURIGANA = N'キクズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'001300' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'生木', HINMEI_NAME_RYAKU = N'生木', HINMEI_FURIGANA = N'ナマキ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'001300' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'繊維くずA', HINMEI_NAME_RYAKU = N'繊維くず', HINMEI_FURIGANA = N'センイクズＡ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'畳', HINMEI_NAME_RYAKU = N'畳', HINMEI_FURIGANA = N'タタミ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'中西　大樹', HAIKI_NAME_CD = N'' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', HINMEI_NAME_RYAKU = N'金属くず', HINMEI_FURIGANA = N'キンゾククズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス陶磁器くず', HINMEI_NAME_RYAKU = N'ガラス陶磁器くず', HINMEI_FURIGANA = N'ガラストウジキクズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ＡＬＣ', HINMEI_NAME_RYAKU = N'ＡＬＣ', HINMEI_FURIGANA = N'エーエルシー', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃石膏ボード', HINMEI_NAME_RYAKU = N'廃石膏ボード', HINMEI_FURIGANA = N'ハイセッコウボード', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'中西　大樹', HAIKI_NAME_CD = N'' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'グラスウール', HINMEI_NAME_RYAKU = N'グラスウール', HINMEI_FURIGANA = N'グラスウール', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'000800' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら', HINMEI_NAME_RYAKU = N'コンクリートがら', HINMEI_FURIGANA = N'コンクリートガラ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'アスコンがら', HINMEI_NAME_RYAKU = N'アスコンがら', HINMEI_FURIGANA = N'アスコンガラ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'その他がれき類', HINMEI_NAME_RYAKU = N'その他がれき類', HINMEI_FURIGANA = N'ソノタガレキルイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'鉱さい', HINMEI_NAME_RYAKU = N'鉱さい', HINMEI_FURIGANA = N'コウサイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'汚泥', HINMEI_NAME_RYAKU = N'汚泥', HINMEI_FURIGANA = N'オデイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'001100' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'蛍光灯', HINMEI_NAME_RYAKU = N'蛍光灯', HINMEI_FURIGANA = N'ケイコウトウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'中西　大樹', HAIKI_NAME_CD = N'' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'混合廃棄物', HINMEI_NAME_RYAKU = N'混合廃棄物', HINMEI_FURIGANA = N'コンゴウハイキブツ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'000100' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'混合廃棄物A', HINMEI_NAME_RYAKU = N'混合廃棄物A', HINMEI_FURIGANA = N'コンゴウハイキブツＡ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'固化物汚泥', HINMEI_NAME_RYAKU = N'固化物汚泥', HINMEI_FURIGANA = N'コカブツコカブツオデイ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'軟弱汚泥', HINMEI_NAME_RYAKU = N'軟弱汚泥', HINMEI_FURIGANA = N'ナンジャクオデイ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃クーラント', HINMEI_NAME_RYAKU = N'廃クーラント', HINMEI_FURIGANA = N'ハイクーラント', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'燃えやすい廃油', HINMEI_NAME_RYAKU = N'燃えやすい廃油', HINMEI_FURIGANA = N'モエヤスイハイユ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一', HAIKI_NAME_CD = N'' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'焼却灰', HINMEI_NAME_RYAKU = N'焼却灰', HINMEI_FURIGANA = N'ショウキャクバイ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'木皮', HINMEI_NAME_RYAKU = N'木皮', HINMEI_FURIGANA = N'キカワ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'選定枝', HINMEI_NAME_RYAKU = N'選定枝', HINMEI_FURIGANA = N'センテイエダ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'解体材', HINMEI_NAME_RYAKU = N'解体材', HINMEI_FURIGANA = N'カイタイザイ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'未利用材', HINMEI_NAME_RYAKU = N'未利用材', HINMEI_FURIGANA = N'ミリヨウザイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'積込　金属くず　バラ積み　1m3', HINMEI_NAME_RYAKU = N'積込　金属くず　バラ', HINMEI_FURIGANA = N'ツミコミキンゾククズバラズミツミミ１ｍ３', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'デスクトップパソコン', HINMEI_NAME_RYAKU = N'デスクトップパソコン', HINMEI_FURIGANA = N'フリコミデスクトップパソコン', CREATE_USER = N'安田　彬', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'複合機', HINMEI_NAME_RYAKU = N'複合機', HINMEI_FURIGANA = N'フクゴウキ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'収集運搬費', HINMEI_NAME_RYAKU = N'収集運搬費', HINMEI_FURIGANA = N'シュウシュウウンパ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'2tダンプ　収集', HINMEI_NAME_RYAKU = N'2tダンプ　収集', HINMEI_FURIGANA = N'２ｔダンプシュウシュウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'中西　大樹', HAIKI_NAME_CD = N'' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'4tダンプ　収集', HINMEI_NAME_RYAKU = N'4tダンプ　収集', HINMEI_FURIGANA = N'４ｔダンプシュウシュウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'4tユニック　収集', HINMEI_NAME_RYAKU = N'4tユニック　収集', HINMEI_FURIGANA = N'４ｔユニックシュウシュウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'7tユニック　収集', HINMEI_NAME_RYAKU = N'7tユニック　収集', HINMEI_FURIGANA = N'７ｔユニックシュウシュウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'中西　大樹', HAIKI_NAME_CD = N'' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'4tコンテナ　収集', HINMEI_NAME_RYAKU = N'4tコンテナ　収集', HINMEI_FURIGANA = N'４ｔコンテナシュウシュウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'中西　大樹', HAIKI_NAME_CD = N'' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'10tコンテナ　収集', HINMEI_NAME_RYAKU = N'10tコンテナ　収集', HINMEI_FURIGANA = N'１０ｔコンテナシュウシュウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンテナ設置', HINMEI_NAME_RYAKU = N'コンテナ設置', HINMEI_FURIGANA = N'コンテナセッチ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'中西　大樹', HAIKI_NAME_CD = N'' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンテナ交換', HINMEI_NAME_RYAKU = N'コンテナ交換', HINMEI_FURIGANA = N'コンテナコウカン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'中西　大樹', HAIKI_NAME_CD = N'' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンテナ引上', HINMEI_NAME_RYAKU = N'コンテナ引上', HINMEI_FURIGANA = N'コンテナヒキアゲ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'トン袋', HINMEI_NAME_RYAKU = N'トン袋', HINMEI_FURIGANA = N'トンブクロ', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊', HAIKI_NAME_CD = N'' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙おむつ', HINMEI_NAME_RYAKU = N'紙おむつ', HINMEI_FURIGANA = N'カミオムツ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙おむつ（袋）', HINMEI_NAME_RYAKU = N'紙おむつ（袋）', HINMEI_FURIGANA = N'カミオムツフクロ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'家畜糞尿', HINMEI_NAME_RYAKU = N'家畜糞尿', HINMEI_FURIGANA = N'カチクフンニョウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'粗大ごみ(小型家電)', HINMEI_NAME_RYAKU = N'粗大ごみ(小型家電)', HINMEI_FURIGANA = N'ソダイゴミコガタカデン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'粗大ごみ(家具)', HINMEI_NAME_RYAKU = N'粗大ごみ(家具)', HINMEI_FURIGANA = N'ソダイゴミカグ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'　　', HINMEI_NAME_RYAKU = N'　　', HINMEI_FURIGANA = N'クウラン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'RC-30', HINMEI_NAME_RYAKU = N'RC-30', HINMEI_FURIGANA = N'ＲＣ－３０', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'RC-40', HINMEI_NAME_RYAKU = N'RC-40', HINMEI_FURIGANA = N'ＲＣ－４０', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'RC-砂', HINMEI_NAME_RYAKU = N'RC-砂', HINMEI_FURIGANA = N'ＲＣ－スナ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'RM-30', HINMEI_NAME_RYAKU = N'RM-30', HINMEI_FURIGANA = N'ＲＭ－３０', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'RM-40', HINMEI_NAME_RYAKU = N'RM-40', HINMEI_FURIGANA = N'ＲＭ－４０', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'中目砂', HINMEI_NAME_RYAKU = N'中目砂', HINMEI_FURIGANA = N'チュウメズナ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'改質土', HINMEI_NAME_RYAKU = N'改質土', HINMEI_FURIGANA = N'カイリョウド', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'改良土B', HINMEI_NAME_RYAKU = N'改良土B', HINMEI_FURIGANA = N'カイリョウドB', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'がれき類', HINMEI_NAME_RYAKU = N'がれき類', HINMEI_FURIGANA = N'ガレキルイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'アスファルトガラ', HINMEI_NAME_RYAKU = N'アスファルトガラ', HINMEI_FURIGANA = N'アスファルトガラ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'アスファルト大ガラ', HINMEI_NAME_RYAKU = N'アスファルト大ガラ', HINMEI_FURIGANA = N'アスファルトダイガラ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 62;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリート無筋ガラ', HINMEI_NAME_RYAKU = N'コンクリート無筋ガラ', HINMEI_FURIGANA = N'コンクリートムキンガラ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 63;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリート有筋ガラ', HINMEI_NAME_RYAKU = N'コンクリート有筋ガラ', HINMEI_FURIGANA = N'コンクリートユウキンガラ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 64;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリート大ガラ（無筋）', HINMEI_NAME_RYAKU = N'コンクリート大ガラ無', HINMEI_FURIGANA = N'コンクリートダイガラムキン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 65;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'その他混合廃材', HINMEI_NAME_RYAKU = N'その他混合廃材', HINMEI_FURIGANA = N'ソノタコンゴウハイザイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 66;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'PCパイル', HINMEI_NAME_RYAKU = N'PCパイル', HINMEI_FURIGANA = N'ＰＣパイル', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 67;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'残土', HINMEI_NAME_RYAKU = N'残土', HINMEI_FURIGANA = N'ザンド', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 68;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'汚泥', HINMEI_NAME_RYAKU = N'汚泥', HINMEI_FURIGANA = N'オデイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 69;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'汚水', HINMEI_NAME_RYAKU = N'汚水', HINMEI_FURIGANA = N'オスイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 70;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'フレコンバック代', HINMEI_NAME_RYAKU = N'フレコンバック代', HINMEI_FURIGANA = N'フレコンバックダイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 71;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'４tダンプ収集運搬費', HINMEI_NAME_RYAKU = N'４tダンプ収集運搬費', HINMEI_FURIGANA = N'４ｔダンプシュウシュウウンパンヒ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 72;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'７tダンプ収集運搬費', HINMEI_NAME_RYAKU = N'７tダンプ収集運搬費', HINMEI_FURIGANA = N'７ｔダンプシュウシュウウンパンヒ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 73;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンテナ設置費', HINMEI_NAME_RYAKU = N'コンテナ設置費', HINMEI_FURIGANA = N'コンテナセッチヒ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 74;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'山土', HINMEI_NAME_RYAKU = N'山土', HINMEI_FURIGANA = N'ヤマツチ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 75;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'魚あら', HINMEI_NAME_RYAKU = N'魚あら', HINMEI_FURIGANA = N'サカナアラ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 76;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'感染性廃棄物', HINMEI_NAME_RYAKU = N'感染性廃棄物', HINMEI_FURIGANA = N'カンセンセイハイキブツ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 77;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'注射針等', HINMEI_NAME_RYAKU = N'注射針等', HINMEI_FURIGANA = N'チュウシャバリトウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 78;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス類等', HINMEI_NAME_RYAKU = N'ガラス類等', HINMEI_FURIGANA = N'ガラスルイトウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 79;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'プラスチック類等', HINMEI_NAME_RYAKU = N'プラスチック類等', HINMEI_FURIGANA = N'プラスチックルイトウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 80;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガーゼ・脱脂綿類', HINMEI_NAME_RYAKU = N'ガーゼ・脱脂綿類', HINMEI_FURIGANA = N'ガーゼ・ダッシメンルイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 81;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'おしめ類', HINMEI_NAME_RYAKU = N'おしめ類', HINMEI_FURIGANA = N'オシメルイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 82;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'汚物類', HINMEI_NAME_RYAKU = N'汚物類', HINMEI_FURIGANA = N'オブツルイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 83;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃液類', HINMEI_NAME_RYAKU = N'廃液類', HINMEI_FURIGANA = N'ハイエキルイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 84;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃血液類', HINMEI_NAME_RYAKU = N'廃血液類', HINMEI_FURIGANA = N'ハイケツエキルイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 85;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', HINMEI_NAME_RYAKU = N'金属くず', HINMEI_FURIGANA = N'キンゾククズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 86;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ギプス・石膏類', HINMEI_NAME_RYAKU = N'ギプス・石膏類', HINMEI_FURIGANA = N'ギプス・セッコウルイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 87;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'汚泥', HINMEI_NAME_RYAKU = N'汚泥', HINMEI_FURIGANA = N'オデイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 88;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃油', HINMEI_NAME_RYAKU = N'廃油', HINMEI_FURIGANA = N'ハイユ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 89;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃酸', HINMEI_NAME_RYAKU = N'廃酸', HINMEI_FURIGANA = N'ハイサン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 90;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃アルカリ', HINMEI_NAME_RYAKU = N'廃アルカリ', HINMEI_FURIGANA = N'ハイアルカリ　', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 91;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', HINMEI_NAME_RYAKU = N'廃プラスチック類', HINMEI_FURIGANA = N'ハイプラスチックルイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 92;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', HINMEI_NAME_RYAKU = N'金属くず', HINMEI_FURIGANA = N'キンゾククズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 93;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラスくず', HINMEI_NAME_RYAKU = N'ガラスくず', HINMEI_FURIGANA = N'ガラスクズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 94;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'収集・運搬費', HINMEI_NAME_RYAKU = N'収集・運搬費', HINMEI_FURIGANA = N'シュウシュウ・ウンパンヒ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 95;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'マニフェスト代', HINMEI_NAME_RYAKU = N'マニフェスト代', HINMEI_FURIGANA = N'マニフェストダイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 96;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'薬品処理', HINMEI_NAME_RYAKU = N'薬品処理', HINMEI_FURIGANA = N'ヤクヒンショリ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 97;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'分析費', HINMEI_NAME_RYAKU = N'分析費', HINMEI_FURIGANA = N'ブンセキヒ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 98;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'20リットル容器　回収', HINMEI_NAME_RYAKU = N'20リットル容器　回収', HINMEI_FURIGANA = N'５２０リットルヨウキンヨウキカイシュウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 99;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'20リットル容器　設置', HINMEI_NAME_RYAKU = N'20リットル容器　設置', HINMEI_FURIGANA = N'セッチ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 100;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'感染性廃棄物(10L容器)', HINMEI_NAME_RYAKU = N'感染性廃棄物(10L容器', HINMEI_FURIGANA = N'カンセンセイハイキブツ（10', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 101;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'感染性廃棄物(20L容器)', HINMEI_NAME_RYAKU = N'感染性廃棄物(20L容器', HINMEI_FURIGANA = N'カンセンセイハイキブツ（20', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 102;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'感染性廃棄物(50L容器)', HINMEI_NAME_RYAKU = N'感染性廃棄物(50L容器', HINMEI_FURIGANA = N'カンセンセイハイキブツ（50', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 103;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'感染性廃棄物(オムツ㎏)', HINMEI_NAME_RYAKU = N'感染性廃棄物(オムツ', HINMEI_FURIGANA = N'カンセンセイハイキブツ（オムツ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 104;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃フィルム', HINMEI_NAME_RYAKU = N'廃フィルム', HINMEI_FURIGANA = N'ハイフィルム', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 105;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃マイクロフィルム', HINMEI_NAME_RYAKU = N'廃マイクロフィルム', HINMEI_FURIGANA = N'ハイマイクロフィルム', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 106;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ｴﾀﾉｰﾙ･ﾒﾀﾉｰﾙ混合廃液', HINMEI_NAME_RYAKU = N'ｴﾀﾉｰﾙ･ﾒﾀﾉｰﾙ混合廃液', HINMEI_FURIGANA = N'エタノールメタノールコンゴウハイエキ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 107;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ベリリウム廃液', HINMEI_NAME_RYAKU = N'ベリリウム廃液', HINMEI_FURIGANA = N'ベリリウムハイエキ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 108;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'バナジウム廃液', HINMEI_NAME_RYAKU = N'バナジウム廃液', HINMEI_FURIGANA = N'パナジウムハイエキ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 109;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃油B', HINMEI_NAME_RYAKU = N'廃油B', HINMEI_FURIGANA = N'ハイユＢ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 110;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃油C', HINMEI_NAME_RYAKU = N'廃油C', HINMEI_FURIGANA = N'ハイユＣ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 111;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'低濃度PCB', HINMEI_NAME_RYAKU = N'低濃度PCB', HINMEI_FURIGANA = N'テイノウドＰＣＢ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 112;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ＨＳ', HINMEI_NAME_RYAKU = N'ＨＳ', HINMEI_FURIGANA = N'ＨＳ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 113;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'Ｈ１', HINMEI_NAME_RYAKU = N'Ｈ１', HINMEI_FURIGANA = N'Ｈ１', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 114;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'Ｈ２', HINMEI_NAME_RYAKU = N'Ｈ２', HINMEI_FURIGANA = N'Ｈ２', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 115;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'Ｈ３', HINMEI_NAME_RYAKU = N'Ｈ３', HINMEI_FURIGANA = N'Ｈ３', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 116;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'銅線（1号）', HINMEI_NAME_RYAKU = N'銅線（1号）', HINMEI_FURIGANA = N'ドウセン１ゴウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 117;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'銅屑', HINMEI_NAME_RYAKU = N'銅屑（出荷）', HINMEI_FURIGANA = N'ドウクズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 118;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'雑線', HINMEI_NAME_RYAKU = N'雑線（出荷）', HINMEI_FURIGANA = N'ザッセン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 119;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ケーブル', HINMEI_NAME_RYAKU = N'ケーブル', HINMEI_FURIGANA = N'ケーブル', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 120;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'真鍮', HINMEI_NAME_RYAKU = N'真鍮', HINMEI_FURIGANA = N'シンチュウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 121;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'砲金', HINMEI_NAME_RYAKU = N'砲金', HINMEI_FURIGANA = N'ホウキン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 122;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'鉛屑', HINMEI_NAME_RYAKU = N'鉛屑', HINMEI_FURIGANA = N'ナマリクズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 123;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'亜鉛屑', HINMEI_NAME_RYAKU = N'亜鉛屑', HINMEI_FURIGANA = N'アエンクズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 124;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ステンレス屑', HINMEI_NAME_RYAKU = N'ステンレス屑', HINMEI_FURIGANA = N'ステンレスクズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 125;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'クローム', HINMEI_NAME_RYAKU = N'クローム', HINMEI_FURIGANA = N'クローム', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 126;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'アルミ屑', HINMEI_NAME_RYAKU = N'アルミ屑', HINMEI_FURIGANA = N'アルミクズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 127;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'雑品', HINMEI_NAME_RYAKU = N'雑品', HINMEI_FURIGANA = N'ザッピン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 128;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'配電盤', HINMEI_NAME_RYAKU = N'配電盤', HINMEI_FURIGANA = N'ハイデンバン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 129;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'モーター', HINMEI_NAME_RYAKU = N'モーター', HINMEI_FURIGANA = N'モーター', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 130;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'エアコン', HINMEI_NAME_RYAKU = N'エアコン', HINMEI_FURIGANA = N'エアコン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'中西　大樹', HAIKI_NAME_CD = N'' WHERE rn = 131;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'バッテリー', HINMEI_NAME_RYAKU = N'バッテリー', HINMEI_FURIGANA = N'バッテリー', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'中西　大樹', HAIKI_NAME_CD = N'' WHERE rn = 132;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'新断', HINMEI_NAME_RYAKU = N'新断', HINMEI_FURIGANA = N'シンタチ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 133;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ギロ材Ａ', HINMEI_NAME_RYAKU = N'ギロ材Ａ', HINMEI_FURIGANA = N'ギロザイＡ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 134;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ギロ材Ｂ', HINMEI_NAME_RYAKU = N'ギロ材Ｂ', HINMEI_FURIGANA = N'ギロザイＢ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 135;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'スチール缶', HINMEI_NAME_RYAKU = N'スチール缶', HINMEI_FURIGANA = N'スチールカン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 136;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'一斗缶', HINMEI_NAME_RYAKU = N'一斗缶', HINMEI_FURIGANA = N'イットカン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 137;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ドラム缶', HINMEI_NAME_RYAKU = N'ドラム缶', HINMEI_FURIGANA = N'ドラムカン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 138;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'シュレッダー', HINMEI_NAME_RYAKU = N'シュレッダー', HINMEI_FURIGANA = N'シュレッダー', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 139;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'アルミ缶', HINMEI_NAME_RYAKU = N'アルミ缶', HINMEI_FURIGANA = N'アルミカン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 140;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'アルミ板', HINMEI_NAME_RYAKU = N'アルミ板', HINMEI_FURIGANA = N'アルミイタ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 141;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'級外', HINMEI_NAME_RYAKU = N'級外', HINMEI_FURIGANA = N'キュウガイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 142;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ダライ粉', HINMEI_NAME_RYAKU = N'ダライ粉', HINMEI_FURIGANA = N'ダライコ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 143;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'解体ステンレス', HINMEI_NAME_RYAKU = N'解体ステンレス', HINMEI_FURIGANA = N'カイタイステンレス', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 144;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ステンレス粉', HINMEI_NAME_RYAKU = N'ステンレス粉', HINMEI_FURIGANA = N'ステンレスコ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 145;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'アルミ粉', HINMEI_NAME_RYAKU = N'アルミ粉', HINMEI_FURIGANA = N'アルミコ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 146;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'アルミホイル', HINMEI_NAME_RYAKU = N'アルミホイル', HINMEI_FURIGANA = N'アルミホイル', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 147;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'SUS301', HINMEI_NAME_RYAKU = N'SUS301', HINMEI_FURIGANA = N'ＳＵＳ３０１', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 148;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'SUS304', HINMEI_NAME_RYAKU = N'SUS304', HINMEI_FURIGANA = N'ＳＵＳ３０４', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 149;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'パーマ', HINMEI_NAME_RYAKU = N'パーマ', HINMEI_FURIGANA = N'パーマ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 150;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'アルミコロ', HINMEI_NAME_RYAKU = N'アルミコロ', HINMEI_FURIGANA = N'アルミコロ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 151;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'銅網', HINMEI_NAME_RYAKU = N'銅網', HINMEI_FURIGANA = N'ドウアミ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 152;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'コイル', HINMEI_NAME_RYAKU = N'コイル', HINMEI_FURIGANA = N'コイル', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 153;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'Ｈ３（出荷）', HINMEI_NAME_RYAKU = N'Ｈ３（出荷）', HINMEI_FURIGANA = N'Ｈ３シュッカ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 154;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'鋼板屑', HINMEI_NAME_RYAKU = N'鋼板屑', HINMEI_FURIGANA = N'コウバンクズ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 155;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'13ステン', HINMEI_NAME_RYAKU = N'13ステン', HINMEI_FURIGANA = N'１３ステン', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 156;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'18ステン', HINMEI_NAME_RYAKU = N'18ステン', HINMEI_FURIGANA = N'１８ステン', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 157;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'研磨粉', HINMEI_NAME_RYAKU = N'研磨粉', HINMEI_FURIGANA = N'ケンマコ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 158;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'新断バラ', HINMEI_NAME_RYAKU = N'新断バラ', HINMEI_FURIGANA = N'シンタチバラ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 159;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'新断バラ（出荷）', HINMEI_NAME_RYAKU = N'新断バラ（出荷）', HINMEI_FURIGANA = N'シンタチバラ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 160;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'新聞・雑誌', HINMEI_NAME_RYAKU = N'新聞・雑誌', HINMEI_FURIGANA = N'シンブンザッシ・', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 161;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'段ボール', HINMEI_NAME_RYAKU = N'段ボール', HINMEI_FURIGANA = N'ダンボール', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 162;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ウエス', HINMEI_NAME_RYAKU = N'ウエス', HINMEI_FURIGANA = N'ウエス', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 163;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'級外', HINMEI_NAME_RYAKU = N'級外', HINMEI_FURIGANA = N'キュウガイキュウガイ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 164;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'一本線', HINMEI_NAME_RYAKU = N'一本線', HINMEI_FURIGANA = N'イッポンセンセン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 165;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'古段ボール', HINMEI_NAME_RYAKU = N'古段ボール', HINMEI_FURIGANA = N'フルダンボール', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 166;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'銅線（特級銅屑60・一号銅屑40)', HINMEI_NAME_RYAKU = N'銅線（特級銅屑60・一', HINMEI_FURIGANA = N'ドウキレイナドウドウテツドウセントッキュ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 167;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'可燃物', HINMEI_NAME_RYAKU = N'可燃物', HINMEI_FURIGANA = N'カネンゴミイッパンハイキブツシュウシュウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 168;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'塵芥', HINMEI_NAME_RYAKU = N'塵芥', HINMEI_FURIGANA = N'チリアクタ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 169;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', HINMEI_NAME_RYAKU = N'紙くず', HINMEI_FURIGANA = N'カミクズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 170;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'弁当ガラ', HINMEI_NAME_RYAKU = N'弁当ガラ', HINMEI_FURIGANA = N'ベントウガラ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 171;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'繊維くず', HINMEI_NAME_RYAKU = N'繊維くず', HINMEI_FURIGANA = N'センイクズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 172;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック', HINMEI_NAME_RYAKU = N'廃プラスチック', HINMEI_FURIGANA = N'ハイプラスチック', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 173;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ダンボール', HINMEI_NAME_RYAKU = N'ダンボール', HINMEI_FURIGANA = N'ダンボール', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 174;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ペットボトル', HINMEI_NAME_RYAKU = N'ペットボトル', HINMEI_FURIGANA = N'ペットボトル', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 175;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'機密書類', HINMEI_NAME_RYAKU = N'機密書類', HINMEI_FURIGANA = N'キミツショルイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 176;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'不燃', HINMEI_NAME_RYAKU = N'不燃', HINMEI_FURIGANA = N'フネン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 177;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'一般廃棄物収集費', HINMEI_NAME_RYAKU = N'一般廃棄物収集費', HINMEI_FURIGANA = N'イッパンハイキブツシュウシュウウンパンシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 178;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ダンボール', HINMEI_NAME_RYAKU = N'ダンボール', HINMEI_FURIGANA = N'ダンボール', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 179;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙管', HINMEI_NAME_RYAKU = N'紙管', HINMEI_FURIGANA = N'シカン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 180;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'クラフト紙', HINMEI_NAME_RYAKU = N'クラフト紙', HINMEI_FURIGANA = N'クラフトシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 181;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'雑誌', HINMEI_NAME_RYAKU = N'雑誌', HINMEI_FURIGANA = N'ザッシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 182;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'新聞', HINMEI_NAME_RYAKU = N'新聞', HINMEI_FURIGANA = N'シンブン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 183;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'牛乳パック', HINMEI_NAME_RYAKU = N'牛乳パック', HINMEI_FURIGANA = N'ギュウニュウパック', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 184;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'上白', HINMEI_NAME_RYAKU = N'上白', HINMEI_FURIGANA = N'ジョウハク', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 185;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'中白', HINMEI_NAME_RYAKU = N'中白', HINMEI_FURIGANA = N'チュウハク', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 186;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ミックス', HINMEI_NAME_RYAKU = N'ミックス', HINMEI_FURIGANA = N'ミックス', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 187;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'OA用紙A', HINMEI_NAME_RYAKU = N'OA用紙A', HINMEI_FURIGANA = N'ＯＡヨウシＡ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 188;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'OA用紙B', HINMEI_NAME_RYAKU = N'OA用紙B', HINMEI_FURIGANA = N'ＯＡヨウシＢ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 189;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'機密書類', HINMEI_NAME_RYAKU = N'機密書類', HINMEI_FURIGANA = N'キミツショルイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 190;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ちらし', HINMEI_NAME_RYAKU = N'ちらし', HINMEI_FURIGANA = N'チラシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 191;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'色紙', HINMEI_NAME_RYAKU = N'色紙', HINMEI_FURIGANA = N'イロガミ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 192;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'シュレッター屑', HINMEI_NAME_RYAKU = N'シュレッター屑', HINMEI_FURIGANA = N'シュレッタークズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 193;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ライナー', HINMEI_NAME_RYAKU = N'ライナー', HINMEI_FURIGANA = N'ライナー', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 194;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ウエス', HINMEI_NAME_RYAKU = N'ウエス', HINMEI_FURIGANA = N'ウエス', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 195;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'再生紙', HINMEI_NAME_RYAKU = N'再生紙', HINMEI_FURIGANA = N'サイセイシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 196;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'回収手数料', HINMEI_NAME_RYAKU = N'回収手数料', HINMEI_FURIGANA = N'カイシュウテスウリョウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 197;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'機密処理代', HINMEI_NAME_RYAKU = N'機密処理代', HINMEI_FURIGANA = N'キミツショリダイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 198;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'収集運搬費', HINMEI_NAME_RYAKU = N'収集運搬費', HINMEI_FURIGANA = N'シュウシュウウンパンヒ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 199;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ノートパソコン処理代', HINMEI_NAME_RYAKU = N'ノートパソコン処理代', HINMEI_FURIGANA = N'ノートパソコンショリダイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 200;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ホイール', HINMEI_NAME_RYAKU = N'ホイール', HINMEI_FURIGANA = N'ホイール', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 201;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃食油（一斗缶）', HINMEI_NAME_RYAKU = N'廃食油（一斗缶）', HINMEI_FURIGANA = N'ハイショクユイットカン', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 202;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃食油（ドラム缶）', HINMEI_NAME_RYAKU = N'廃食油（ドラム缶）', HINMEI_FURIGANA = N'ハイショクユドラムカン', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 203;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ロスパン', HINMEI_NAME_RYAKU = N'ロスパン', HINMEI_FURIGANA = N'ロスパン', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 204;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ヘタパン', HINMEI_NAME_RYAKU = N'ヘタパン', HINMEI_FURIGANA = N'ヘタパン', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 205;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'微粉パン粉', HINMEI_NAME_RYAKU = N'微粉パン粉', HINMEI_FURIGANA = N'ビフンパンコ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 206;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'汚土(2tトラック)', HINMEI_NAME_RYAKU = N'汚土(2tトラック)', HINMEI_FURIGANA = N'オセンドツチ２ｔトラック', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 207;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'汚土(4tトラック)', HINMEI_NAME_RYAKU = N'汚土(4tトラック)', HINMEI_FURIGANA = N'４', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 208;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'残土券', HINMEI_NAME_RYAKU = N'残土券', HINMEI_FURIGANA = N'ザンドケンケン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 209;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'グリストラップ汚泥', HINMEI_NAME_RYAKU = N'グリストラップ汚泥', HINMEI_FURIGANA = N'グリストラップオデイ', CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子', HAIKI_NAME_CD = N'' WHERE rn = 210;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'破棄トナー', HINMEI_NAME_RYAKU = N'破棄トナー', HINMEI_FURIGANA = N'ハキトナー', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 211;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ペットボトル', HINMEI_NAME_RYAKU = N'ペットボトル', HINMEI_FURIGANA = N'ペットボトル', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 212;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラ', HINMEI_NAME_RYAKU = N'廃プラ', HINMEI_FURIGANA = N'ハイプラ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一', HAIKI_NAME_CD = N'' WHERE rn = 213;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃棄物の品名', HINMEI_NAME_RYAKU = N'廃棄物の品名', HINMEI_FURIGANA = N'ｈｏＤｋＭｂｖｔｄｎｎｈｒｎｍＤＡＡｉｎ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 214;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'剪定枝', HINMEI_NAME_RYAKU = N'剪定枝', HINMEI_FURIGANA = N'センテイエダ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 215;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'幹（生）', HINMEI_NAME_RYAKU = N'幹（生）', HINMEI_FURIGANA = N'ミキナマ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 216;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'草木', HINMEI_NAME_RYAKU = N'草木', HINMEI_FURIGANA = N'クサキ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 217;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃パレット', HINMEI_NAME_RYAKU = N'廃パレット', HINMEI_FURIGANA = N'ハイパレット', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 218;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'プリンタ回収', HINMEI_NAME_RYAKU = N'プリンタ回収', HINMEI_FURIGANA = N'プリンタカイシュウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 219;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'鉄くず', HINMEI_NAME_RYAKU = N'鉄くず', HINMEI_FURIGANA = N'テツクズ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一', HAIKI_NAME_CD = N'' WHERE rn = 220;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'木パレット', HINMEI_NAME_RYAKU = N'木パレット', HINMEI_FURIGANA = N'キクズパレット', CREATE_USER = N'安田　彬', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 221;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃機器・金属類', HINMEI_NAME_RYAKU = N'廃機器・金属類', HINMEI_FURIGANA = N'ハイキキ・キンゾクルイ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 222;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'発泡スチロール', HINMEI_NAME_RYAKU = N'発泡スチロール', HINMEI_FURIGANA = N'ハッポウスチロール', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 223;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'段ボール', HINMEI_NAME_RYAKU = N'段ボール', HINMEI_FURIGANA = N'ダンボール', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 224;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリはつりくず', HINMEI_NAME_RYAKU = N'コンクリはつりくず', HINMEI_FURIGANA = N'コンクリハツリクズ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 225;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'浴槽（プラスチック浴槽）', HINMEI_NAME_RYAKU = N'浴槽（プラスチック浴', HINMEI_FURIGANA = N'ヨクソウプラスチックヨクソウ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 226;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'浴槽（ステンレス浴槽）', HINMEI_NAME_RYAKU = N'浴槽（ステンレス浴槽', HINMEI_FURIGANA = N'ヨクソウステンレスヨクソウ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 227;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'浴槽（ホーロー浴槽）', HINMEI_NAME_RYAKU = N'浴槽（ホーロー浴槽）', HINMEI_FURIGANA = N'ヨクソウホーローヨクソウ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 228;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'スーパー廃プラスチック', HINMEI_NAME_RYAKU = N'スーパー廃プラスチッ', HINMEI_FURIGANA = N'スーパーハイプラスチック', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 229;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック', HINMEI_NAME_RYAKU = N'廃プラスチック', HINMEI_FURIGANA = N'ハイプラスチック', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 230;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'住設機器・建具類・その他のもの', HINMEI_NAME_RYAKU = N'住設機器・建具類・そ', HINMEI_FURIGANA = N'ジュウセツキキ・タテグルイ・ソノタノモノ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 231;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃機器', HINMEI_NAME_RYAKU = N'廃機器', HINMEI_FURIGANA = N'ハイキキ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 232;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', HINMEI_NAME_RYAKU = N'木くず', HINMEI_FURIGANA = N'キクズ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 233;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'エアコン', HINMEI_NAME_RYAKU = N'エアコン', HINMEI_FURIGANA = N'エアコン', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 234;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'乾燥機', HINMEI_NAME_RYAKU = N'乾燥機', HINMEI_FURIGANA = N'カンソウキ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 235;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'生ごみ', HINMEI_NAME_RYAKU = N'生ごみ', HINMEI_FURIGANA = N'ナマゴミ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 236;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'磁選', HINMEI_NAME_RYAKU = N'磁選', HINMEI_FURIGANA = N'ジセン', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 237;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'汚泥　ローリー', HINMEI_NAME_RYAKU = N'汚泥　ローリー', HINMEI_FURIGANA = N'オデイローリー', CREATE_USER = N'安田　彬', UPDATE_USER = N'安田　彬', HAIKI_NAME_CD = N'' WHERE rn = 238;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'汚泥　バラ', HINMEI_NAME_RYAKU = N'汚泥　バラ', HINMEI_FURIGANA = N'オデイバラ', CREATE_USER = N'安田　彬', UPDATE_USER = N'安田　彬', HAIKI_NAME_CD = N'' WHERE rn = 239;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'FRP', HINMEI_NAME_RYAKU = N'FRP', HINMEI_FURIGANA = N'ＦＲＰ', CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子', HAIKI_NAME_CD = N'' WHERE rn = 240;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', HINMEI_NAME_RYAKU = N'紙くず', HINMEI_FURIGANA = N'カミクズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 241;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'10t常用', HINMEI_NAME_RYAKU = N'10t常用', HINMEI_FURIGANA = N'ジョウヨウ１０ｔ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 242;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'処分費', HINMEI_NAME_RYAKU = N'処分費', HINMEI_FURIGANA = N'ショブンヒ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 243;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'産廃ボックス', HINMEI_NAME_RYAKU = N'産廃ボックス', HINMEI_FURIGANA = N'サンパイボックス', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 244;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリート塊', HINMEI_NAME_RYAKU = N'コンクリート塊', HINMEI_FURIGANA = N'コンクリートカタマリ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 245;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリート塊（有筋）', HINMEI_NAME_RYAKU = N'コンクリート塊（有筋', HINMEI_FURIGANA = N'コンクリートカタマリユウキン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 246;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'土砂', HINMEI_NAME_RYAKU = N'土砂', HINMEI_FURIGANA = N'ドシャ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 247;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'在庫Ａ', HINMEI_NAME_RYAKU = N'在庫Ａ', HINMEI_FURIGANA = N'ザイコＡ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 248;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'一本線', HINMEI_NAME_RYAKU = N'一本線', HINMEI_FURIGANA = N'イッポンセン', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 249;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'銅（出荷）', HINMEI_NAME_RYAKU = N'銅（出荷）', HINMEI_FURIGANA = N'ドウシュッカ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 250;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'電線', HINMEI_NAME_RYAKU = N'電線', HINMEI_FURIGANA = N'デンセン', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 251;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'電線ＡＢ', HINMEI_NAME_RYAKU = N'電線ＡＢ', HINMEI_FURIGANA = N'デンセンＡＢ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 252;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'電線（出荷', HINMEI_NAME_RYAKU = N'電線（出荷', HINMEI_FURIGANA = N'デンセンシュッカシュッカ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 253;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'一本線', HINMEI_NAME_RYAKU = N'一本線', HINMEI_FURIGANA = N'イッポンセン', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 254;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'一本線（出荷）', HINMEI_NAME_RYAKU = N'一本線（出荷）', HINMEI_FURIGANA = N'イッポンセンシュッカ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 255;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'一般廃棄物収集・処分料　', HINMEI_NAME_RYAKU = N'可燃物', HINMEI_FURIGANA = N'カネンブツ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 256;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'一般廃棄物収集・処分料　(不燃)', HINMEI_NAME_RYAKU = N'不燃物', HINMEI_FURIGANA = N'リョウフネンコメカッコフネン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 257;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'一般廃棄物　収集運搬料', HINMEI_NAME_RYAKU = N'一般廃棄物　収集運搬', HINMEI_FURIGANA = N'イッパンハイキブツシュウシュウウンパンリ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 258;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'一般廃棄物　可燃ごみ', HINMEI_NAME_RYAKU = N'一般廃棄物　可燃ごみ', HINMEI_FURIGANA = N'イッパンハイキブツカネンゴミ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 259;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'一般廃棄物　不燃ごみ', HINMEI_NAME_RYAKU = N'一般廃棄物　不燃ごみ', HINMEI_FURIGANA = N'イッパンハイキブツフネンゴミ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 260;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'産業廃棄物処分料', HINMEI_NAME_RYAKU = N'産業廃棄物処分料', HINMEI_FURIGANA = N'サンギョウハイキブツショウブンショブンリ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 261;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'産業廃棄物処分料', HINMEI_NAME_RYAKU = N'産業廃棄物処分料', HINMEI_FURIGANA = N'サンギョウハイキブツショブンリョウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 262;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'一般廃棄物収集運搬処理料', HINMEI_NAME_RYAKU = N'一般廃棄物収集運搬処', HINMEI_FURIGANA = N'イッパンハイキブツシュウシュウウンパンシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 263;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃棄ＰＣ', HINMEI_NAME_RYAKU = N'廃棄ＰＣ', HINMEI_FURIGANA = N'ハイキＰＣ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 264;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'１２３４５６７８９０一二三四五六七八九〇', HINMEI_NAME_RYAKU = N'１２３４５６７８９０', HINMEI_FURIGANA = N'１２３４５６７８９０１２３４５６７８９０', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 265;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'あいう', HINMEI_NAME_RYAKU = N'あいう', HINMEI_FURIGANA = N'アオイアイウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 266;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'RECYCLING SOLVENT', HINMEI_NAME_RYAKU = N'RECYCLING SOLVENT', HINMEI_FURIGANA = N'ＲＥＣＹＣＬＩＮＧＳＯＬＶＥＮＴ', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊', HAIKI_NAME_CD = N'' WHERE rn = 267;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'Tansport chage', HINMEI_NAME_RYAKU = N'Tansport chage', HINMEI_FURIGANA = N'Tansport chage', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊', HAIKI_NAME_CD = N'' WHERE rn = 268;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'１０ｔダンプ', HINMEI_NAME_RYAKU = N'１０ｔダンプ', HINMEI_FURIGANA = N'１０ｔダンプ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 269;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'解体工事費', HINMEI_NAME_RYAKU = N'解体工事費', HINMEI_FURIGANA = N'カイタイコウジヒカイタイコウジヒ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 270;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'PP(マルマル）', HINMEI_NAME_RYAKU = N'PP(マルマル）', HINMEI_FURIGANA = N'ＰＰマルマル', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 271;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラ 処理費', HINMEI_NAME_RYAKU = N'廃プラ 処理費（これ', HINMEI_FURIGANA = N'ハイプラショオリヒショリヒ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 272;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'PP（△△）', HINMEI_NAME_RYAKU = N'PP（△△）', HINMEI_FURIGANA = N'ＰＰサンカクサンカク', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 273;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'はっぽう', HINMEI_NAME_RYAKU = N'はっぽう', HINMEI_FURIGANA = N'ハッポウスハッポウ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 274;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'発泡スチロール処理費', HINMEI_NAME_RYAKU = N'発泡スチロール処理費', HINMEI_FURIGANA = N'ハッポウスチロールショリヒ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 275;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'テストプラ', HINMEI_NAME_RYAKU = N'テストプラ', HINMEI_FURIGANA = N'テストプラ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 276;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'混合廃棄物（処理）あああああああ', HINMEI_NAME_RYAKU = N'混合廃棄物（処理）', HINMEI_FURIGANA = N'コンゴウハイキブツショリアアアアアアア', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 277;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ダンボール', HINMEI_NAME_RYAKU = N'ダンボール', HINMEI_FURIGANA = N'ダンボールダン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 278;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ダンボール', HINMEI_NAME_RYAKU = N'ダンボール', HINMEI_FURIGANA = N'ダンボールダン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 279;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'計量作業費', HINMEI_NAME_RYAKU = N'計量作業費', HINMEI_FURIGANA = N'ケイリョウノミケイリョウケイリョウヒョウ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一', HAIKI_NAME_CD = N'' WHERE rn = 280;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'汚泥回収', HINMEI_NAME_RYAKU = N'汚泥回収', HINMEI_FURIGANA = N'オデイカイシュウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 281;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'値引', HINMEI_NAME_RYAKU = N'値引（内税）', HINMEI_FURIGANA = N'ネビキウチゼイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 282;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'あいうえお', HINMEI_NAME_RYAKU = N'あいうえお', HINMEI_FURIGANA = N'アイウエオ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 283;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃塗料あいうおえ', HINMEI_NAME_RYAKU = N'廃塗料あいうおえ', HINMEI_FURIGANA = N'ハイトリョウアイウオエ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 284;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', HINMEI_NAME_RYAKU = N'木くず', HINMEI_FURIGANA = N'キクズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 285;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'高速代', HINMEI_NAME_RYAKU = N'高速代', HINMEI_FURIGANA = N'コウソクダイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 286;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'印紙代（委託契約書）', HINMEI_NAME_RYAKU = N'印紙代（委託契約書）', HINMEI_FURIGANA = N'インシダイイタクケイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 287;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック', HINMEI_NAME_RYAKU = N'廃プラスチック', HINMEI_FURIGANA = N'ハイプラスチック', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 288;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら（無筋）', HINMEI_NAME_RYAKU = N'コンクリートがら（無', HINMEI_FURIGANA = N'コンクリートガラムキン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 289;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'RC-40（販売）4t', HINMEI_NAME_RYAKU = N'RC-40（販売）4t', HINMEI_FURIGANA = N'ｒｃ－４０ハンバイ４ｔ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 290;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'配送料', HINMEI_NAME_RYAKU = N'配送料', HINMEI_FURIGANA = N'ハイソウリョウハイソウリョウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 291;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら（有筋）', HINMEI_NAME_RYAKU = N'コンクリートがら（有', HINMEI_FURIGANA = N'コンクリートガラユウキン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 292;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'A材', HINMEI_NAME_RYAKU = N'A材', HINMEI_FURIGANA = N'エーザイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 293;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'級外品', HINMEI_NAME_RYAKU = N'級外品', HINMEI_FURIGANA = N'キュウガイヒン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 294;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'雑線', HINMEI_NAME_RYAKU = N'雑線', HINMEI_FURIGANA = N'ザツセン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 295;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'アルミパーマ', HINMEI_NAME_RYAKU = N'アルミパーマ', HINMEI_FURIGANA = N'アルミパーマ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 296;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'解体ステン', HINMEI_NAME_RYAKU = N'解体ステン', HINMEI_FURIGANA = N'カイタイステン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 297;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラ（運搬費込み）', HINMEI_NAME_RYAKU = N'廃プラ（運搬費込み）', HINMEI_FURIGANA = N'ハイプラウンパンヒコミコミ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 298;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'TB', HINMEI_NAME_RYAKU = N'TB', HINMEI_FURIGANA = N'ＴＢ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 299;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'生脂（0～49kg）', HINMEI_NAME_RYAKU = N'生脂（0～49kg）', HINMEI_FURIGANA = N'ナマシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 300;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'生脂（50～149kg）', HINMEI_NAME_RYAKU = N'生脂（50～149kg）', HINMEI_FURIGANA = N'ナマシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 301;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'生脂（150～299kg）', HINMEI_NAME_RYAKU = N'生脂（150～299kg）', HINMEI_FURIGANA = N'ナマシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 302;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', HINMEI_NAME_RYAKU = N'紙くず', HINMEI_FURIGANA = N'カミクズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 303;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'フリー', HINMEI_NAME_RYAKU = N'フリー', HINMEI_FURIGANA = N'フリー', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 304;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'20L　ポリ', HINMEI_NAME_RYAKU = N'20L　ポリ', HINMEI_FURIGANA = N'２０Ｌポリ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'900000' WHERE rn = 305;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'20L　段ボール', HINMEI_NAME_RYAKU = N'20L　段ボール', HINMEI_FURIGANA = N'２０Ｌダンボール', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'000102' WHERE rn = 306;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'40L　段ボール', HINMEI_NAME_RYAKU = N'40L　段ボール', HINMEI_FURIGANA = N'４０Lダンボール', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'000006' WHERE rn = 307;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'入替', HINMEI_NAME_RYAKU = N'入替', HINMEI_FURIGANA = N'イレカエ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 308;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'新設', HINMEI_NAME_RYAKU = N'新設', HINMEI_FURIGANA = N'シンセツ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 309;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートガラ', HINMEI_NAME_RYAKU = N'コンクリートガラ', HINMEI_FURIGANA = N'コンクリートガラ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 310;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'産廃税（最終', HINMEI_NAME_RYAKU = N'産廃税（最終', HINMEI_FURIGANA = N'サンパイゼイサイシュウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 311;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'調整値引き', HINMEI_NAME_RYAKU = N'調整値引き', HINMEI_FURIGANA = N'チョウセイネビキ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 312;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'ダスト引き', HINMEI_NAME_RYAKU = N'ダスト引き', HINMEI_FURIGANA = N'ダストビキ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 313;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'収入印紙', HINMEI_NAME_RYAKU = N'収入印紙', HINMEI_FURIGANA = N'シュウニュウシュウニュウインシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 314;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'運賃', HINMEI_NAME_RYAKU = N'運賃', HINMEI_FURIGANA = N'ウンチン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 315;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'高速代', HINMEI_NAME_RYAKU = N'高速代', HINMEI_FURIGANA = N'コウソクダイ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'' WHERE rn = 316;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'混合B', HINMEI_NAME_RYAKU = N'混合B', HINMEI_FURIGANA = N'コンゴウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', HAIKI_NAME_CD = N'000102' WHERE rn = 317;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HINMEI)
UPDATE T SET HINMEI_NAME = N'産廃税', HINMEI_NAME_RYAKU = N'産廃税', HINMEI_FURIGANA = N'サンパイゼイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', HAIKI_NAME_CD = N'' WHERE rn = 318;

