-- UPDATE script for table M_HOUKOKUSHO_BUNRUI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 46

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'燃え殻', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'燃え殻', HOUKOKUSHO_BUNRUI_FURIGANA = N'モエガラ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'汚泥', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'汚泥', HOUKOKUSHO_BUNRUI_FURIGANA = N'オデイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃油', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'廃油', HOUKOKUSHO_BUNRUI_FURIGANA = N'ハイユ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃酸', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'廃酸', HOUKOKUSHO_BUNRUI_FURIGANA = N'ハイサン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃アルカリ', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'廃アルカリ', HOUKOKUSHO_BUNRUI_FURIGANA = N'ハイアルカリ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'廃プラスチック', HOUKOKUSHO_BUNRUI_FURIGANA = N'ハイプラスチック', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'紙くず', HOUKOKUSHO_BUNRUI_FURIGANA = N'カミクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'木くず', HOUKOKUSHO_BUNRUI_FURIGANA = N'キクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'繊維くず', HOUKOKUSHO_BUNRUI_FURIGANA = N'センイクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'動・植物性残さ', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'動・植物性残さ', HOUKOKUSHO_BUNRUI_FURIGANA = N'ドウ・ショクブツセイザンサ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ゴムくず', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'ゴムくず', HOUKOKUSHO_BUNRUI_FURIGANA = N'ゴムクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'金属くず', HOUKOKUSHO_BUNRUI_FURIGANA = N'キンゾククズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'ガラス・陶磁器くず', HOUKOKUSHO_BUNRUI_FURIGANA = N'ガラス・トウジキクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'鉱さい', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'鉱さい', HOUKOKUSHO_BUNRUI_FURIGANA = N'コウサイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'がれき類', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'がれき類', HOUKOKUSHO_BUNRUI_FURIGANA = N'ガレキルイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'動物のふん尿', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'動物のふん尿', HOUKOKUSHO_BUNRUI_FURIGANA = N'ドウブツノフンニョウ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'動物の死体', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'動物の死体', HOUKOKUSHO_BUNRUI_FURIGANA = N'ドウブツノシタイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ばいじん', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'ばいじん', HOUKOKUSHO_BUNRUI_FURIGANA = N'バイジン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'１３号廃棄物', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'１３号廃棄物', HOUKOKUSHO_BUNRUI_FURIGANA = N'１３ゴウハイキブツ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'非飛散性アスベスト', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'非飛散性アスベスト', HOUKOKUSHO_BUNRUI_FURIGANA = N'ヒヒサンセイアスベスト', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'動物系固形不要物', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'動物系固形不要物', HOUKOKUSHO_BUNRUI_FURIGANA = N'ドウブツケイコケイフヨウブツ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラスくず・コンクリートくず及び陶磁器くず', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'ガラスくず・コンクリ', HOUKOKUSHO_BUNRUI_FURIGANA = N'ガラスクズ・コンクリートクズオヨビトウジキクズ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'政令第１３号廃棄物', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'政令第１３号廃棄物', HOUKOKUSHO_BUNRUI_FURIGANA = N'セイレイダイ１３ゴウハイキブツ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'引火性廃油', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'引火性廃油', HOUKOKUSHO_BUNRUI_FURIGANA = N'インカセイハイユ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'強酸', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'強酸', HOUKOKUSHO_BUNRUI_FURIGANA = N'キョウサン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'強アルカリ', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'強アルカリ', HOUKOKUSHO_BUNRUI_FURIGANA = N'キョウアルカリ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'感染性廃棄物', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'感染性廃棄物', HOUKOKUSHO_BUNRUI_FURIGANA = N'カンセンセイハイキブツ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'特定有害産業廃棄物', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'特定有害廃棄物', HOUKOKUSHO_BUNRUI_FURIGANA = N'トクテイユウガイサンギョウハイキブツ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃油（揮発油類、灯油類及び軽油類）', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'廃油（特管類）', HOUKOKUSHO_BUNRUI_FURIGANA = N'ハイユ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃酸（ph２．０以下のものに限る。）', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'廃酸（特管類）', HOUKOKUSHO_BUNRUI_FURIGANA = N'ハイサン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃アルカリ（ph１２．５以上のものに限る。）', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'廃アルカリ（特管類）', HOUKOKUSHO_BUNRUI_FURIGANA = N'ハイアルカリ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'感染性産業廃棄物', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'感染性産業廃棄物', HOUKOKUSHO_BUNRUI_FURIGANA = N'カンセンセイサンギョウハイキブツ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃PCB', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'廃PCB', HOUKOKUSHO_BUNRUI_FURIGANA = N'ハイＰＣＢ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'PCB汚染物', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'PCB汚染物', HOUKOKUSHO_BUNRUI_FURIGANA = N'ＰＣＢオセンブツ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'PCB処理物', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'PCB処理物', HOUKOKUSHO_BUNRUI_FURIGANA = N'ＰＣＢショリブツ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'指定下水汚泥等', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'指定下水汚泥等', HOUKOKUSHO_BUNRUI_FURIGANA = N'シテイゲスイオデイトウ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'鉱さい（有害物質を含む鉱さい）', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'鉱さい（特管類）', HOUKOKUSHO_BUNRUI_FURIGANA = N'コウサイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃石綿等', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'廃石綿等', HOUKOKUSHO_BUNRUI_FURIGANA = N'ハイセキメントウ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ばいじん（有害物質を含むばいじん）', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'ばいじん（特管類）', HOUKOKUSHO_BUNRUI_FURIGANA = N'バイジン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'燃え殻（有害物質を含む燃え殻）', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'燃え殻（特管類）', HOUKOKUSHO_BUNRUI_FURIGANA = N'モエガラ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃油（有害物質を含む廃油）', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'廃油（特管類）', HOUKOKUSHO_BUNRUI_FURIGANA = N'ハイユ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'汚泥（有害物質を含む汚泥）', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'汚泥（特管類）', HOUKOKUSHO_BUNRUI_FURIGANA = N'オデイ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃酸（有害物質を含む廃酸）', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'廃酸（特管類）', HOUKOKUSHO_BUNRUI_FURIGANA = N'ハイサン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃アルカリ（有害物質を含む廃アルカリ）', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'廃アルカリ（特管類）', HOUKOKUSHO_BUNRUI_FURIGANA = N'ハイアルカリ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'その他', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'その他', HOUKOKUSHO_BUNRUI_FURIGANA = N'ソノタ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_HOUKOKUSHO_BUNRUI)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'テスト', HOUKOKUSHO_BUNRUI_NAME_RYAKU = N'テスト', HOUKOKUSHO_BUNRUI_FURIGANA = N'テスト', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 46;

