-- UPDATE script for table M_ITAKU_KEIYAKU_BESSHI_TAITORU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 147

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'将軍情報で印刷' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'将軍情報で印刷' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 62;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 63;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 64;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 65;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 66;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 67;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 68;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 69;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 70;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 71;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 72;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 73;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 74;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 75;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'将軍情報で印刷' WHERE rn = 76;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'将軍情報で印刷' WHERE rn = 77;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'将軍情報で印刷' WHERE rn = 78;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'将軍情報で印刷' WHERE rn = 79;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'将軍情報で印刷' WHERE rn = 80;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'将軍情報で印刷' WHERE rn = 81;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'将軍情報で印刷' WHERE rn = 82;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'将軍情報で印刷' WHERE rn = 83;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 84;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 85;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 86;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 87;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 88;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 89;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 90;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 91;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 92;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 93;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 94;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 95;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 96;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 97;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 98;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 99;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 100;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 101;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 102;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 103;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 104;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 105;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 106;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 107;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 108;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 109;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 110;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 111;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 112;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 113;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 114;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 115;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 116;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 117;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 118;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 119;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 120;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 121;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 122;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 123;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 124;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 125;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 126;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 127;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 128;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 129;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 130;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 131;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 132;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 133;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 134;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 135;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 136;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 137;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 138;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 139;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 140;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 141;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 142;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 143;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 144;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 145;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 146;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BESSHI_TAITORU)
UPDATE T SET SAKUSEI_HOUHOU_NAME = N'印刷しない' WHERE rn = 147;

