-- UPDATE script for table M_ITAKU_KEIYAKU_BETSU4 (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 38

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = N'がれき類' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'エジソン商事', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31あ', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'住所２', LAST_SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = N'鉱さい' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'エジソン商事', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = N'燃え殻' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'エジソン商事', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31あ', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'住所２', LAST_SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = N'動・植物性残さ' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = N'' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = N'' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = N'' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = N'がれき類' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = N'' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'エジソン商事', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市中央1-4-1', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'エジソン商事', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市中央1-4-1', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'エジソン商事', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31あ', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'住所２', LAST_SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'エジソン商事', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31あ', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'住所２', LAST_SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'エジソン商事', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'笠間工場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'笠間市住吉23-1', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = N'燃え殻' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = N'' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'エジソン商事', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'エジソン商事', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'若槻リサイクル', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'久喜市新井7-6-1', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'A-303', LAST_SHOBUN_JIGYOUJOU_NAME = N'若槻リサイクル', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'久喜市新井7-6-1', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'A-303', HOUKOKUSHO_BUNRUI_NAME = N'廃油' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'ナカゾネ産業', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'土浦市中村西根50-1-2', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'ナカゾネ産業　藤岡処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'藤岡市下戸塚大字稲荷1028（他8筆）', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'エジソン商事', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市中央1-4-1', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'エジソン商事', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市中央1-4-1', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'博多ケミカル', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'福岡市博多区博多駅前', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'博多ケミカル筑紫口', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'福岡市博多区博多駅前', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'ナカゾネ産業', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'土浦市中村西根50-1-2', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'ナカゾネ産業　藤岡処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'藤岡市下戸塚大字稲荷1028（他8筆）', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'モバイル検証2024_業者略称', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'住所1住所1住所1住所1住所1住所1住所1住所1', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'住所2住所2住所2住所2住所2住所2住所2住所2', LAST_SHOBUN_JIGYOUJOU_NAME = N'モバイル検証2024_現場略称', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'住所1住所1住所1住所1住所1住所1住所1住所1', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'住所2住所2住所2住所2住所2住所2住所2住所2', HOUKOKUSHO_BUNRUI_NAME = NULL WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU4)
UPDATE T SET LAST_SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', LAST_SHOBUN_GYOUSHA_ADDRESS = NULL, LAST_SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', LAST_SHOBUN_GYOUSHA_ADDRESS2 = N'', LAST_SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', LAST_SHOBUN_JIGYOUJOU_ADDRESS = NULL, LAST_SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', LAST_SHOBUN_JIGYOUJOU_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = N'' WHERE rn = 38;

