-- UPDATE script for table M_ITAKU_KEIYAKU_HINMEI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 215

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'繊維くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス陶磁器くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'アスコンがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'その他がれき類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'繊維くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス陶磁器くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'アスコンがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'その他がれき類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'繊維くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス陶磁器くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'アスコンがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'その他がれき類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'繊維くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス陶磁器くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'アスコンがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'その他がれき類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'繊維くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス陶磁器くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'アスコンがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'その他がれき類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'繊維くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス陶磁器くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'アスコンがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'その他がれき類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'繊維くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス陶磁器くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'アスコンがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 62;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'その他がれき類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 63;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 64;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 65;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 66;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'繊維くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 67;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 68;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス陶磁器くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 69;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 70;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'アスコンがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 71;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'その他がれき類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 72;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 73;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 74;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 75;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'繊維くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 76;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 77;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス陶磁器くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 78;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 79;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'アスコンがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 80;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'その他がれき類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 81;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 82;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 83;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 84;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'繊維くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 85;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 86;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス陶磁器くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 87;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 88;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'アスコンがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 89;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'その他がれき類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 90;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 91;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 92;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 93;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'繊維くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 94;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 95;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス陶磁器くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 96;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 97;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'アスコンがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 98;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'その他がれき類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 99;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 100;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 101;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 102;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'繊維くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 103;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 104;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス陶磁器くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 105;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 106;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'アスコンがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 107;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'その他がれき類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 108;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 109;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 110;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ダンボール', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 111;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 112;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 113;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 114;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 115;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'繊維くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 116;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 117;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス陶磁器くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 118;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 119;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 120;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 121;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'クロス', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 122;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 123;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 124;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 125;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス陶磁器くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 126;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 127;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'感染性廃棄物', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 128;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類（混廃）', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸リサイクルセンター', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 129;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'生木', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 130;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 131;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 132;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス陶磁器くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 133;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 134;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 135;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 136;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'繊維くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 137;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 138;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス陶磁器くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 139;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 140;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'アスコンがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 141;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'その他がれき類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 142;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 143;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'クロス', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 144;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 145;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 146;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'クロス', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 147;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'生木', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 148;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 149;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃石膏ボード', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 150;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 151;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 152;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'クロス', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 153;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'生木', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 154;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 155;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃石膏ボード', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 156;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 157;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'その他がれき類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 158;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 159;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 160;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃石膏ボード', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 161;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'コンクリートがら', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 162;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'汚泥', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 163;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ガラス陶磁器くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市中央1-4-1', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 164;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'アスコンがら', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市中央1-4-1', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 165;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 166;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'クロス', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 167;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 168;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 169;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 170;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'混合廃棄物A', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 171;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 172;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'蛍光灯', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 173;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ダンボール', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 174;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 175;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'小山中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'小山市大字下国府塚25-1', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 176;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'小山中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'小山市大字下国府塚25-1', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 177;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'繊維くずA', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'小山中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'小山市大字下国府塚25-1', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 178;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'混合廃棄物A', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 179;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'汚泥', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 180;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'混合廃棄物A', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 181;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'固化物汚泥', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 182;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'軟弱汚泥', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 183;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 184;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 185;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'金属くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 186;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'汚泥', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 187;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'混合廃棄物', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 188;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 189;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 190;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'クロス', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 191;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃石膏ボード', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 192;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 193;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 194;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 195;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 196;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'繊維くずA', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 197;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 198;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'クロス', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 199;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'紙くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 200;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'ダンボール', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 201;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'木くず', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 202;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'生木', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 203;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 204;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'一般廃棄物収集費', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 205;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 206;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'クロス', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 207;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 208;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 209;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 210;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'生木', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 211;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 212;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 213;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', SHOBUN_JUTAKUSHA_NAME = NULL, SHOBUN_JIGYOUJOU_NAME = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = NULL, SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 214;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_HINMEI)
UPDATE T SET HINMEI_NAME = N'混合廃棄物', SHOBUN_JUTAKUSHA_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市中央1-4-1', SHOBUN_JIGYOUJOU_ADDRESS2 = NULL WHERE rn = 215;

