-- UPDATE script for table M_ITAKU_KEIYAKU_BETSU2 (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 63

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31あ', UNPAN_GYOUSHA_ADDRESS2 = N'住所２' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31あ', UNPAN_GYOUSHA_ADDRESS2 = N'住所２' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31あ', UNPAN_GYOUSHA_ADDRESS2 = N'住所２' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'シマヅ運送', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'常総市坂手町5687-1', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31あ', UNPAN_GYOUSHA_ADDRESS2 = N'住所２' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'阿良川工業', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'名古屋市中村区名駅1-1-1', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31あ', UNPAN_GYOUSHA_ADDRESS2 = N'住所２' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31あ', UNPAN_GYOUSHA_ADDRESS2 = N'住所２' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'ホソカワ運送', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市高野1197-20', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'赤松運輸', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市栗原1-2-3', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'赤松運輸', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市栗原1-2-3', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'赤松運輸', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市栗原1-2-3', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'柴田物流', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'福岡市博多区博多駅前', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'ヨシダ通運', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市吾妻9-9-9', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'野茂建設', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'福岡市博多区美野島', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'阿良川工業', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'名古屋市中村区名駅1-1-1９９９９', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'モバイル検証2024_業者略称', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'住所1住所1住所1住所1住所1住所1住所1住所1', UNPAN_GYOUSHA_ADDRESS2 = N'住所2住所2住所2住所2住所2住所2住所2住所2' WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'モバイル検証2024_業者略称', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'住所1住所1住所1住所1住所1住所1住所1住所1', UNPAN_GYOUSHA_ADDRESS2 = N'住所2住所2住所2住所2住所2住所2住所2住所2' WHERE rn = 62;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU2)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNPAN_GYOUSHA_ADDRESS = NULL, UNPAN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', UNPAN_GYOUSHA_ADDRESS2 = N'' WHERE rn = 63;

