-- UPDATE script for table M_ITAKU_KEIYAKU_SAISEIHINM (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 11

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_SAISEIHINM)
UPDATE T SET SAISEI_HINMOKU_NAME = N'木質チップ', BAIKYAKUSAKI_NAME = N'＠＠商事' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_SAISEIHINM)
UPDATE T SET SAISEI_HINMOKU_NAME = N'RPF', BAIKYAKUSAKI_NAME = N'★商店' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_SAISEIHINM)
UPDATE T SET SAISEI_HINMOKU_NAME = N'さいせいひんもく', BAIKYAKUSAKI_NAME = N'ばいきゃくさき' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_SAISEIHINM)
UPDATE T SET SAISEI_HINMOKU_NAME = N'あああ', BAIKYAKUSAKI_NAME = N'' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_SAISEIHINM)
UPDATE T SET SAISEI_HINMOKU_NAME = N'あああ', BAIKYAKUSAKI_NAME = N'' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_SAISEIHINM)
UPDATE T SET SAISEI_HINMOKU_NAME = N'こけくきかおえういあ', BAIKYAKUSAKI_NAME = N'こけくきかおえういあ' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_SAISEIHINM)
UPDATE T SET SAISEI_HINMOKU_NAME = N'さしすせそ', BAIKYAKUSAKI_NAME = N'そせすしさ' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_SAISEIHINM)
UPDATE T SET SAISEI_HINMOKU_NAME = N'こけくきかおえういあ', BAIKYAKUSAKI_NAME = N'こけくきかおえういあ' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_SAISEIHINM)
UPDATE T SET SAISEI_HINMOKU_NAME = N'こけくきかおえういあ', BAIKYAKUSAKI_NAME = N'こけくきかおえういあ' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_SAISEIHINM)
UPDATE T SET SAISEI_HINMOKU_NAME = N'こけくきかおえういあ', BAIKYAKUSAKI_NAME = N'こけくきかおえういあ' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_SAISEIHINM)
UPDATE T SET SAISEI_HINMOKU_NAME = N'砂利', BAIKYAKUSAKI_NAME = N'' WHERE rn = 11;

