-- UPDATE script for table M_ITAKU_KEIYAKU_TSUMIKAE (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 8

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_TSUMIKAE)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'天の川産業', TSUMIKAE_HOKANBA_NAME = N'天の川産業　つくば市花室保管場', TSUMIKAE_HOKANBA_ADDRESS1 = N'つくば市花室4-9地内', TSUMIKAE_HOKANBA_ADDRESS2 = N'' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_TSUMIKAE)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'ウベ運輸', TSUMIKAE_HOKANBA_NAME = N'ウベ運輸', TSUMIKAE_HOKANBA_ADDRESS1 = N'つくば市学園の森2-33', TSUMIKAE_HOKANBA_ADDRESS2 = N'' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_TSUMIKAE)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', TSUMIKAE_HOKANBA_NAME = N'しんげんば', TSUMIKAE_HOKANBA_ADDRESS1 = N'福岡市博多区下川端町２２２', TSUMIKAE_HOKANBA_ADDRESS2 = N'' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_TSUMIKAE)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'赤松運輸', TSUMIKAE_HOKANBA_NAME = N'赤松運輸', TSUMIKAE_HOKANBA_ADDRESS1 = N'つくば市栗原1-2-3', TSUMIKAE_HOKANBA_ADDRESS2 = N'' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_TSUMIKAE)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'赤松運輸', TSUMIKAE_HOKANBA_NAME = N'赤松運輸', TSUMIKAE_HOKANBA_ADDRESS1 = N'つくば市栗原1-2-3', TSUMIKAE_HOKANBA_ADDRESS2 = N'' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_TSUMIKAE)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', TSUMIKAE_HOKANBA_NAME = N'福岡営業所', TSUMIKAE_HOKANBA_ADDRESS1 = N'福岡市博多区下川端町２２２', TSUMIKAE_HOKANBA_ADDRESS2 = N'' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_TSUMIKAE)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', TSUMIKAE_HOKANBA_NAME = N'福岡営業所', TSUMIKAE_HOKANBA_ADDRESS1 = N'福岡市博多区下川端町２２２', TSUMIKAE_HOKANBA_ADDRESS2 = N'' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_TSUMIKAE)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', TSUMIKAE_HOKANBA_NAME = N'福岡営業所', TSUMIKAE_HOKANBA_ADDRESS1 = N'福岡市博多区下川端町２２２', TSUMIKAE_HOKANBA_ADDRESS2 = N'' WHERE rn = 8;

