-- UPDATE script for table M_ITAKU_KEIYAKU_KIHON_HST_GENBA (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 132

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'(仮称)筑波ビル建設工事　', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市春日4-4-4', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'筑波中学校耐震補強工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市北条2-2-2', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'ホームセンターオーナン改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市天久保9-9-9', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'住所２行目' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'横田様邸改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市泊崎1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'海野平団地E棟・F棟建設工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'土浦市東崎町2-3-4', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'大熊様邸リニューアル工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'牛久市中根町7-7-7', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'岡見団地住宅改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'牛久市岡見町5-6-7', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'ABCビル設備改修他工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'稲敷市信太古渡7-8-9', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'筑西落合4丁目賃貸計画', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'筑西市落合4-5-6', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'古河シティタワー補強工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'古河市静町6-7-8', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'ススキ療育センター', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市吾妻2-9', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'にじいろクリニック', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'土浦市下高津1-19', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'よつばこどもクリニック', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市小田2377‐1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'つくば総合病院', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'土浦市下高津2‐7‐14', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'まりも整形外科', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市小田2413', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'たんぽぽ耳鼻咽喉科', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'牛久市ひたち野西1-2-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'医療法人社団　みなみ病院', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'牛久市ひたち野西1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'がくえん診療所', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'土浦市中荒川沖町5-824-15', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'とまと動物病院', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市沼田579', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'さくら歯科医院', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくばみらい市台953-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'今井様邸改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市並木1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'アオゾラ保育園改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'土浦市川口9-9-9', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'カツラ第一工場改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'筑西市樋口1-2-3', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'オオイシ興業', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市泊崎383-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'オオイシ興業', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市泊崎383-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'竹園ビル改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市竹園1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'本田商事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'土浦市富士崎', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'川口様邸増築工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市上境1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'アサヒ製作所', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくばみらい市野堀529-3-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'阿良川工業豊田工場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'豊田市池田町', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'阿良川工業豊田工場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'豊田市池田町', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'筑波中学校耐震補強工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市北条2-2-2', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'阿良川工業豊田工場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'豊田市池田町', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'竹園ビル改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市竹園1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'イトウ建設', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市春日3-3-3', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'カミツ鉄鋼', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市自由ケ丘449-9', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'令和元年度23号線道徳高架橋橋梁補修②', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市中区錦3-3-3', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'イワモト食品㈱古河工場改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'古河市緑町9-8-7', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'現場契約　県外', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'令和元年度23号線道徳高架橋橋梁補修②', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市中区錦3-3-3', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'竹園ビル改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市竹園1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'浅沼土建', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'筑波中学校耐震補強工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市北条2-2-2', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'よつばこどもクリニック', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市小田2377‐1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'よつばこどもクリニック', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市小田2377‐1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'よつばこどもクリニック', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市小田2377‐1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'23号道徳高架橋橋梁補修工事‗令和元年その2', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市中区錦3-3-3', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'23号道徳高架橋橋梁補修工事‗令和元年その2', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市中区錦3-3-3', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'竹園ビル改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市竹園1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'深田製造㈱豊田第1工場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'豊田市大河原町1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'本田現場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'土浦市上高津', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'ヨークマート竹園店', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市東新井３１−１３', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'筑波中学校耐震補強工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市北条2-2-2', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'ホームセンターオーナン改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市天久保9-9-9', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'住所２行目' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'阿良川工業豊田工場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'豊田市池田町', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'阿良川工業豊田工場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'豊田市池田町', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'しんげんば', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'福岡市博多区下川端町２２２', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'土間', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市中村区名駅3-22-8', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'山形工業山形店舗', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'アオゾラ保育園改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'土浦市川口9-9-9', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'エジソン商事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市東新井13-31', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'イトウ建設', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市春日3-3-3', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 62;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'中部産業', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市中区三の丸1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 63;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'本田商事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'土浦市富士崎９９９', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 64;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'茨城町役場改修現場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'東茨城郡茨城町常井', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 65;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'茨城町小学校　解体現場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'東茨城郡茨城町桜の郷１－４－５', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 66;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'茨城町小学校　解体現場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'東茨城郡茨城町桜の郷１－４－５', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 67;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'田中建設Ａ現場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'千代田区皇居外苑1-11', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 68;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'竹園ビル改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市竹園1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 69;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'23号道令和元年その2', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市南区堤町1-67-4', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 70;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'１号線黄金陸橋交差点舗装工事 3期', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市中村区黄金通8-6', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 71;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'１号線黄金陸橋交差点舗装工事 3期', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市中村区黄金通8-6', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 72;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'○○工事（ベント用）', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市緑区太子1-182', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 73;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'23号道令和元年その2', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市南区堤町1-67-4', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 74;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'23号道令和元年その2', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市南区堤町1-67-4', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 75;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'23号道令和元年その2', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市南区堤町1-67-4', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 76;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'西園寺建設', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'稲敷市鳩崎1-2-3', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 77;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'深田製造豊田第2工場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'豊田市葛町1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 78;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'(仮称)つくば市香取台A１２地区', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市香取台A12', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 79;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'令和元年度23号鈴鹿舗装工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'鈴鹿市江島本町1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 80;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'山縣工務店', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市泊崎1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 81;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'中部産業 名古屋第一工場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市中区東桜1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 82;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'阿良川工業豊田工場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'愛知県名古屋市中区栄２丁目１７−１', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 83;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'〇〇解体工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'千代田区皇居外苑', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 84;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'金沢園芸第2作業所', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'千代田区皇居外苑', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 85;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'23号道令和元年その2', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市南区堤町1-67-4', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 86;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'１号線黄金陸橋交差点舗装工事 3期★', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市中村区黄金通8-6', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 87;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'名大山椒', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市中区三の丸', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 88;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'阿良川工業豊田工場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'愛知県名古屋市中区栄２丁目１７−１', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 89;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'(仮称)筑波ビル建設工事　', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市春日4-4-4', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 90;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'INXS商事　つくば事業所', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市梅園1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 91;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'竹園ビル改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市竹園1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 92;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'竹園ビル改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市竹園1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 93;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'竹園ビル改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市竹園1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 94;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'エジソン商事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市東新井13-31', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 95;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'〇〇解体工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'千代田区皇居外苑', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 96;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'テスト現場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'福岡市博多区美野島', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 97;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'エジソン商事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市東新井31-13', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 98;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'〇〇工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'千代田区皇居外苑', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 99;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'ミニマート稲岡店', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市稲岡793-15', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 100;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'エジソン商事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市東新井31-13', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 101;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'福本商店Ａ工場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'千代田区千代田', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 102;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'石岡駅南高架下補強工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'石岡市国府1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 103;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'井樋工業', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市竹園区1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 104;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'横田様邸改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市泊崎1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 105;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'エジソン商事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市東新井31-13', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 106;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'エジソン商事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市東新井31-13', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 107;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'竹園ビル改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市竹園1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 108;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'柴田物流　筑紫口', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'福岡市博多区博多駅前', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 109;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'竹園ビル改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市竹園1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 110;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'イトウ建設', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市春日3-3-3', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 111;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'竹園ビル改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市竹園1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 112;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'西日本物流 現場A', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'福岡市博多区博多駅前', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 113;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'今井様邸改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市並木1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 114;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'水戸中間処理場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'水戸市中央1-4-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 115;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'福岡営業所', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'福岡市博多区下川端町２２２', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 116;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'(仮称)筑波ビル建設工事　', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市春日4-4-4', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 117;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'今井様邸改修工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市並木1-1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 118;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'池田商店', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市東新井31-13', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 119;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'クロダ建設', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市並木4-44-4', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 120;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'free', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 121;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'野茂建設', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'福岡市博多区美野島', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 122;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'池下国際ビル', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市千種区池上1丁目1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 123;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'堀川工場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市伏見1丁目1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 124;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'エジソン商事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'つくば市東新井13-31', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 125;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'23号道令和元年その2', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市南区堤町1-67-4', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 126;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'今池大通り工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市千種区', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 127;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'水戸中間処理場', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'水戸市中央1-4-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 128;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'栄ビル工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'名古屋市中区錦1丁目1-1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 129;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'モバイル検証2024_現場略称', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'住所1住所1住所1住所1住所1住所1住所1住所1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'住所2住所2住所2住所2住所2住所2住所2住所2' WHERE rn = 130;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'モバイル検証2024_現場略称', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'住所1住所1住所1住所1住所1住所1住所1住所1', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'住所2住所2住所2住所2住所2住所2住所2住所2' WHERE rn = 131;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_KIHON_HST_GENBA)
UPDATE T SET HAISHUTSU_JIGYOUJOU_NAME = N'海野平団地E棟・F棟建設工事', HAISHUTSU_JIGYOUJOU_ADDRESS = NULL, HAISHUTSU_JIGYOUJOU_ADDRESS1 = N'土浦市東崎町2-3-4', HAISHUTSU_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 132;

