-- UPDATE script for table M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 176

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'伊東　史郎', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'三條　司', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'山形　アキラ', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'松方　仁', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = N'090-0000-0000', ATESAKI_NAME = N'松方建設　つくば支社', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'日野　浩太', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = N'090-0000-1111', ATESAKI_NAME = N'オオスミ工務店', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'浅田　三次', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'篠原真一', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = NULL, ATESAKI_NAME = N'にじいろクリニック　つくば受付', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'橋本　信也', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = N'090-0000-0000', ATESAKI_NAME = N'四葉グループ　東京本社', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'星野　公平', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = N'029-222-2222', ATESAKI_NAME = N'つくば総合病院', BUSHO_NAME = N'廃棄物管理課', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'森　和義', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = N'043-333-3333', ATESAKI_NAME = N'まりも整形外科', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'近藤　幸子', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = NULL, ATESAKI_NAME = N'たんぽぽ耳鼻咽喉科', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'南野　修', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = N'029-2222-2222', ATESAKI_NAME = N'みなみ病院', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'荒川沖　平蔵', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = NULL, ATESAKI_NAME = N'荒川沖院長自宅', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'沼照　良子', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = N'029-333-3333', ATESAKI_NAME = N'とまと病院', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'桜田　雅人', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = N'044-222-2222', ATESAKI_NAME = N'さくら歯科医院', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'伊東　広', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = N'090-3333-3333', ATESAKI_NAME = N'イトウグループ', BUSHO_NAME = N'マニフェスト管理部', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'黒田　正樹', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'松方　仁', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = N'090-0000-0000', ATESAKI_NAME = N'松方建設　つくば本社', BUSHO_NAME = NULL, CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'大石', MAIL_ADDRESS = N'arakawa@e-mall.co.jp', TEL_NO = NULL, ATESAKI_NAME = N'大石あて先名', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'大石', MAIL_ADDRESS = N'edison_arakawa@yahoo.co.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'2', SOUHU_TANTOUSHA_NAME = N'鈴木　次郎', MAIL_ADDRESS = N'shi-sato@e-mall.co.jp', TEL_NO = NULL, ATESAKI_NAME = N'エジソン商事株式会社', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'2', SOUHU_TANTOUSHA_NAME = N'佐藤　花子', MAIL_ADDRESS = N'hanako@e-mall.co.jj', TEL_NO = NULL, ATESAKI_NAME = N'エジソン商事株式会社', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'2', SOUHU_TANTOUSHA_NAME = N'西田　栄一', MAIL_ADDRESS = N'nishida@e-mall.co.jj', TEL_NO = NULL, ATESAKI_NAME = N'エジソン商事株式会社', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'2', SOUHU_TANTOUSHA_NAME = N'浅沼　啓太', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'1', SOUHU_TANTOUSHA_NAME = N'浅沼　啓太', MAIL_ADDRESS = N'asanuma@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = N'株式会社ＪＥＭＳ', BUSHO_NAME = N'将軍事業部営業課', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'浅沼　啓太', MAIL_ADDRESS = N'asanuma@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'1', SOUHU_TANTOUSHA_NAME = N'浅沼啓太', MAIL_ADDRESS = N'asanuma@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = N'あ' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'新川　拓哉', MAIL_ADDRESS = N'edison_arakawa@yahoo.co.jp', TEL_NO = NULL, ATESAKI_NAME = N'あいうえお', BUSHO_NAME = NULL, CREATE_USER = N'田中　五郎', UPDATE_USER = N'田中　五郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'荒川', MAIL_ADDRESS = N'arakawa@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'田中　五郎', UPDATE_USER = N'田中　五郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'浅沼　啓太', MAIL_ADDRESS = N'asanuma@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'浅沼　啓太', MAIL_ADDRESS = N'asanuma@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = N'★宛先あいうえお★', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'新川　拓哉', MAIL_ADDRESS = N'arakawa@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'あ', MAIL_ADDRESS = N'ediosn_arakawa@yahoo.co.jp', TEL_NO = NULL, ATESAKI_NAME = N'阿良川社長', BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'すぎやまさん', MAIL_ADDRESS = N'edison_arakawa@yahoo.co.jp', TEL_NO = NULL, ATESAKI_NAME = N'すぎやまさん', BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'浅沼　啓太', MAIL_ADDRESS = N'jemsasanuma@gmail.com', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'浅沼', MAIL_ADDRESS = N'jemsasanuma@gmail.com', TEL_NO = NULL, ATESAKI_NAME = N'★宛先名　株式会社ＪＥＭＳ★', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'はしもとさん', MAIL_ADDRESS = N'edison_arakawa@yahoo.co.jp', TEL_NO = NULL, ATESAKI_NAME = N'しんわかんきょうはしもとさん', BUSHO_NAME = NULL, CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'1', SOUHU_TANTOUSHA_NAME = N'浅沼　太郎', MAIL_ADDRESS = N'asanuma@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'浅沼　太郎', MAIL_ADDRESS = N'jemsasanuma@gmail.com', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'安田　彬', UPDATE_USER = N'安田　彬', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'横山', MAIL_ADDRESS = N'edisonjems@yahoo.co.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'横山', MAIL_ADDRESS = N'yokoyama@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = N'横山建設株式会社' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'浅沼', MAIL_ADDRESS = N'asanuma@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = N'★委託契約書', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'2', SOUHU_TANTOUSHA_NAME = N'鈴木　次郎', MAIL_ADDRESS = N'shi-sato@e-mall.co.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'2', SOUHU_TANTOUSHA_NAME = N'佐藤　花子', MAIL_ADDRESS = N'hanako@e-mall.co.jj', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'2', SOUHU_TANTOUSHA_NAME = N'西田　栄一', MAIL_ADDRESS = N'nishida@e-mall.co.jj', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 62;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'2', SOUHU_TANTOUSHA_NAME = N'本田哲也', MAIL_ADDRESS = N'goodjob17@yahoo.co.jp', TEL_NO = NULL, ATESAKI_NAME = N'本田哲也', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 63;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 64;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 65;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'3', SOUHU_TANTOUSHA_NAME = N'テスト太郎', MAIL_ADDRESS = N'hatakenaka@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 66;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'3', SOUHU_TANTOUSHA_NAME = N'畠中', MAIL_ADDRESS = N'kyoto.teraooi@ezweb.ne.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 67;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 68;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'3', SOUHU_TANTOUSHA_NAME = N'テスト太郎', MAIL_ADDRESS = N'hatakenaka@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = N'エジソン商事株式会社', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 69;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'3', SOUHU_TANTOUSHA_NAME = N'鈴木　次郎', MAIL_ADDRESS = N'shi-sato@e-mall.co.jp', TEL_NO = NULL, ATESAKI_NAME = N'エジソン商事株式会社', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 70;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'3', SOUHU_TANTOUSHA_NAME = N'畠中', MAIL_ADDRESS = N'kyoto.teraooi@ezweb.ne.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 71;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 72;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 73;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 74;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'鈴木　次郎', MAIL_ADDRESS = N'shi-sato@e-mall.co.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 75;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'西田　栄一', MAIL_ADDRESS = N'nishida@e-mall.co.jj', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 76;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'浅沼　啓太', MAIL_ADDRESS = N'asanuma@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = N'株式会社ＪＥＭＳ', BUSHO_NAME = N'将軍事業部', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 77;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 78;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'山形　アキラ', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = NULL, ATESAKI_NAME = N'山縣工務店　つくば事務所', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 79;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 80;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 81;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'4', SOUHU_TANTOUSHA_NAME = N'秋葉　太郎', MAIL_ADDRESS = N'yokoyama@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = N'エジソン商事株式会社', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 82;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'4', SOUHU_TANTOUSHA_NAME = N'横山', MAIL_ADDRESS = N'edisonjems@yahoo.co.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 83;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 84;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 85;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 86;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 87;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 88;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 89;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 90;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 91;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'荒川', MAIL_ADDRESS = N'arakawa@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = N'中部建設' WHERE rn = 92;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 93;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'本田哲也', MAIL_ADDRESS = N'aaa@aaaaaa.com', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = N'中部建設' WHERE rn = 94;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 95;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'後藤さん', MAIL_ADDRESS = N'edison_arakawa@yahoo.co.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = N'後藤工業' WHERE rn = 96;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'かきくけこ', MAIL_ADDRESS = N'arakawa@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = N'あいうえお' WHERE rn = 97;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 98;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 99;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'3', SOUHU_TANTOUSHA_NAME = N'テスト太郎', MAIL_ADDRESS = N'hatakenaka@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = N'エジソン商事株式会社', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 100;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'3', SOUHU_TANTOUSHA_NAME = N'鈴木　次郎', MAIL_ADDRESS = N'shi-sato@e-mall.co.jp', TEL_NO = NULL, ATESAKI_NAME = N'エジソン商事株式会社', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 101;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'3', SOUHU_TANTOUSHA_NAME = N'西園寺', MAIL_ADDRESS = N'arakawa@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = N'西園寺建設株式会社' WHERE rn = 102;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 103;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 104;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 105;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 106;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'1', SOUHU_TANTOUSHA_NAME = N'さとう　じろう', MAIL_ADDRESS = N'satou@gmail.com', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 107;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'1', SOUHU_TANTOUSHA_NAME = N'テムス　たろう', MAIL_ADDRESS = N'temusu@yahoo.co.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = N'テムス' WHERE rn = 108;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'3', SOUHU_TANTOUSHA_NAME = N'テスト太郎', MAIL_ADDRESS = N'hatakenaka@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = N'エジソン商事株式会社', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 109;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'3', SOUHU_TANTOUSHA_NAME = N'鈴木　次郎', MAIL_ADDRESS = N'kyoto.teraooi@ezweb.ne.jp', TEL_NO = NULL, ATESAKI_NAME = N'エジソン商事株式会社', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 110;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'3', SOUHU_TANTOUSHA_NAME = N'あいう　えお', MAIL_ADDRESS = N'hatakenaka@e-mall.co.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = N'あいう株式会社' WHERE rn = 111;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 112;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'7', SOUHU_TANTOUSHA_NAME = N'山田　太郎', MAIL_ADDRESS = N'mo-kusama@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = N'エジソン商事株式会社', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 113;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'7', SOUHU_TANTOUSHA_NAME = N'山縣　太郎', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = N'山縣工務店' WHERE rn = 114;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 115;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'アラカワ', MAIL_ADDRESS = N'arakawa@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = N'株式会社アラカワ' WHERE rn = 116;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 117;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 118;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'中部太郎', MAIL_ADDRESS = N'edison_arakawa@yahoo.co.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = N'株式会社中部建設' WHERE rn = 119;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'荒川卓也', MAIL_ADDRESS = N'edison_arakawa@yahoo.co.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一', KEIYAKUSAKI_CORP_NAME = N'株式会社荒川産業' WHERE rn = 120;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'ああ太郎', MAIL_ADDRESS = N'edison_arakawa@yahoo.co.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = N'ああああ' WHERE rn = 121;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'あらかわ', MAIL_ADDRESS = N'edison_arakawa@yahoo.co.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = N'株式会社阿良川興業' WHERE rn = 122;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'伊藤太郎', MAIL_ADDRESS = N'edison_arakawa@yahoo.co.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = N'株式会社イトウ建設' WHERE rn = 123;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 124;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 125;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 126;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 127;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 128;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 129;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 130;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 131;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'やまだ', UPDATE_USER = N'やまだ', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 132;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 133;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 134;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 135;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 136;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 137;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 138;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 139;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 140;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 141;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 142;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 143;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'1', SOUHU_TANTOUSHA_NAME = N'鈴木　次郎', MAIL_ADDRESS = N'kyoto.teraooi@ezweb.ne.jp', TEL_NO = NULL, ATESAKI_NAME = N'エジソン商事株式会社', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 144;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'1', SOUHU_TANTOUSHA_NAME = N'ｗｗｗｗ', MAIL_ADDRESS = N'morodomi@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = N'ｗｗｗ' WHERE rn = 145;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'のも', MAIL_ADDRESS = N'morodmoi@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = N'エジソン商事株式会社', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 146;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'野茂英雄', MAIL_ADDRESS = N'morodomi@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = N'ロス' WHERE rn = 147;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'1', SOUHU_TANTOUSHA_NAME = N'鈴木　次郎', MAIL_ADDRESS = N'kyoto.teraooi@ezweb.ne.jp', TEL_NO = NULL, ATESAKI_NAME = N'エジソン商事株式会社', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 148;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'1', SOUHU_TANTOUSHA_NAME = N'３', MAIL_ADDRESS = N'morodomi@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = N'２２２' WHERE rn = 149;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 150;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 151;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 152;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 153;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 154;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 155;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 156;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 157;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'1', SOUHU_TANTOUSHA_NAME = N'鈴木　次郎', MAIL_ADDRESS = N'kyoto.teraooi@ezweb.ne.jp', TEL_NO = NULL, ATESAKI_NAME = N'エジソン商事株式会社', BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 158;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'1', SOUHU_TANTOUSHA_NAME = N'契約締結男', MAIL_ADDRESS = N'hi-ikeda@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = N'テスト契約先' WHERE rn = 159;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 160;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 161;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 162;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'テスト　太郎', MAIL_ADDRESS = N'edisonjems@gmail.com', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = N'テスト１' WHERE rn = 163;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'7', SOUHU_TANTOUSHA_NAME = N'山田　太郎', MAIL_ADDRESS = N'mo-kusama@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = N'エジソン商事株式会社', BUSHO_NAME = NULL, CREATE_USER = N'やまだ', UPDATE_USER = N'やまだ', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 164;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = N'7', SOUHU_TANTOUSHA_NAME = N'諸富', MAIL_ADDRESS = N'morodomi@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'やまだ', UPDATE_USER = N'やまだ', KEIYAKUSAKI_CORP_NAME = N'テスト' WHERE rn = 165;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'山田太郎', MAIL_ADDRESS = N'edisonjems@yahoo.co.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = N'JEMS' WHERE rn = 166;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 167;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 168;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = N'ちゅうぶたろー', MAIL_ADDRESS = N'arakawa@j-ems.jp', TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', KEIYAKUSAKI_CORP_NAME = N'ちゅうぶけんせつ' WHERE rn = 169;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 170;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 171;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 172;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 173;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 174;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 175;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_DENSHI_SOUHUSAKI)
UPDATE T SET DENSHI_KEIYAKU_SHANAI_KEIRO_NAME_CD = NULL, SOUHU_TANTOUSHA_NAME = NULL, MAIL_ADDRESS = NULL, TEL_NO = NULL, ATESAKI_NAME = NULL, BUSHO_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', KEIYAKUSAKI_CORP_NAME = NULL WHERE rn = 176;

