-- UPDATE script for table M_ITAKU_KEIYAKU_BETSU3 (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 75

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'水戸工場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'水戸工場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　クリーンセンター', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　クリーンセンター', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　クリーンセンター', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　クリーンセンター', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　クリーンセンター', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　クリーンセンター', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　クリーンセンター', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　クリーンセンター', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　クリーンセンター', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　クリーンセンター', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　クリーンセンター', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　クリーンセンター', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31あ', SHOBUN_GYOUSHA_ADDRESS2 = N'住所２', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'笠間工場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'笠間市住吉23-1', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'笠間工場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'笠間市住吉23-1', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　クリーンセンター', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　ｸﾘｰﾝｾﾝﾀｰ', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31あ', SHOBUN_GYOUSHA_ADDRESS2 = N'住所２', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市中央1-4-1', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31あ', SHOBUN_GYOUSHA_ADDRESS2 = N'住所２', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市中央1-4-1', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　ｸﾘｰﾝｾﾝﾀｰ', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　ｸﾘｰﾝｾﾝﾀｰ', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　ｸﾘｰﾝｾﾝﾀｰ', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'若槻リサイクル', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'久喜市新井7-6-1', SHOBUN_GYOUSHA_ADDRESS2 = N'A-303', SHOBUN_JIGYOUJOU_NAME = N'若槻リサイクル　館山工場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'館山市亀ケ原4-12-3', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'つくば市東新井31-13', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　ｸﾘｰﾝｾﾝﾀｰ', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　ｸﾘｰﾝｾﾝﾀｰ', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 62;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　クリーンセンター', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 63;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　ｸﾘｰﾝｾﾝﾀｰ', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 64;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　クリーンセンター', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 65;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　ｸﾘｰﾝｾﾝﾀｰ', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 66;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市中央1-4-1', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 67;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 68;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'三日月クリーン開発', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'三日月クリーン開発　最終処分場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'宮若市鶴田355-9', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 69;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　クリーンセンター', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 70;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'エジソン商事　クリーンセンター', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市上水戸5-6-7', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 71;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市中央1-4-1', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 72;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市中央1-4-1', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 73;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'モバイル検証2024_業者略称', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'住所1住所1住所1住所1住所1住所1住所1住所1', SHOBUN_GYOUSHA_ADDRESS2 = N'住所2住所2住所2住所2住所2住所2住所2住所2', SHOBUN_JIGYOUJOU_NAME = N'モバイル検証2024_現場略称', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'住所1住所1住所1住所1住所1住所1住所1住所1', SHOBUN_JIGYOUJOU_ADDRESS2 = N'住所2住所2住所2住所2住所2住所2住所2住所2' WHERE rn = 74;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU3)
UPDATE T SET SHOBUN_GYOUSHA_NAME = N'エジソン商事', SHOBUN_GYOUSHA_ADDRESS = NULL, SHOBUN_GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', SHOBUN_GYOUSHA_ADDRESS2 = N'', SHOBUN_JIGYOUJOU_NAME = N'水戸中間処理場', SHOBUN_JIGYOUJOU_ADDRESS = NULL, SHOBUN_JIGYOUJOU_ADDRESS1 = N'水戸市中央1-4-1', SHOBUN_JIGYOUJOU_ADDRESS2 = N'' WHERE rn = 75;

