-- UPDATE script for table M_ITAKU_KEIYAKU_BETSU1_HST (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 256

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'がれき類' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'がれき類' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'がれき類' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'鉱さい' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'がれき類' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'がれき類' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'がれき類' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'がれき類' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'がれき類' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 62;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'がれき類' WHERE rn = 63;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃酸' WHERE rn = 64;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃アルカリ' WHERE rn = 65;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 66;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 67;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 68;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 69;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 70;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'感染性産業廃棄物' WHERE rn = 71;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃酸' WHERE rn = 72;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃アルカリ' WHERE rn = 73;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 74;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 75;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 76;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 77;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 78;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'感染性産業廃棄物' WHERE rn = 79;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃酸' WHERE rn = 80;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃アルカリ' WHERE rn = 81;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 82;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 83;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 84;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 85;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 86;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'感染性産業廃棄物' WHERE rn = 87;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃酸' WHERE rn = 88;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃アルカリ' WHERE rn = 89;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 90;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 91;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 92;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 93;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 94;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'感染性産業廃棄物' WHERE rn = 95;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃酸' WHERE rn = 96;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃アルカリ' WHERE rn = 97;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 98;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 99;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 100;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 101;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 102;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'感染性産業廃棄物' WHERE rn = 103;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃酸' WHERE rn = 104;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃アルカリ' WHERE rn = 105;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 106;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 107;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 108;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 109;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 110;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'感染性産業廃棄物' WHERE rn = 111;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃酸' WHERE rn = 112;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃アルカリ' WHERE rn = 113;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 114;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 115;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 116;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 117;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 118;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'感染性産業廃棄物' WHERE rn = 119;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃酸' WHERE rn = 120;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃アルカリ' WHERE rn = 121;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 122;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 123;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 124;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 125;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 126;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'感染性産業廃棄物' WHERE rn = 127;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃酸' WHERE rn = 128;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃アルカリ' WHERE rn = 129;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 130;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 131;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 132;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 133;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 134;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'感染性産業廃棄物' WHERE rn = 135;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃酸' WHERE rn = 136;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃アルカリ' WHERE rn = 137;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 138;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 139;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 140;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 141;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 142;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'感染性産業廃棄物' WHERE rn = 143;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 144;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 145;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 146;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 147;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 148;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 149;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'がれき類' WHERE rn = 150;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 151;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 152;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 153;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 154;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 155;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 156;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'がれき類' WHERE rn = 157;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 158;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 159;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 160;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 161;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 162;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 163;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'がれき類' WHERE rn = 164;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 165;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 166;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 167;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'燃え殻' WHERE rn = 168;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 169;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 170;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'燃え殻' WHERE rn = 171;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'燃え殻' WHERE rn = 172;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 173;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 174;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 175;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 176;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 177;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 178;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 179;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 180;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃アルカリ' WHERE rn = 181;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'燃え殻' WHERE rn = 182;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 183;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 184;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 185;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'感染性産業廃棄物' WHERE rn = 186;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 187;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 188;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 189;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 190;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 191;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 192;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 193;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 194;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃アルカリ' WHERE rn = 195;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 196;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 197;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 198;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 199;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 200;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 201;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 202;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'がれき類' WHERE rn = 203;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 204;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 205;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 206;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 207;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 208;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 209;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'燃え殻' WHERE rn = 210;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 211;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 212;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 213;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラスくず・コンクリ' WHERE rn = 214;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'ガラス・陶磁器くず' WHERE rn = 215;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 216;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'燃え殻' WHERE rn = 217;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 218;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 219;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃酸' WHERE rn = 220;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 221;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 222;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 223;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 224;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 225;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 226;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃油' WHERE rn = 227;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'燃え殻' WHERE rn = 228;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 229;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'繊維くず' WHERE rn = 230;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'燃え殻' WHERE rn = 231;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'汚泥' WHERE rn = 232;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃油' WHERE rn = 233;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 234;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'がれき類' WHERE rn = 235;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'金属くず' WHERE rn = 236;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'汚泥' WHERE rn = 237;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'燃え殻' WHERE rn = 238;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'汚泥' WHERE rn = 239;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'燃え殻' WHERE rn = 240;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 241;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃アルカリ' WHERE rn = 242;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'木くず' WHERE rn = 243;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'紙くず' WHERE rn = 244;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'汚泥' WHERE rn = 245;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 246;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 247;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 248;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 249;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 250;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 251;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'燃え殻' WHERE rn = 252;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'汚泥' WHERE rn = 253;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃油' WHERE rn = 254;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'廃プラスチック' WHERE rn = 255;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ITAKU_KEIYAKU_BETSU1_HST)
UPDATE T SET HOUKOKUSHO_BUNRUI_NAME = N'燃え殻' WHERE rn = 256;

