-- UPDATE script for table M_JISSEKI_BUNRUI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 10

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JISSEKI_BUNRUI)
UPDATE T SET JISSEKI_BUNRUI_NAME = N'可燃ごみ', JISSEKI_BUNRUI_NAME_RYAKU = N'可燃ごみ', JISSEKI_BUNRUI_FURIGANA = N'カネンゴミ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JISSEKI_BUNRUI)
UPDATE T SET JISSEKI_BUNRUI_NAME = N'厨芥', JISSEKI_BUNRUI_NAME_RYAKU = N'厨芥', JISSEKI_BUNRUI_FURIGANA = N'チュウカイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JISSEKI_BUNRUI)
UPDATE T SET JISSEKI_BUNRUI_NAME = N'紙くず', JISSEKI_BUNRUI_NAME_RYAKU = N'紙くず', JISSEKI_BUNRUI_FURIGANA = N'カミクズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JISSEKI_BUNRUI)
UPDATE T SET JISSEKI_BUNRUI_NAME = N'弁当ガラ', JISSEKI_BUNRUI_NAME_RYAKU = N'弁当ガラ', JISSEKI_BUNRUI_FURIGANA = N'ベントウガラ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JISSEKI_BUNRUI)
UPDATE T SET JISSEKI_BUNRUI_NAME = N'繊維くず', JISSEKI_BUNRUI_NAME_RYAKU = N'繊維くず', JISSEKI_BUNRUI_FURIGANA = N'センイクズ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JISSEKI_BUNRUI)
UPDATE T SET JISSEKI_BUNRUI_NAME = N'廃プラスチック', JISSEKI_BUNRUI_NAME_RYAKU = N'廃プラスチック', JISSEKI_BUNRUI_FURIGANA = N'ハイプラスチック', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JISSEKI_BUNRUI)
UPDATE T SET JISSEKI_BUNRUI_NAME = N'ダンボール', JISSEKI_BUNRUI_NAME_RYAKU = N'ダンボール', JISSEKI_BUNRUI_FURIGANA = N'ダンボール', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JISSEKI_BUNRUI)
UPDATE T SET JISSEKI_BUNRUI_NAME = N'ペットボトル', JISSEKI_BUNRUI_NAME_RYAKU = N'ペットボトル', JISSEKI_BUNRUI_FURIGANA = N'ペットボトル', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JISSEKI_BUNRUI)
UPDATE T SET JISSEKI_BUNRUI_NAME = N'機密書類', JISSEKI_BUNRUI_NAME_RYAKU = N'機密書類', JISSEKI_BUNRUI_FURIGANA = N'キミツショルイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JISSEKI_BUNRUI)
UPDATE T SET JISSEKI_BUNRUI_NAME = N'不燃', JISSEKI_BUNRUI_NAME_RYAKU = N'不燃', JISSEKI_BUNRUI_FURIGANA = N'フネン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

