-- UPDATE script for table M_JW_NOTIFICATION (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 62

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_JW_NOTIFICATION)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 62;

