-- UPDATE script for table M_KAISHI_ZAIKO_INFO (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 22

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'銅線', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'一斗缶', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'再生紙', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'紙おむつ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'紙おむつ（在庫）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'ＨＳ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'ステンレス屑', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'鉄（テスト用）3', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'ＨＳ', CREATE_USER = N'中西　大樹', UPDATE_USER = N'鈴木　次郎' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'Ｈ１', CREATE_USER = N'中西　大樹', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'Ｈ２', CREATE_USER = N'中西　大樹', UPDATE_USER = N'鈴木　次郎' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'Ｈ３', CREATE_USER = N'中西　大樹', UPDATE_USER = N'鈴木　次郎' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'雑線', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'ステンレス屑', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'アルミ屑', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'雑品', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'配電盤', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'モーター', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'エアコン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'ギロ材Ａ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'ギロ材Ｂ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KAISHI_ZAIKO_INFO)
UPDATE T SET ZAIKO_HINMEI_NAME_RYAKU = N'ダンボール', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 22;

