-- UPDATE script for table M_KEIJOU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 4

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEIJOU)
UPDATE T SET KEIJOU_NAME = N'固形状', KEIJOU_NAME_RYAKU = N'固形状', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEIJOU)
UPDATE T SET KEIJOU_NAME = N'泥状', KEIJOU_NAME_RYAKU = N'泥状', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEIJOU)
UPDATE T SET KEIJOU_NAME = N'液状', KEIJOU_NAME_RYAKU = N'液状', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEIJOU)
UPDATE T SET KEIJOU_NAME = N'液状（テスト）', KEIJOU_NAME_RYAKU = N'液状（テスト）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

