-- UPDATE script for table M_KEITAI_KBN (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 17

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEITAI_KBN)
UPDATE T SET KEITAI_KBN_NAME = N'収集現金', KEITAI_KBN_NAME_RYAKU = N'収集現金', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEITAI_KBN)
UPDATE T SET KEITAI_KBN_NAME = N'収集売掛', KEITAI_KBN_NAME_RYAKU = N'収集売掛', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEITAI_KBN)
UPDATE T SET KEITAI_KBN_NAME = N'持込現金', KEITAI_KBN_NAME_RYAKU = N'持込現金', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEITAI_KBN)
UPDATE T SET KEITAI_KBN_NAME = N'持込売掛', KEITAI_KBN_NAME_RYAKU = N'持込売掛', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEITAI_KBN)
UPDATE T SET KEITAI_KBN_NAME = N'受入持込', KEITAI_KBN_NAME_RYAKU = N'受入持込', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEITAI_KBN)
UPDATE T SET KEITAI_KBN_NAME = N'受入収集', KEITAI_KBN_NAME_RYAKU = N'受入収集', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEITAI_KBN)
UPDATE T SET KEITAI_KBN_NAME = N'出荷引取', KEITAI_KBN_NAME_RYAKU = N'出荷引取', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEITAI_KBN)
UPDATE T SET KEITAI_KBN_NAME = N'出荷配達', KEITAI_KBN_NAME_RYAKU = N'出荷配達', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'佐藤　花子' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEITAI_KBN)
UPDATE T SET KEITAI_KBN_NAME = N'有価出荷', KEITAI_KBN_NAME_RYAKU = N'有価出荷', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEITAI_KBN)
UPDATE T SET KEITAI_KBN_NAME = N'産廃出荷', KEITAI_KBN_NAME_RYAKU = N'産廃出荷', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEITAI_KBN)
UPDATE T SET KEITAI_KBN_NAME = N'工場渡し', KEITAI_KBN_NAME_RYAKU = N'工場渡し', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEITAI_KBN)
UPDATE T SET KEITAI_KBN_NAME = N'配達', KEITAI_KBN_NAME_RYAKU = N'配達', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEITAI_KBN)
UPDATE T SET KEITAI_KBN_NAME = N'持込買掛', KEITAI_KBN_NAME_RYAKU = N'持込買掛', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEITAI_KBN)
UPDATE T SET KEITAI_KBN_NAME = N'仕入持込', KEITAI_KBN_NAME_RYAKU = N'仕入持込', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEITAI_KBN)
UPDATE T SET KEITAI_KBN_NAME = N'仕入引取', KEITAI_KBN_NAME_RYAKU = N'仕入引取', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEITAI_KBN)
UPDATE T SET KEITAI_KBN_NAME = N'仕入代納', KEITAI_KBN_NAME_RYAKU = N'仕入代納', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEITAI_KBN)
UPDATE T SET KEITAI_KBN_NAME = N'社内移動', KEITAI_KBN_NAME_RYAKU = N'社内移動', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 17;

