-- UPDATE script for table M_KEIRYOU_CARD (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 2

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEIRYOU_CARD)
UPDATE T SET CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KEIRYOU_CARD)
UPDATE T SET CREATE_USER = N'やまだ', UPDATE_USER = N'やまだ' WHERE rn = 2;

