-- UPDATE script for table M_KONGOU_SHURUI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 25

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'スプレー缶', KONGOU_SHURUI_NAME_RYAKU = N'スプレー缶', KONGOU_SHURUI_FURIGANA = N'スプレーカン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'○○用こんぱい', KONGOU_SHURUI_NAME_RYAKU = N'○○用こんぱい', KONGOU_SHURUI_FURIGANA = N'マルマルマルマルヨウコンパイ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'ああ用こんぱい', KONGOU_SHURUI_NAME_RYAKU = N'ああ用こんぱい', KONGOU_SHURUI_FURIGANA = N'アアヨウコンパイ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'デモ用混合産廃', KONGOU_SHURUI_NAME_RYAKU = N'デモ用混合産廃', KONGOU_SHURUI_FURIGANA = N'デモヨウコンゴウサンパイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'廃プラ振り分け', KONGOU_SHURUI_NAME_RYAKU = N'廃プラ振り分け', KONGOU_SHURUI_FURIGANA = N'ハイプラフリワケ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'一般木造建築住宅廃材', KONGOU_SHURUI_NAME_RYAKU = N'一般木造建築住宅廃材', KONGOU_SHURUI_FURIGANA = N'イッパンモクゾウケンチクジュウタクハイ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'デモ混廃産廃', KONGOU_SHURUI_NAME_RYAKU = N'混廃産廃', KONGOU_SHURUI_FURIGANA = N'デモデモンストレーションコンパイサンパイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'デモ用混廃(産廃)', KONGOU_SHURUI_NAME_RYAKU = N'デモ用混廃(産廃)', KONGOU_SHURUI_FURIGANA = N'デモヨウコンゴウサンパイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'管理型混合', KONGOU_SHURUI_NAME_RYAKU = N'管理型混合', KONGOU_SHURUI_FURIGANA = N'カンリガコンゴウガタコンゴウコンゴウ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'テスト', KONGOU_SHURUI_NAME_RYAKU = N'テスト', KONGOU_SHURUI_FURIGANA = N'テスト', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'自動販売機A', KONGOU_SHURUI_NAME_RYAKU = N'自動販売機A', KONGOU_SHURUI_FURIGANA = N'ジドウハンバイキＡ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'今池', KONGOU_SHURUI_NAME_RYAKU = N'今池', KONGOU_SHURUI_FURIGANA = N'イマイケ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'えええええええ', KONGOU_SHURUI_NAME_RYAKU = N'えええええええ', KONGOU_SHURUI_FURIGANA = N'エエエエエエエ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'ｑｑｑｑｑｑｑｑｑｑｑｑｑｑｑｑｑｑ', KONGOU_SHURUI_NAME_RYAKU = N'ｑｑｑｑｑｑｑｑｑｑ', KONGOU_SHURUI_FURIGANA = N'ｑｑｑｑｑｑｑｑｑｑｑｑｑｑｑｑｑｑ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'混廃A', KONGOU_SHURUI_NAME_RYAKU = N'混廃A', KONGOU_SHURUI_FURIGANA = N'コンゴウＡコンパイＡコンゴウハイキブツＡ', CREATE_USER = N'田中　五郎', UPDATE_USER = N'佐藤　花子' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'木造解体混合', KONGOU_SHURUI_NAME_RYAKU = N'木造解体混合', KONGOU_SHURUI_FURIGANA = N'コンゴウモクゾウカイタイコウンゴウカイタ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'内装系混合', KONGOU_SHURUI_NAME_RYAKU = N'内装系混合', KONGOU_SHURUI_FURIGANA = N'ナイソウカイケイコンゴウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'片付系混合', KONGOU_SHURUI_NAME_RYAKU = N'片付系混合', KONGOU_SHURUI_FURIGANA = N'カタヅケケイコンゴウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'デモ用混廃(建廃)', KONGOU_SHURUI_NAME_RYAKU = N'デモ用混廃(建廃)', KONGOU_SHURUI_FURIGANA = N'デモヨウコンパイケンパイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'機材センター用', KONGOU_SHURUI_NAME_RYAKU = N'機材センター用', KONGOU_SHURUI_FURIGANA = N'キザイセンターヨウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'リフォーム混合', KONGOU_SHURUI_NAME_RYAKU = N'リフォーム混合', KONGOU_SHURUI_FURIGANA = N'リフォームコンゴウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'今池建設混廃X', KONGOU_SHURUI_NAME_RYAKU = N'今池建設混廃X', KONGOU_SHURUI_FURIGANA = N'コンパイＸイマイケケンセツコンパイＸ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'ノートＰＣ‗Ａ', KONGOU_SHURUI_NAME_RYAKU = N'ノートＰＣ‗Ａ', KONGOU_SHURUI_FURIGANA = N'ノートＰＣＡ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'廃棄プリンタ', KONGOU_SHURUI_NAME_RYAKU = N'廃棄プリンタ', KONGOU_SHURUI_FURIGANA = N'プリンタハイキ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KONGOU_SHURUI)
UPDATE T SET KONGOU_SHURUI_NAME = N'ノートＰＣ‗Ｂ', KONGOU_SHURUI_NAME_RYAKU = N'ノートＰＣ‗Ｂ', KONGOU_SHURUI_FURIGANA = N'ノートＰＣＢ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 25;

