-- UPDATE script for table M_KOBETSU_HINMEI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 28

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'クロス８８８８８', CREATE_USER = N'やまだ', UPDATE_USER = N'やまだ' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'１１１', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'クロスC', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'紙D', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'廃プラ１', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'クロス２２２', CREATE_USER = N'やまだ', UPDATE_USER = N'やまだ' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'廃プラ０００１', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'請求品名用段ボール', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'廃プラスチックA　処分費', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'運搬費　交換', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'コンテナ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'HHH1', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'廃プＡＢＣＤ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'汚泥（田中）', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'廃プラスチック処理費　', CREATE_USER = N'沢口　賢治', UPDATE_USER = N'沢口　賢治' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'電特Ａ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'特Ａ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'特級', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'１級', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'一般廃棄物収集運搬★★', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'可燃物収集・処分料　', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'木くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'木くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'生木', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'金属くず', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'木皮', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'廃プラスチック処理費用', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KOBETSU_HINMEI)
UPDATE T SET SEIKYUU_HINMEI_NAME = N'紙屑', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 28;

