-- UPDATE script for table M_KYOTEN (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 9

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KYOTEN)
UPDATE T SET KYOTEN_NAME = N'本社', KYOTEN_NAME_RYAKU = N'本社', KYOTEN_FURIGANA = N'ホンシャ', KYOTEN_POST = N'305-0033', KYOTEN_ADDRESS1 = N'茨城県つくば市東新井31-13', KYOTEN_ADDRESS2 = N'', KYOTEN_TEL = N'029-863-7215', KYOTEN_FAX = N'029-863-7216', CREATE_USER = N'edison', UPDATE_USER = N'西田　栄一' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KYOTEN)
UPDATE T SET KYOTEN_NAME = N'リサイクルセンター', KYOTEN_NAME_RYAKU = N'リサイクル', KYOTEN_FURIGANA = N'リサイクルセンター', KYOTEN_POST = N'305-0001', KYOTEN_ADDRESS1 = N'茨城県つくば市吾妻', KYOTEN_ADDRESS2 = N'', KYOTEN_TEL = N'029-111-2222', KYOTEN_FAX = N'029-111-2223', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KYOTEN)
UPDATE T SET KYOTEN_NAME = N'タイヤ事業部', KYOTEN_NAME_RYAKU = N'タイヤ事業', KYOTEN_FURIGANA = N'タイヤジギョウブ', KYOTEN_POST = N'812-0017', KYOTEN_ADDRESS1 = N'じゅうしょ１－１－１', KYOTEN_ADDRESS2 = N'', KYOTEN_TEL = N'9999999', KYOTEN_FAX = N'8888888', CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KYOTEN)
UPDATE T SET KYOTEN_NAME = N'つくば支店', KYOTEN_NAME_RYAKU = N'つくば支店', KYOTEN_FURIGANA = N'ツクバシテン', KYOTEN_POST = N'305-0033', KYOTEN_ADDRESS1 = N'茨城県つくば市竹園1-1-1', KYOTEN_ADDRESS2 = N'', KYOTEN_TEL = N'', KYOTEN_FAX = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KYOTEN)
UPDATE T SET KYOTEN_NAME = N'福岡支店', KYOTEN_NAME_RYAKU = N'福岡支店', KYOTEN_FURIGANA = N'フクオカシテン', KYOTEN_POST = N'812-0011', KYOTEN_ADDRESS1 = N'福岡県福岡市博多区博多駅前', KYOTEN_ADDRESS2 = N'', KYOTEN_TEL = N'092-0000-0000', KYOTEN_FAX = N'092-1111-1111', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KYOTEN)
UPDATE T SET KYOTEN_NAME = N'本社', KYOTEN_NAME_RYAKU = N'本社', KYOTEN_FURIGANA = N'ホンシャ', KYOTEN_POST = N'305-0033', KYOTEN_ADDRESS1 = N'茨城県つくば市東新井31-13', KYOTEN_ADDRESS2 = N'', KYOTEN_TEL = N'029-863-7215', KYOTEN_FAX = N'029-863-7216', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KYOTEN)
UPDATE T SET KYOTEN_NAME = N'東ヤード', KYOTEN_NAME_RYAKU = N'東ヤード', KYOTEN_FURIGANA = N'ヒガシヤード', KYOTEN_POST = N'300-0101', KYOTEN_ADDRESS1 = N'茨城県つくば市の東', KYOTEN_ADDRESS2 = N'', KYOTEN_TEL = N'', KYOTEN_FAX = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KYOTEN)
UPDATE T SET KYOTEN_NAME = N'西ヤード', KYOTEN_NAME_RYAKU = N'西ヤード', KYOTEN_FURIGANA = N'ニシヤード', KYOTEN_POST = N'300-0202', KYOTEN_ADDRESS1 = N'茨城県つくば市の西', KYOTEN_ADDRESS2 = N'', KYOTEN_TEL = N'', KYOTEN_FAX = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_KYOTEN)
UPDATE T SET KYOTEN_NAME = N'全社', KYOTEN_NAME_RYAKU = N'全社', KYOTEN_FURIGANA = N'ゼンシャ', KYOTEN_POST = N'', KYOTEN_ADDRESS1 = N'あああ', KYOTEN_ADDRESS2 = N'', KYOTEN_TEL = N'123', KYOTEN_FAX = N'123', CREATE_USER = N'edison', UPDATE_USER = N'新川　拓哉' WHERE rn = 9;

