-- UPDATE script for table M_LYNA_CLOUD_YUURYOUDOURO_SYASHU_KBN (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 5

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_LYNA_CLOUD_YUURYOUDOURO_SYASHU_KBN)
UPDATE T SET YUURYOU_DOURO_SHASHU_KBN_NAME = N'普通', CREATE_USER = N'jems', UPDATE_USER = N'jems' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_LYNA_CLOUD_YUURYOUDOURO_SYASHU_KBN)
UPDATE T SET YUURYOU_DOURO_SHASHU_KBN_NAME = N'大型', CREATE_USER = N'jems', UPDATE_USER = N'jems' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_LYNA_CLOUD_YUURYOUDOURO_SYASHU_KBN)
UPDATE T SET YUURYOU_DOURO_SHASHU_KBN_NAME = N'特大', CREATE_USER = N'jems', UPDATE_USER = N'jems' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_LYNA_CLOUD_YUURYOUDOURO_SYASHU_KBN)
UPDATE T SET YUURYOU_DOURO_SHASHU_KBN_NAME = N'中型', CREATE_USER = N'jems', UPDATE_USER = N'jems' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_LYNA_CLOUD_YUURYOUDOURO_SYASHU_KBN)
UPDATE T SET YUURYOU_DOURO_SHASHU_KBN_NAME = N'軽', CREATE_USER = N'jems', UPDATE_USER = N'jems' WHERE rn = 5;

