-- UPDATE script for table M_LYNA_CLOUD_GENBA (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 7

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_LYNA_CLOUD_GENBA)
UPDATE T SET GROUP_NAME1 = NULL, GROUP_NAME2 = NULL, GROUP_NAME3 = NULL, GROUP_NAME4 = NULL, GROUP_NAME5 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_LYNA_CLOUD_GENBA)
UPDATE T SET GROUP_NAME1 = NULL, GROUP_NAME2 = NULL, GROUP_NAME3 = NULL, GROUP_NAME4 = NULL, GROUP_NAME5 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_LYNA_CLOUD_GENBA)
UPDATE T SET GROUP_NAME1 = NULL, GROUP_NAME2 = NULL, GROUP_NAME3 = NULL, GROUP_NAME4 = NULL, GROUP_NAME5 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_LYNA_CLOUD_GENBA)
UPDATE T SET GROUP_NAME1 = NULL, GROUP_NAME2 = NULL, GROUP_NAME3 = NULL, GROUP_NAME4 = NULL, GROUP_NAME5 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_LYNA_CLOUD_GENBA)
UPDATE T SET GROUP_NAME1 = NULL, GROUP_NAME2 = NULL, GROUP_NAME3 = NULL, GROUP_NAME4 = NULL, GROUP_NAME5 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_LYNA_CLOUD_GENBA)
UPDATE T SET GROUP_NAME1 = NULL, GROUP_NAME2 = NULL, GROUP_NAME3 = NULL, GROUP_NAME4 = NULL, GROUP_NAME5 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_LYNA_CLOUD_GENBA)
UPDATE T SET GROUP_NAME1 = NULL, GROUP_NAME2 = NULL, GROUP_NAME3 = NULL, GROUP_NAME4 = NULL, GROUP_NAME5 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

