-- UPDATE script for table M_MANIFEST_SHURUI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 3

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MANIFEST_SHURUI)
UPDATE T SET MANIFEST_SHURUI_NAME = N'紙', MANIFEST_SHURUI_NAME_RYAKU = N'紙', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MANIFEST_SHURUI)
UPDATE T SET MANIFEST_SHURUI_NAME = N'電子', MANIFEST_SHURUI_NAME_RYAKU = N'電子', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MANIFEST_SHURUI)
UPDATE T SET MANIFEST_SHURUI_NAME = N'無', MANIFEST_SHURUI_NAME_RYAKU = N'無', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

