-- UPDATE script for table M_MANIFEST_TEHAI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 3

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MANIFEST_TEHAI)
UPDATE T SET MANIFEST_TEHAI_NAME = N'閾ｪ遉ｾ謇矩・', MANIFEST_TEHAI_NAME_RYAKU = N'閾ｪ遉ｾ謇矩・', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MANIFEST_TEHAI)
UPDATE T SET MANIFEST_TEHAI_NAME = N'莉也､ｾ謇矩・', MANIFEST_TEHAI_NAME_RYAKU = N'莉也､ｾ謇矩・', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MANIFEST_TEHAI)
UPDATE T SET MANIFEST_TEHAI_NAME = N'辟｡', MANIFEST_TEHAI_NAME_RYAKU = N'辟｡', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

