-- UPDATE script for table M_MY_FAVORITE (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 61

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'沢口　賢治', UPDATE_USER = N'沢口　賢治' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'沢口　賢治', UPDATE_USER = N'沢口　賢治' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'沢口　賢治', UPDATE_USER = N'沢口　賢治' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'沢口　賢治', UPDATE_USER = N'沢口　賢治' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'安田　彬', UPDATE_USER = N'安田　彬' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'安田　彬', UPDATE_USER = N'安田　彬' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'安田　彬', UPDATE_USER = N'安田　彬' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'安田　彬', UPDATE_USER = N'安田　彬' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'大野　哲夫', UPDATE_USER = N'大野　哲夫' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'大野　哲夫', UPDATE_USER = N'大野　哲夫' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'大野　哲夫', UPDATE_USER = N'大野　哲夫' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'坂本　琢磨', UPDATE_USER = N'坂本　琢磨' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'坂本　琢磨', UPDATE_USER = N'坂本　琢磨' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'坂本　琢磨', UPDATE_USER = N'坂本　琢磨' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'野口　秀吉', UPDATE_USER = N'野口　秀吉' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'野口　秀吉', UPDATE_USER = N'野口　秀吉' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'野口　秀吉', UPDATE_USER = N'野口　秀吉' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'髙橋　智', UPDATE_USER = N'髙橋　智' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'髙橋　智', UPDATE_USER = N'髙橋　智' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'髙橋　智', UPDATE_USER = N'髙橋　智' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'岡田　益男', UPDATE_USER = N'岡田　益男' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'岡田　益男', UPDATE_USER = N'岡田　益男' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'岡田　益男', UPDATE_USER = N'岡田　益男' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'田中　五郎', UPDATE_USER = N'田中　五郎' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'田中　五郎', UPDATE_USER = N'田中　五郎' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'田中　五郎', UPDATE_USER = N'田中　五郎' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'田中　五郎', UPDATE_USER = N'田中　五郎' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'田中　五郎', UPDATE_USER = N'田中　五郎' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'田中　五郎', UPDATE_USER = N'田中　五郎' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_MY_FAVORITE)
UPDATE T SET CREATE_USER = N'田中　五郎', UPDATE_USER = N'田中　五郎' WHERE rn = 61;

