-- UPDATE script for table M_NISUGATA (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 10

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NISUGATA)
UPDATE T SET NISUGATA_NAME = N'バラ', NISUGATA_NAME_RYAKU = N'バラ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NISUGATA)
UPDATE T SET NISUGATA_NAME = N'コンテナ', NISUGATA_NAME_RYAKU = N'コンテナ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NISUGATA)
UPDATE T SET NISUGATA_NAME = N'ドラム缶', NISUGATA_NAME_RYAKU = N'ドラム缶', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NISUGATA)
UPDATE T SET NISUGATA_NAME = N'石油缶', NISUGATA_NAME_RYAKU = N'石油缶', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NISUGATA)
UPDATE T SET NISUGATA_NAME = N'プラスチック容器', NISUGATA_NAME_RYAKU = N'プラスチック容器', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NISUGATA)
UPDATE T SET NISUGATA_NAME = N'袋', NISUGATA_NAME_RYAKU = N'袋', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NISUGATA)
UPDATE T SET NISUGATA_NAME = N'フレコンバック', NISUGATA_NAME_RYAKU = N'フレコンバック', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NISUGATA)
UPDATE T SET NISUGATA_NAME = N'段ボール箱', NISUGATA_NAME_RYAKU = N'段ボール箱', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NISUGATA)
UPDATE T SET NISUGATA_NAME = N'その他', NISUGATA_NAME_RYAKU = N'その他', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NISUGATA)
UPDATE T SET NISUGATA_NAME = N'缶', NISUGATA_NAME_RYAKU = N'缶', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

