-- UPDATE script for table M_NYUUSHUKKIN_KBN (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 13

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUUSHUKKIN_KBN)
UPDATE T SET NYUUSHUKKIN_KBN_NAME = N'現金', NYUUSHUKKIN_KBN_NAME_RYAKU = N'現金', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUUSHUKKIN_KBN)
UPDATE T SET NYUUSHUKKIN_KBN_NAME = N'振込', NYUUSHUKKIN_KBN_NAME_RYAKU = N'振込', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUUSHUKKIN_KBN)
UPDATE T SET NYUUSHUKKIN_KBN_NAME = N'手形', NYUUSHUKKIN_KBN_NAME_RYAKU = N'手形', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUUSHUKKIN_KBN)
UPDATE T SET NYUUSHUKKIN_KBN_NAME = N'自動振替', NYUUSHUKKIN_KBN_NAME_RYAKU = N'自動振替', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUUSHUKKIN_KBN)
UPDATE T SET NYUUSHUKKIN_KBN_NAME = N'代引', NYUUSHUKKIN_KBN_NAME_RYAKU = N'代引', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUUSHUKKIN_KBN)
UPDATE T SET NYUUSHUKKIN_KBN_NAME = N'手形（半金半手）', NYUUSHUKKIN_KBN_NAME_RYAKU = N'手形（半金半手）', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUUSHUKKIN_KBN)
UPDATE T SET NYUUSHUKKIN_KBN_NAME = N'前受金', NYUUSHUKKIN_KBN_NAME_RYAKU = N'前受金', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUUSHUKKIN_KBN)
UPDATE T SET NYUUSHUKKIN_KBN_NAME = N'ぺいぺい', NYUUSHUKKIN_KBN_NAME_RYAKU = N'ぺいぺい', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUUSHUKKIN_KBN)
UPDATE T SET NYUUSHUKKIN_KBN_NAME = N'手数料', NYUUSHUKKIN_KBN_NAME_RYAKU = N'手数料', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUUSHUKKIN_KBN)
UPDATE T SET NYUUSHUKKIN_KBN_NAME = N'相殺', NYUUSHUKKIN_KBN_NAME_RYAKU = N'相殺', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUUSHUKKIN_KBN)
UPDATE T SET NYUUSHUKKIN_KBN_NAME = N'値引き', NYUUSHUKKIN_KBN_NAME_RYAKU = N'値引き', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUUSHUKKIN_KBN)
UPDATE T SET NYUUSHUKKIN_KBN_NAME = N'返金', NYUUSHUKKIN_KBN_NAME_RYAKU = N'返金', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUUSHUKKIN_KBN)
UPDATE T SET NYUUSHUKKIN_KBN_NAME = N'仮受金', NYUUSHUKKIN_KBN_NAME_RYAKU = N'仮受金', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 13;

