-- UPDATE script for table M_NYUURYOKU_TANTOUSHA (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 22

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = N'', CREATE_USER = N'初回ログイン用', UPDATE_USER = N'初回ログイン用' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = N'', CREATE_USER = N'初回ログイン用', UPDATE_USER = N'初回ログイン用' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = NULL, CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = N'', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = NULL, CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = N'', CREATE_USER = N'初回ログイン用', UPDATE_USER = N'初回ログイン用' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = NULL, CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = NULL, CREATE_USER = N'大谷　正平', UPDATE_USER = N'大谷　正平' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = N'', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = NULL, CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUURYOKU_TANTOUSHA)
UPDATE T SET NYUURYOKU_TANTOUSHA_BIKOU = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 22;

