-- UPDATE script for table M_NYUUKINSAKI_FURIKOMI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 2

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUUKINSAKI_FURIKOMI)
UPDATE T SET FURIKOMI_NAME = N'ｲﾄｳｹﾝｾﾝﾂ' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_NYUUKINSAKI_FURIKOMI)
UPDATE T SET FURIKOMI_NAME = N'ｶﾜﾂ ｼﾞﾛｳ' WHERE rn = 2;

