-- UPDATE script for table M_OUTPUT_CSV_PATTERN (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 8

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_OUTPUT_CSV_PATTERN)
UPDATE T SET PATTERN_NAME = N'１', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_OUTPUT_CSV_PATTERN)
UPDATE T SET PATTERN_NAME = N'１', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_OUTPUT_CSV_PATTERN)
UPDATE T SET PATTERN_NAME = N'12345', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_OUTPUT_CSV_PATTERN)
UPDATE T SET PATTERN_NAME = N'全明細', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_OUTPUT_CSV_PATTERN)
UPDATE T SET PATTERN_NAME = N'売上', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_OUTPUT_CSV_PATTERN)
UPDATE T SET PATTERN_NAME = N'売上', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_OUTPUT_CSV_PATTERN)
UPDATE T SET PATTERN_NAME = N'売上', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_OUTPUT_CSV_PATTERN)
UPDATE T SET PATTERN_NAME = N'取引先単位（売上、支払）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

