-- UPDATE script for table M_PLAN_CATEGORY (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 3

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_PLAN_CATEGORY)
UPDATE T SET PLAN_CATEGORY_NAME = N'環境将軍Rデモ_自動配車', LYNA_PLAN_NAME = N'kankyoushougunR', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_PLAN_CATEGORY)
UPDATE T SET PLAN_CATEGORY_NAME = N'ライナクラウド_デモ', LYNA_PLAN_NAME = N'111', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_PLAN_CATEGORY)
UPDATE T SET PLAN_CATEGORY_NAME = N'APIテスト計画カテゴリー', LYNA_PLAN_NAME = N'1', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

