-- UPDATE script for table M_RAKU_RAKU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 91

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'305-0031', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市吾妻1-7-1', SOUFU_SAKI_ADDRESS2 = N'トナリエCREO5階', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'305-0031', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市吾妻1-7-1', SOUFU_SAKI_ADDRESS2 = N'トナリエCREO5階', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'305-0031', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市吾妻1-7-1', SOUFU_SAKI_ADDRESS2 = N'トナリエCREO5階', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'101-0041', SOUFU_SAKI_ADDRESS1 = N'東京都千代田区神田須田町1-16-5', SOUFU_SAKI_ADDRESS2 = N'ヒューリック神田8F', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'305-0031', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市吾妻4-19-10', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'101-0041', SOUFU_SAKI_ADDRESS1 = N'東京都千代田区神田須田町1-16-5', SOUFU_SAKI_ADDRESS2 = N'ヒューリック神田8F', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'盛岡　英雄', SOUFU_SAKI_POST = N'020-0034', SOUFU_SAKI_ADDRESS1 = N'岩手県盛岡市盛岡駅前通16-21 盛岡駅前通ビル5F', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'812-0011', SOUFU_SAKI_ADDRESS1 = N'福岡県福岡市博多区博多駅前4-3-3', SOUFU_SAKI_ADDRESS2 = N'博多八百治ビル4F', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'453-0002', SOUFU_SAKI_ADDRESS1 = N'愛知県名古屋市中村区名駅3-22-8 大東海ビル503', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'812-0011', SOUFU_SAKI_ADDRESS1 = N'福岡県福岡市博多区博多駅前4-3-3', SOUFU_SAKI_ADDRESS2 = N'博多八百治ビル4F', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'453-0002', SOUFU_SAKI_ADDRESS1 = N'愛知県名古屋市中村区名駅3-22-8 大東海ビル503', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'306-0001', SOUFU_SAKI_ADDRESS1 = N'茨城県古河市静町6-7-8', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'812-0011', SOUFU_SAKI_ADDRESS1 = N'福岡県福岡市博多区博多駅前4-3-3', SOUFU_SAKI_ADDRESS2 = N'博多八百治ビル4F', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'453-0002', SOUFU_SAKI_ADDRESS1 = N'愛知県名古屋市中村区名駅3-22-8 大東海ビル503', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'306-0001', SOUFU_SAKI_ADDRESS1 = N'茨城県古河市静町6-7-8', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'305-0031', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市吾妻1-7-1', SOUFU_SAKI_ADDRESS2 = N'トナリエCREO5階', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'305-0031', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市吾妻1-7-1', SOUFU_SAKI_ADDRESS2 = N'トナリエCREO5階', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'305-0031', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市吾妻1-7-1', SOUFU_SAKI_ADDRESS2 = N'トナリエCREO5階', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'101-0041', SOUFU_SAKI_ADDRESS1 = N'東京都千代田区神田須田町1-16-5', SOUFU_SAKI_ADDRESS2 = N'ヒューリック神田8F', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'305-0031', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市吾妻4-19-10', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'812-0011', SOUFU_SAKI_ADDRESS1 = N'福岡県福岡市博多区博多駅前4-3-3', SOUFU_SAKI_ADDRESS2 = N'博多八百治ビル4F', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'453-0002', SOUFU_SAKI_ADDRESS1 = N'愛知県名古屋市中村区名駅3-22-8 大東海ビル503', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'306-0001', SOUFU_SAKI_ADDRESS1 = N'茨城県古河市静町6-7-8', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'筑紫　聡', SOUFU_SAKI_POST = N'305-8577', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市天王台一丁目1番地1', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'305-0821', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市春日3-3-3', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'とりひきさき', SOUFU_SAKI_POST = N'305-0821', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市春日3-3-5', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'300-4354', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市国松1400', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'300-3257', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市筑穂1-1-13', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'305-0821', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市春日3-3-3', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'13213', EMAIL_ADDRESS2 = N'1321313', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'305-0821', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市春日3-3-3', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'13213', EMAIL_ADDRESS2 = N'1321313', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'とりひきさき', SOUFU_SAKI_POST = N'305-0821', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市春日3-3-5', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'やまだ', UPDATE_USER = N'やまだ' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'やまだ', UPDATE_USER = N'やまだ' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'やまだ', UPDATE_USER = N'やまだ' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'305-0821', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市春日3-3-3', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'13213', EMAIL_ADDRESS2 = N'1321313', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'とりひきさき', SOUFU_SAKI_POST = N'305-0821', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市春日3-3-5', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'300-4354', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市国松1400', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'300-3257', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市筑穂1-1-13', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 62;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 63;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'305-0821', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市春日3-3-3', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'13213', EMAIL_ADDRESS2 = N'1321313', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 64;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'とりひきさき', SOUFU_SAKI_POST = N'305-0821', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市春日3-3-5', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 65;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 66;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 67;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 68;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'300-4354', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市国松1400', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 69;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'300-3257', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市筑穂1-1-13', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 70;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 71;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 72;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 73;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 74;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 75;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'305-0821', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市春日3-3-3', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'13213', EMAIL_ADDRESS2 = N'1321313', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 76;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'とりひきさき', SOUFU_SAKI_POST = N'305-0821', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市春日3-3-5', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 77;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 78;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 79;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 80;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'300-4354', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市国松1400', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 81;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'300-3257', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市筑穂1-1-13', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 82;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 83;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 84;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 85;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'やまだ', UPDATE_USER = N'やまだ' WHERE rn = 86;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'305-0033', SOUFU_SAKI_ADDRESS1 = N'茨城県つくば市東新井21-12', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'やまだ', UPDATE_USER = N'やまだ' WHERE rn = 87;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'444-2525', SOUFU_SAKI_ADDRESS1 = N'愛知県豊田市大河原町1-1-1', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'やまだ', UPDATE_USER = N'やまだ' WHERE rn = 88;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'300-0502', SOUFU_SAKI_ADDRESS1 = N'茨城県稲敷市信太古渡7-8-9', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'やまだ', UPDATE_USER = N'やまだ' WHERE rn = 89;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'', SOUFU_SAKI_ADDRESS1 = N'', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 90;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_RAKU_RAKU)
UPDATE T SET SOUFU_SAKI_TANTOUSHA = N'', SOUFU_SAKI_POST = N'460-0001', SOUFU_SAKI_ADDRESS1 = N'愛知県名古屋市中区三の丸1-1-1', SOUFU_SAKI_ADDRESS2 = N'', EMAIL_ADDRESS1 = N'', EMAIL_ADDRESS2 = N'', EMAIL_ADDRESS3 = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 91;

