-- UPDATE script for table M_SBNB_PATTERN (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 13

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SBNB_PATTERN)
UPDATE T SET PATTERN_NAME = N'中間処理', PATTERN_FURIGANA = N'チュウカンリョシショリ', GYOUSHA_NAME = N'エジソン商事', GYOUSHA_ADDRESS = NULL, GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', GYOUSHA_ADDRESS2 = N'', GENBA_NAME = N'エジソン商事　クリーンセンター', GENBA_ADDRESS = NULL, GENBA_ADDRESS1 = N'水戸市上水戸5-6-7', GENBA_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', SAKUSEI_HOUHOU_NAME = NULL, JISHA_JOUBUN_NAME = NULL WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SBNB_PATTERN)
UPDATE T SET PATTERN_NAME = N'中間処理', PATTERN_FURIGANA = N'チュウカンリョシショリ', GYOUSHA_NAME = N'エジソン商事', GYOUSHA_ADDRESS = NULL, GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', GYOUSHA_ADDRESS2 = N'', GENBA_NAME = N'', GENBA_ADDRESS = NULL, GENBA_ADDRESS1 = N'', GENBA_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', SAKUSEI_HOUHOU_NAME = NULL, JISHA_JOUBUN_NAME = NULL WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SBNB_PATTERN)
UPDATE T SET PATTERN_NAME = N'自社処分パターン', PATTERN_FURIGANA = N'ジシャショブンパターン', GYOUSHA_NAME = N'エジソン商事', GYOUSHA_ADDRESS = NULL, GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', GYOUSHA_ADDRESS2 = N'', GENBA_NAME = N'エジソン商事　クリーンセンター', GENBA_ADDRESS = NULL, GENBA_ADDRESS1 = N'水戸市上水戸5-6-7', GENBA_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', SAKUSEI_HOUHOU_NAME = NULL, JISHA_JOUBUN_NAME = NULL WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SBNB_PATTERN)
UPDATE T SET PATTERN_NAME = N'自社処分パターン', PATTERN_FURIGANA = N'ジシャショブンパターン', GYOUSHA_NAME = N'エジソン商事', GYOUSHA_ADDRESS = NULL, GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', GYOUSHA_ADDRESS2 = N'', GENBA_NAME = N'', GENBA_ADDRESS = NULL, GENBA_ADDRESS1 = N'', GENBA_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', SAKUSEI_HOUHOU_NAME = NULL, JISHA_JOUBUN_NAME = NULL WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SBNB_PATTERN)
UPDATE T SET PATTERN_NAME = N'クロダ商事', PATTERN_FURIGANA = N'クロダショウジ', GYOUSHA_NAME = N'クロダ商事', GYOUSHA_ADDRESS = NULL, GYOUSHA_ADDRESS1 = N'つくば市作谷862-1', GYOUSHA_ADDRESS2 = N'', GENBA_NAME = N'', GENBA_ADDRESS = NULL, GENBA_ADDRESS1 = N'', GENBA_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', SAKUSEI_HOUHOU_NAME = NULL, JISHA_JOUBUN_NAME = NULL WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SBNB_PATTERN)
UPDATE T SET PATTERN_NAME = N'クロダ商事/松丸/ｴｼﾞｿﾝ', PATTERN_FURIGANA = N'クロダ・マツマル・エジソエジソン', GYOUSHA_NAME = N'クロダ商事', GYOUSHA_ADDRESS = NULL, GYOUSHA_ADDRESS1 = N'つくば市作谷862-1', GYOUSHA_ADDRESS2 = N'', GENBA_NAME = N'', GENBA_ADDRESS = NULL, GENBA_ADDRESS1 = N'', GENBA_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', SAKUSEI_HOUHOU_NAME = NULL, JISHA_JOUBUN_NAME = NULL WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SBNB_PATTERN)
UPDATE T SET PATTERN_NAME = N'クロダ商事/松丸/ｴｼﾞｿﾝ', PATTERN_FURIGANA = N'クロダ・マツマル・エジソエジソン', GYOUSHA_NAME = N'松丸プラント', GYOUSHA_ADDRESS = NULL, GYOUSHA_ADDRESS1 = N'つくば市作谷1494-24', GYOUSHA_ADDRESS2 = N'', GENBA_NAME = N'', GENBA_ADDRESS = NULL, GENBA_ADDRESS1 = N'', GENBA_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', SAKUSEI_HOUHOU_NAME = NULL, JISHA_JOUBUN_NAME = NULL WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SBNB_PATTERN)
UPDATE T SET PATTERN_NAME = N'クロダ商事/松丸/ｴｼﾞｿﾝ', PATTERN_FURIGANA = N'クロダ・マツマル・エジソエジソン', GYOUSHA_NAME = N'エジソン商事', GYOUSHA_ADDRESS = NULL, GYOUSHA_ADDRESS1 = N'つくば市東新井13‐31', GYOUSHA_ADDRESS2 = N'', GENBA_NAME = N'', GENBA_ADDRESS = NULL, GENBA_ADDRESS1 = N'', GENBA_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', SAKUSEI_HOUHOU_NAME = NULL, JISHA_JOUBUN_NAME = NULL WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SBNB_PATTERN)
UPDATE T SET PATTERN_NAME = N'特殊', PATTERN_FURIGANA = N'トクシュ', GYOUSHA_NAME = N'三日月クリーン開発', GYOUSHA_ADDRESS = NULL, GYOUSHA_ADDRESS1 = N'豊前市大河内102-8', GYOUSHA_ADDRESS2 = N'', GENBA_NAME = N'三日月クリーン開発　最終処分場', GENBA_ADDRESS = NULL, GENBA_ADDRESS1 = N'宮若市鶴田355-9', GENBA_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', SAKUSEI_HOUHOU_NAME = NULL, JISHA_JOUBUN_NAME = NULL WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SBNB_PATTERN)
UPDATE T SET PATTERN_NAME = N'特殊', PATTERN_FURIGANA = N'トクシュ', GYOUSHA_NAME = N'ナカゾネ産業', GYOUSHA_ADDRESS = NULL, GYOUSHA_ADDRESS1 = N'土浦市中村西根50-1-2', GYOUSHA_ADDRESS2 = N'', GENBA_NAME = N'ナカゾネ産業　藤岡処分場', GENBA_ADDRESS = NULL, GENBA_ADDRESS1 = N'藤岡市下戸塚大字稲荷1028（他8筆）', GENBA_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', SAKUSEI_HOUHOU_NAME = NULL, JISHA_JOUBUN_NAME = NULL WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SBNB_PATTERN)
UPDATE T SET PATTERN_NAME = N'テスト１', PATTERN_FURIGANA = N'テスト１', GYOUSHA_NAME = N'エジソン商事', GYOUSHA_ADDRESS = NULL, GYOUSHA_ADDRESS1 = N'つくば市東新井13-31', GYOUSHA_ADDRESS2 = N'', GENBA_NAME = N'エジソン商事', GENBA_ADDRESS = NULL, GENBA_ADDRESS1 = N'つくば市東新井31-13', GENBA_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', SAKUSEI_HOUHOU_NAME = NULL, JISHA_JOUBUN_NAME = NULL WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SBNB_PATTERN)
UPDATE T SET PATTERN_NAME = N'テスト①', PATTERN_FURIGANA = N'テスト１', GYOUSHA_NAME = N'若槻リサイクル', GYOUSHA_ADDRESS = NULL, GYOUSHA_ADDRESS1 = N'久喜市新井7-6-1', GYOUSHA_ADDRESS2 = N'A-303', GENBA_NAME = N'若槻リサイクル', GENBA_ADDRESS = NULL, GENBA_ADDRESS1 = N'久喜市新井7-6-1', GENBA_ADDRESS2 = N'A-303', HOUKOKUSHO_BUNRUI_NAME = N'廃油', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', SAKUSEI_HOUHOU_NAME = NULL, JISHA_JOUBUN_NAME = NULL WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SBNB_PATTERN)
UPDATE T SET PATTERN_NAME = N'テスト２', PATTERN_FURIGANA = N'テスト２', GYOUSHA_NAME = N'若槻リサイクル', GYOUSHA_ADDRESS = NULL, GYOUSHA_ADDRESS1 = N'久喜市新井7-6-1', GYOUSHA_ADDRESS2 = N'A-303', GENBA_NAME = N'若槻リサイクル　館山工場', GENBA_ADDRESS = NULL, GENBA_ADDRESS1 = N'館山市亀ケ原4-12-3', GENBA_ADDRESS2 = N'', HOUKOKUSHO_BUNRUI_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', SAKUSEI_HOUHOU_NAME = NULL, JISHA_JOUBUN_NAME = NULL WHERE rn = 13;

