-- UPDATE script for table M_SHUUKEI_KOUMOKU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 8

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHUUKEI_KOUMOKU)
UPDATE T SET SHUUKEI_KOUMOKU_NAME = N'3か月毎', SHUUKEI_KOUMOKU_NAME_RYAKU = N'3か月毎', SHUUKEI_KOUMOKU_FURIGANA = N'３カゲツゴオｔゴトゴ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHUUKEI_KOUMOKU)
UPDATE T SET SHUUKEI_KOUMOKU_NAME = N'口座有り', SHUUKEI_KOUMOKU_NAME_RYAKU = N'口座有り', SHUUKEI_KOUMOKU_FURIGANA = N'コウザアリ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHUUKEI_KOUMOKU)
UPDATE T SET SHUUKEI_KOUMOKU_NAME = N'その他', SHUUKEI_KOUMOKU_NAME_RYAKU = N'その他', SHUUKEI_KOUMOKU_FURIGANA = N'ソノタ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHUUKEI_KOUMOKU)
UPDATE T SET SHUUKEI_KOUMOKU_NAME = N'取引先集計', SHUUKEI_KOUMOKU_NAME_RYAKU = N'取引先集計', SHUUKEI_KOUMOKU_FURIGANA = N'トリヒキサキシュウケ', CREATE_USER = N'沢口　賢治', UPDATE_USER = N'沢口　賢治' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHUUKEI_KOUMOKU)
UPDATE T SET SHUUKEI_KOUMOKU_NAME = N'手数料（株式会社X）', SHUUKEI_KOUMOKU_NAME_RYAKU = N'手数料（X', SHUUKEI_KOUMOKU_FURIGANA = N'テスウリョウＸ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHUUKEI_KOUMOKU)
UPDATE T SET SHUUKEI_KOUMOKU_NAME = N'自社集計', SHUUKEI_KOUMOKU_NAME_RYAKU = N'自社集計', SHUUKEI_KOUMOKU_FURIGANA = N'ジシャシュウケイ', CREATE_USER = N'沢口　賢治', UPDATE_USER = N'沢口　賢治' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHUUKEI_KOUMOKU)
UPDATE T SET SHUUKEI_KOUMOKU_NAME = N'鉄鋼会社', SHUUKEI_KOUMOKU_NAME_RYAKU = N'鉄鋼会社', SHUUKEI_KOUMOKU_FURIGANA = N'テッコウカイシャ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHUUKEI_KOUMOKU)
UPDATE T SET SHUUKEI_KOUMOKU_NAME = N'一般廃棄物', SHUUKEI_KOUMOKU_NAME_RYAKU = N'一般廃棄物', SHUUKEI_KOUMOKU_FURIGANA = N'イッパンハイキブツ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 8;

