-- UPDATE script for table M_SHASHU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 28

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'2tダンプ', SHASHU_NAME_RYAKU = N'2tダンプ', SHASHU_FURIGANA = N'２ｔダンプ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'4tダンプ', SHASHU_NAME_RYAKU = N'4tダンプ', SHASHU_FURIGANA = N'４ｔダンプ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'4tコンテナ', SHASHU_NAME_RYAKU = N'4tコンテナ', SHASHU_FURIGANA = N'４ｔコンテナ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'4tユニック', SHASHU_NAME_RYAKU = N'4tユニック', SHASHU_FURIGANA = N'４ｔユニック', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'4t平ダンプ', SHASHU_NAME_RYAKU = N'4t平ダンプ', SHASHU_FURIGANA = N'４ｔヒラダンプ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'2tコンテナ', SHASHU_NAME_RYAKU = N'2tコンテナ', SHASHU_FURIGANA = N'２ｔコンテナ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'7tユニック', SHASHU_NAME_RYAKU = N'7tユニック', SHASHU_FURIGANA = N'７ｔユニック', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'10tコンテナ', SHASHU_NAME_RYAKU = N'10tコンテ', SHASHU_FURIGANA = N'１０ｔコンテナ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'10tダンプ', SHASHU_NAME_RYAKU = N'10tダンプ', SHASHU_FURIGANA = N'１０ｔダンプ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'7tダンプ', SHASHU_NAME_RYAKU = N'7tダンプ', SHASHU_FURIGANA = N'７ｔダンプ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'トレーラー', SHASHU_NAME_RYAKU = N'トレーラー', SHASHU_FURIGANA = N'トレーラー', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'保冷車', SHASHU_NAME_RYAKU = N'保冷車', SHASHU_FURIGANA = N'ホレイシャ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'バン', SHASHU_NAME_RYAKU = N'バン', SHASHU_FURIGANA = N'バン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'2t平車', SHASHU_NAME_RYAKU = N'2t平車', SHASHU_FURIGANA = N'２ｔヒラシャ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'4t平ボディー', SHASHU_NAME_RYAKU = N'4t平ボディ', SHASHU_FURIGANA = N'４ｔヒラボディー', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'４ｔパッカー', SHASHU_NAME_RYAKU = N'４ｔパッカ', SHASHU_FURIGANA = N'４ｔパッカー', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'２ｔパッカー車', SHASHU_NAME_RYAKU = N'２ｔパッカ', SHASHU_FURIGANA = N'２ｔパッカー', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'2t平ボディー', SHASHU_NAME_RYAKU = N'2t平ボディ', SHASHU_FURIGANA = N'２ｔヒラボディー', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'3tユニック', SHASHU_NAME_RYAKU = N'3tユニック', SHASHU_FURIGANA = N'３ｔユニック', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'Front loaders', SHASHU_NAME_RYAKU = N'F loader', SHASHU_FURIGANA = N'Front loaders', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'Rear loaders', SHASHU_NAME_RYAKU = N'R loader', SHASHU_FURIGANA = N'Rear loaders', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'4tバキューム車', SHASHU_NAME_RYAKU = N'4tバキュー', SHASHU_FURIGANA = N'４ｔバキュームシャ', CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'4tウイング', SHASHU_NAME_RYAKU = N'4tウイング', SHASHU_FURIGANA = N'４ｔウイング', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'車種１', SHASHU_NAME_RYAKU = N'車種１', SHASHU_FURIGANA = N'ｓｙＷｓｙＷＥ．１', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'25tダンプ', SHASHU_NAME_RYAKU = N'25tダンプ', SHASHU_FURIGANA = N'２５ｔダンプ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'5tトレーラー', SHASHU_NAME_RYAKU = N'5tトレーラ', SHASHU_FURIGANA = N'５ｔｔトレーラー', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'あいうえお', SHASHU_NAME_RYAKU = N'あいうえお', SHASHU_FURIGANA = N'アイウエオ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHASHU)
UPDATE T SET SHASHU_NAME = N'8tコンテナ', SHASHU_NAME_RYAKU = N'8tコンテナ', SHASHU_FURIGANA = N'８ｔコンテナ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 28;

