-- UPDATE script for table M_SHIME_SHORI_GROUP (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 7

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHIME_SHORI_GROUP)
UPDATE T SET SHIME_SHORI_GROUP_NAME = N'15日締め', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHIME_SHORI_GROUP)
UPDATE T SET SHIME_SHORI_GROUP_NAME = N'末締め', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHIME_SHORI_GROUP)
UPDATE T SET SHIME_SHORI_GROUP_NAME = N'早締め', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHIME_SHORI_GROUP)
UPDATE T SET SHIME_SHORI_GROUP_NAME = N'請求書 確認不要', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHIME_SHORI_GROUP)
UPDATE T SET SHIME_SHORI_GROUP_NAME = N'請求書 営業確認', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHIME_SHORI_GROUP)
UPDATE T SET SHIME_SHORI_GROUP_NAME = N'大手スーパー（早締）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHIME_SHORI_GROUP)
UPDATE T SET SHIME_SHORI_GROUP_NAME = N'末締め', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

