-- UPDATE script for table M_SHURUI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 21

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'収集運搬', SHURUI_NAME_RYAKU = N'収集運搬', SHURUI_FURIGANA = N'シュウシュウウンパン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'処分費', SHURUI_NAME_RYAKU = N'処分費', SHURUI_FURIGANA = N'ショブンヒ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'廃電子機器', SHURUI_NAME_RYAKU = N'廃電子機器', SHURUI_FURIGANA = N'ハイデンシキキ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'銅線', SHURUI_NAME_RYAKU = N'銅線', SHURUI_FURIGANA = N'ドウセン', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'燃えがら', SHURUI_NAME_RYAKU = N'燃えがら', SHURUI_FURIGANA = N'モエガラ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'金属くず', SHURUI_NAME_RYAKU = N'金属くず', SHURUI_FURIGANA = N'キンゾククズ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'ガラスくず', SHURUI_NAME_RYAKU = N'ガラスくず', SHURUI_FURIGANA = N'ガラスクズ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'コンクリートくず', SHURUI_NAME_RYAKU = N'コンクリートくず', SHURUI_FURIGANA = N'コンクリートクズ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'汚泥', SHURUI_NAME_RYAKU = N'汚泥', SHURUI_FURIGANA = N'オデイ', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'製品', SHURUI_NAME_RYAKU = N'製品', SHURUI_FURIGANA = N'セイヒン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'処分', SHURUI_NAME_RYAKU = N'処分', SHURUI_FURIGANA = N'ショブン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'特管', SHURUI_NAME_RYAKU = N'特管', SHURUI_FURIGANA = N'トッカン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'産廃', SHURUI_NAME_RYAKU = N'産廃', SHURUI_FURIGANA = N'サンパイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'鉄', SHURUI_NAME_RYAKU = N'鉄', SHURUI_FURIGANA = N'テツ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'非鉄', SHURUI_NAME_RYAKU = N'非鉄', SHURUI_FURIGANA = N'ヒテツ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'一般廃棄物', SHURUI_NAME_RYAKU = N'一般廃棄物', SHURUI_FURIGANA = N'イッパンハイキブツ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'古紙・機密', SHURUI_NAME_RYAKU = N'古紙・機密', SHURUI_FURIGANA = N'コシ・キミツ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'廃棄物種類', SHURUI_NAME_RYAKU = N'廃棄物種類', SHURUI_FURIGANA = N'ｈｏＤｋＭｂｖｔｄｓｙＷｒｒＤＡＡｉ．', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'その他', SHURUI_NAME_RYAKU = N'その他', SHURUI_FURIGANA = N'ソノタ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'廃プラスチック類', SHURUI_NAME_RYAKU = N'廃プラスチック類', SHURUI_FURIGANA = N'ｈａｉｕハイプラスチックスルイルイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHURUI)
UPDATE T SET SHURUI_NAME = N'産廃税', SHURUI_NAME_RYAKU = N'産廃税', SHURUI_FURIGANA = N'サンパイゼイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 21;

