-- UPDATE script for table M_SHOUHIZEI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 3

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOUHIZEI)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOUHIZEI)
UPDATE T SET CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOUHIZEI)
UPDATE T SET CREATE_USER = N'jems', UPDATE_USER = N'jems' WHERE rn = 3;

