-- UPDATE script for table M_SHIKUCHOUSON (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 11

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHIKUCHOUSON)
UPDATE T SET SHIKUCHOUSON_NAME = N'つくば市', SHIKUCHOUSON_NAME_RYAKU = N'つくば市', SHIKUCHOUSON_FURIGANA = N'ツクバシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHIKUCHOUSON)
UPDATE T SET SHIKUCHOUSON_NAME = N'土浦市', SHIKUCHOUSON_NAME_RYAKU = N'土浦市', SHIKUCHOUSON_FURIGANA = N'ツチウラシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHIKUCHOUSON)
UPDATE T SET SHIKUCHOUSON_NAME = N'牛久市', SHIKUCHOUSON_NAME_RYAKU = N'牛久市', SHIKUCHOUSON_FURIGANA = N'ウシクシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHIKUCHOUSON)
UPDATE T SET SHIKUCHOUSON_NAME = N'竜ケ崎市', SHIKUCHOUSON_NAME_RYAKU = N'竜ケ崎市', SHIKUCHOUSON_FURIGANA = N'リュウガサキシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHIKUCHOUSON)
UPDATE T SET SHIKUCHOUSON_NAME = N'取手市', SHIKUCHOUSON_NAME_RYAKU = N'取手市', SHIKUCHOUSON_FURIGANA = N'トリデシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHIKUCHOUSON)
UPDATE T SET SHIKUCHOUSON_NAME = N'常総市', SHIKUCHOUSON_NAME_RYAKU = N'常総市', SHIKUCHOUSON_FURIGANA = N'ジョウソウシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHIKUCHOUSON)
UPDATE T SET SHIKUCHOUSON_NAME = N'かすみがうら市', SHIKUCHOUSON_NAME_RYAKU = N'かすみがう', SHIKUCHOUSON_FURIGANA = N'カスミガウラシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHIKUCHOUSON)
UPDATE T SET SHIKUCHOUSON_NAME = N'つくばみらい市', SHIKUCHOUSON_NAME_RYAKU = N'つくばみら', SHIKUCHOUSON_FURIGANA = N'ツクバミライシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHIKUCHOUSON)
UPDATE T SET SHIKUCHOUSON_NAME = N'柏市', SHIKUCHOUSON_NAME_RYAKU = N'柏市', SHIKUCHOUSON_FURIGANA = N'カシワシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHIKUCHOUSON)
UPDATE T SET SHIKUCHOUSON_NAME = N'守谷市', SHIKUCHOUSON_NAME_RYAKU = N'守谷市', SHIKUCHOUSON_FURIGANA = N'モリヤシ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHIKUCHOUSON)
UPDATE T SET SHIKUCHOUSON_NAME = N'テスト市区町村', SHIKUCHOUSON_NAME_RYAKU = N'テスト市区', SHIKUCHOUSON_FURIGANA = N'テストシクチョウソン', CREATE_USER = N'テスト太郎', UPDATE_USER = N'テスト太郎' WHERE rn = 11;

