-- UPDATE script for table M_SHAIN (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 35

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'鈴木　次郎', SHAIN_NAME_RYAKU = N'鈴木　次郎', SHAIN_FURIGANA = N'ショカイログインスズ', EIGYOU_TANTOU_KBN = N'True', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'True', MAIL_ADDRESS = N'kyoto.teraooi@ezweb.ne.jp', CREATE_USER = N'edison', UPDATE_USER = N'鈴木　次郎', INXS_TANTOU_FLG = N'True' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'佐藤　太郎', SHAIN_NAME_RYAKU = N'佐藤　太郎', SHAIN_FURIGANA = N'サトウハナコタロウ', EIGYOU_TANTOU_KBN = N'False', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'True', MAIL_ADDRESS = N'', CREATE_USER = N'初回ログイン用', UPDATE_USER = N'新川　拓哉', INXS_TANTOU_FLG = N'True' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'西田　栄一', SHAIN_NAME_RYAKU = N'西田　栄一', SHAIN_FURIGANA = N'ニシダエイイチ', EIGYOU_TANTOU_KBN = N'True', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'True', MAIL_ADDRESS = N'nishida@e-mall.co.jj', CREATE_USER = N'初回ログイン用', UPDATE_USER = N'新川　拓哉', INXS_TANTOU_FLG = N'True' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'中西　大樹', SHAIN_NAME_RYAKU = N'中西　大樹', SHAIN_FURIGANA = N'ナカニシダイキ', EIGYOU_TANTOU_KBN = N'False', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'False', MAIL_ADDRESS = N'', CREATE_USER = N'初回ログイン用', UPDATE_USER = N'新川　拓哉', INXS_TANTOU_FLG = N'True' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'大野　哲夫', SHAIN_NAME_RYAKU = N'大野　哲夫', SHAIN_FURIGANA = N'オオノテツオ', EIGYOU_TANTOU_KBN = N'False', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'False', MAIL_ADDRESS = N'', CREATE_USER = N'初回ログイン用', UPDATE_USER = N'新川　拓哉', INXS_TANTOU_FLG = N'True' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'坂本　琢磨', SHAIN_NAME_RYAKU = N'坂本　琢磨', SHAIN_FURIGANA = N'サカモトタクマ', EIGYOU_TANTOU_KBN = N'False', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'False', MAIL_ADDRESS = N'', CREATE_USER = N'初回ログイン用', UPDATE_USER = N'新川　拓哉', INXS_TANTOU_FLG = N'True' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'野口　秀吉', SHAIN_NAME_RYAKU = N'野口　秀吉', SHAIN_FURIGANA = N'ノグチヒデキチ', EIGYOU_TANTOU_KBN = N'False', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'False', MAIL_ADDRESS = N'', CREATE_USER = N'初回ログイン用', UPDATE_USER = N'新川　拓哉', INXS_TANTOU_FLG = N'True' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'竹ノ内　豊', SHAIN_NAME_RYAKU = N'竹ノ内　豊', SHAIN_FURIGANA = N'タケノウチユタカ', EIGYOU_TANTOU_KBN = N'True', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'True', MAIL_ADDRESS = N'', CREATE_USER = N'初回ログイン用', UPDATE_USER = N'新川　拓哉', INXS_TANTOU_FLG = N'True' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'沢口　賢治', SHAIN_NAME_RYAKU = N'沢口　賢治', SHAIN_FURIGANA = N'サワグチケンジ', EIGYOU_TANTOU_KBN = N'True', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'True', MAIL_ADDRESS = N'', CREATE_USER = N'初回ログイン用', UPDATE_USER = N'新川　拓哉', INXS_TANTOU_FLG = N'True' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'田中　五郎', SHAIN_NAME_RYAKU = N'田中　五郎', SHAIN_FURIGANA = N'タナカタナカゴロウ', EIGYOU_TANTOU_KBN = N'False', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'False', MAIL_ADDRESS = N'', CREATE_USER = N'初回ログイン用', UPDATE_USER = N'新川　拓哉', INXS_TANTOU_FLG = N'True' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'髙橋　智', SHAIN_NAME_RYAKU = N'髙橋　智', SHAIN_FURIGANA = N'タカハシサトシ', EIGYOU_TANTOU_KBN = N'False', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'False', MAIL_ADDRESS = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', INXS_TANTOU_FLG = N'True' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'岡田　益男', SHAIN_NAME_RYAKU = N'岡田　益男', SHAIN_FURIGANA = N'オカダマスオ', EIGYOU_TANTOU_KBN = N'False', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'False', MAIL_ADDRESS = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', INXS_TANTOU_FLG = N'False' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'安田　彬', SHAIN_NAME_RYAKU = N'安田　彬', SHAIN_FURIGANA = N'ヤスダアキラ', EIGYOU_TANTOU_KBN = N'True', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'True', MAIL_ADDRESS = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', INXS_TANTOU_FLG = N'True' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'大川　英雄', SHAIN_NAME_RYAKU = N'大川　英雄', SHAIN_FURIGANA = N'オオカワヒデオ', EIGYOU_TANTOU_KBN = N'False', SHOBUN_TANTOU_KBN = N'True', NYUURYOKU_TANTOU_KBN = N'False', MAIL_ADDRESS = N'', CREATE_USER = N'西田　栄一', UPDATE_USER = N'新川　拓哉', INXS_TANTOU_FLG = NULL WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'野茂　英雄', SHAIN_NAME_RYAKU = N'のも', SHAIN_FURIGANA = N'ノモヒデオ', EIGYOU_TANTOU_KBN = N'True', SHOBUN_TANTOU_KBN = N'True', NYUURYOKU_TANTOU_KBN = N'True', MAIL_ADDRESS = N'morodmoi@j-ems.jp', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', INXS_TANTOU_FLG = N'True' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'大谷　正平', SHAIN_NAME_RYAKU = N'大谷　正平', SHAIN_FURIGANA = N'オオタニショウヘイ', EIGYOU_TANTOU_KBN = N'True', SHOBUN_TANTOU_KBN = N'True', NYUURYOKU_TANTOU_KBN = N'True', MAIL_ADDRESS = N'morodomi@j-ems.jp', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊', INXS_TANTOU_FLG = N'True' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'山田　太郎', SHAIN_NAME_RYAKU = N'山田　太郎', SHAIN_FURIGANA = N'ヤマダタロウ', EIGYOU_TANTOU_KBN = N'False', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'False', MAIL_ADDRESS = N'mo-kusama@j-ems.jp', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'山田　太郎', INXS_TANTOU_FLG = N'False' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'山田　太郎', SHAIN_NAME_RYAKU = N'山田　次郎', SHAIN_FURIGANA = N'ヤマダ', EIGYOU_TANTOU_KBN = N'True', SHOBUN_TANTOU_KBN = N'True', NYUURYOKU_TANTOU_KBN = N'True', MAIL_ADDRESS = N'', CREATE_USER = N'大谷　正平', UPDATE_USER = N'やまだ', INXS_TANTOU_FLG = N'True' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'植田 和樹', SHAIN_NAME_RYAKU = N'植田 和樹', SHAIN_FURIGANA = N'ウエダ カズキ', EIGYOU_TANTOU_KBN = N'True', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'True', MAIL_ADDRESS = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', INXS_TANTOU_FLG = N'True' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'桜　勤三', SHAIN_NAME_RYAKU = N'桜　勤三', SHAIN_FURIGANA = N'サクラキンゾウ', EIGYOU_TANTOU_KBN = N'False', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'False', MAIL_ADDRESS = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', INXS_TANTOU_FLG = NULL WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'新川　拓哉', SHAIN_NAME_RYAKU = N'新川　拓哉', SHAIN_FURIGANA = N'シンカワタクヤ', EIGYOU_TANTOU_KBN = N'True', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'True', MAIL_ADDRESS = N'arakawa@j-ems.jp', CREATE_USER = N'田中　五郎', UPDATE_USER = N'竹ノ内　豊', INXS_TANTOU_FLG = N'True' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'朝日 雄一', SHAIN_NAME_RYAKU = N'朝日 雄一', SHAIN_FURIGANA = N'アサヒ ユウイチ', EIGYOU_TANTOU_KBN = N'False', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'False', MAIL_ADDRESS = N'hatakenaka@j-ems.jp', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉', INXS_TANTOU_FLG = N'True' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'石川　聡', SHAIN_NAME_RYAKU = N'石川　聡', SHAIN_FURIGANA = N'イシカワサトシ', EIGYOU_TANTOU_KBN = N'True', SHOBUN_TANTOU_KBN = N'True', NYUURYOKU_TANTOU_KBN = N'True', MAIL_ADDRESS = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', INXS_TANTOU_FLG = N'True' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'つくば　花子', SHAIN_NAME_RYAKU = N'つくば　花子', SHAIN_FURIGANA = N'ツクバハナコ', EIGYOU_TANTOU_KBN = N'True', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'True', MAIL_ADDRESS = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'佐藤　花子', INXS_TANTOU_FLG = NULL WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'院玖珠　太朗', SHAIN_NAME_RYAKU = N'院玖珠　太朗', SHAIN_FURIGANA = N'インクスタロウ', EIGYOU_TANTOU_KBN = N'False', SHOBUN_TANTOU_KBN = N'True', NYUURYOKU_TANTOU_KBN = N'True', MAIL_ADDRESS = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'佐藤　花子', INXS_TANTOU_FLG = N'True' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'工場　担当者', SHAIN_NAME_RYAKU = N'工場　担当者', SHAIN_FURIGANA = N'コウジョウタントウシ', EIGYOU_TANTOU_KBN = N'False', SHOBUN_TANTOU_KBN = N'True', NYUURYOKU_TANTOU_KBN = N'False', MAIL_ADDRESS = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'竹ノ内　豊', INXS_TANTOU_FLG = N'True' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'クリーン　太郎', SHAIN_NAME_RYAKU = N'クリーン　太郎', SHAIN_FURIGANA = N'クリーンタロウ', EIGYOU_TANTOU_KBN = N'False', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'False', MAIL_ADDRESS = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'竹ノ内　豊', INXS_TANTOU_FLG = N'True' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'那比　一', SHAIN_NAME_RYAKU = N'那比　一', SHAIN_FURIGANA = N'ナビイチ', EIGYOU_TANTOU_KBN = N'False', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'False', MAIL_ADDRESS = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', INXS_TANTOU_FLG = N'True' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'那比　二', SHAIN_NAME_RYAKU = N'那比　二', SHAIN_FURIGANA = N'ナビニ', EIGYOU_TANTOU_KBN = N'False', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'False', MAIL_ADDRESS = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉', INXS_TANTOU_FLG = N'True' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'佐藤　大樹', SHAIN_NAME_RYAKU = N'佐藤　大樹', SHAIN_FURIGANA = N'サトウダイジュ', EIGYOU_TANTOU_KBN = N'True', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'False', MAIL_ADDRESS = N'', CREATE_USER = N'山田　太郎', UPDATE_USER = N'山田　太郎', INXS_TANTOU_FLG = NULL WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'田山　礼子', SHAIN_NAME_RYAKU = N'田山　礼子', SHAIN_FURIGANA = N'タヤマレイコ', EIGYOU_TANTOU_KBN = N'True', SHOBUN_TANTOU_KBN = N'True', NYUURYOKU_TANTOU_KBN = N'True', MAIL_ADDRESS = N'suenaga@j-ems.jp', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', INXS_TANTOU_FLG = N'True' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'原田泰造', SHAIN_NAME_RYAKU = N'原田泰造', SHAIN_FURIGANA = N'ハラダタイゾウタイゾ', EIGYOU_TANTOU_KBN = N'True', SHOBUN_TANTOU_KBN = N'True', NYUURYOKU_TANTOU_KBN = N'True', MAIL_ADDRESS = N'taizou@e-mail.com', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', INXS_TANTOU_FLG = N'True' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'他社運転手', SHAIN_NAME_RYAKU = N'他社運転手', SHAIN_FURIGANA = N'タシャウンテンシュ', EIGYOU_TANTOU_KBN = N'False', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'False', MAIL_ADDRESS = N'', CREATE_USER = N'やまだ', UPDATE_USER = N'やまだ', INXS_TANTOU_FLG = NULL WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'森 幸二', SHAIN_NAME_RYAKU = N'モリ コウジ', SHAIN_FURIGANA = N'アキバタロウ', EIGYOU_TANTOU_KBN = N'True', SHOBUN_TANTOU_KBN = N'True', NYUURYOKU_TANTOU_KBN = N'True', MAIL_ADDRESS = N'yokoyama@j-ems.jp', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', INXS_TANTOU_FLG = N'True' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHAIN)
UPDATE T SET SHAIN_NAME = N'ホンダ', SHAIN_NAME_RYAKU = N'ホンダ', SHAIN_FURIGANA = N'ホンダ', EIGYOU_TANTOU_KBN = N'True', SHOBUN_TANTOU_KBN = N'False', NYUURYOKU_TANTOU_KBN = N'True', MAIL_ADDRESS = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎', INXS_TANTOU_FLG = NULL WHERE rn = 35;

