-- UPDATE script for table M_SHOBUN_HOUHOU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 38

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'再生', SHOBUN_HOUHOU_NAME_RYAKU = N'再生', CREATE_USER = N'edison', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'再使用（リユース）', SHOBUN_HOUHOU_NAME_RYAKU = N'再使用（リユース）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'素材再生', SHOBUN_HOUHOU_NAME_RYAKU = N'素材再生', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'他用途原材料化', SHOBUN_HOUHOU_NAME_RYAKU = N'他用途原材料化', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'燃料化', SHOBUN_HOUHOU_NAME_RYAKU = N'燃料化', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'コンポスト化（堆肥化）', SHOBUN_HOUHOU_NAME_RYAKU = N'コンポスト化（堆肥化）', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'その他再生', SHOBUN_HOUHOU_NAME_RYAKU = N'その他再生', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'中間処理', SHOBUN_HOUHOU_NAME_RYAKU = N'中間処理', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'脱水', SHOBUN_HOUHOU_NAME_RYAKU = N'脱水', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'機械乾燥', SHOBUN_HOUHOU_NAME_RYAKU = N'機械乾燥', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'天日乾燥', SHOBUN_HOUHOU_NAME_RYAKU = N'天日乾燥', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'焼却', SHOBUN_HOUHOU_NAME_RYAKU = N'焼却', CREATE_USER = N'edison', UPDATE_USER = N'新川　拓哉' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'油水分離', SHOBUN_HOUHOU_NAME_RYAKU = N'油水分離', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'中和', SHOBUN_HOUHOU_NAME_RYAKU = N'中和', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'破砕', SHOBUN_HOUHOU_NAME_RYAKU = N'破砕', CREATE_USER = N'edison', UPDATE_USER = N'鈴木　次郎' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'圧縮', SHOBUN_HOUHOU_NAME_RYAKU = N'圧縮', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'溶融', SHOBUN_HOUHOU_NAME_RYAKU = N'溶融', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'選別', SHOBUN_HOUHOU_NAME_RYAKU = N'選別', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'固形化', SHOBUN_HOUHOU_NAME_RYAKU = N'固形化', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'ばい焼', SHOBUN_HOUHOU_NAME_RYAKU = N'ばい焼', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'分解', SHOBUN_HOUHOU_NAME_RYAKU = N'分解', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'洗浄', SHOBUN_HOUHOU_NAME_RYAKU = N'洗浄', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'滅菌', SHOBUN_HOUHOU_NAME_RYAKU = N'滅菌', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'消毒', SHOBUN_HOUHOU_NAME_RYAKU = N'消毒', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'煮沸', SHOBUN_HOUHOU_NAME_RYAKU = N'煮沸', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'破砕・圧縮固化', SHOBUN_HOUHOU_NAME_RYAKU = N'破砕・圧縮固化', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'溶融固化', SHOBUN_HOUHOU_NAME_RYAKU = N'溶融固化', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'その他中間処理', SHOBUN_HOUHOU_NAME_RYAKU = N'その他中間処理', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'最終処分', SHOBUN_HOUHOU_NAME_RYAKU = N'最終処分', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'埋立処分', SHOBUN_HOUHOU_NAME_RYAKU = N'埋立処分', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'安定型埋立処分', SHOBUN_HOUHOU_NAME_RYAKU = N'安定型埋立処分', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'管理型埋立処分', SHOBUN_HOUHOU_NAME_RYAKU = N'管理型埋立処分', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'遮断型埋立処分', SHOBUN_HOUHOU_NAME_RYAKU = N'遮断型埋立処分', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'海洋投入', SHOBUN_HOUHOU_NAME_RYAKU = N'海洋投入', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'生物', SHOBUN_HOUHOU_NAME_RYAKU = N'生物', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'売却（製鋼原料）', SHOBUN_HOUHOU_NAME_RYAKU = N'売却（製鋼原料）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'堆肥化', SHOBUN_HOUHOU_NAME_RYAKU = N'堆肥化', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SHOBUN_HOUHOU)
UPDATE T SET SHOBUN_HOUHOU_NAME = N'テスト処分', SHOBUN_HOUHOU_NAME_RYAKU = N'テスト処分', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 38;

