-- UPDATE script for table M_SYS_INFO (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 1

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_SYS_INFO)
UPDATE T SET MANIFEST_PRINTERMAKERNAME = NULL, MANIFEST_PRINTERNAME = NULL, BUSHO_NAME_PRINT = N'1', CREATE_USER = N'edison', UPDATE_USER = N'鈴木　次郎', DB_INXS_SUBAPP_CONNECT_NAME = N'SubAppDB', WAN_SIGN_FIELD_NAME_1 = NULL, WAN_SIGN_FIELD_NAME_2 = NULL, WAN_SIGN_FIELD_NAME_3 = NULL, WAN_SIGN_FIELD_NAME_4 = NULL, WAN_SIGN_FIELD_NAME_5 = NULL, SHARYOU_NAME_INGI = N'2', SHIHARAI_SHARYOU_NAME_INGI = N'1' WHERE rn = 1;

