-- UPDATE script for table M_TANKA_GROUP (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 5

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TANKA_GROUP)
UPDATE T SET TANKA_GROUP_NAME = N'騾壼ｸｸ', TANKA_GROUP_NAME_RYAKU = N'騾壼ｸｸ', TANKA_GROUP_FURIGANA = N'ツウジョウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TANKA_GROUP)
UPDATE T SET TANKA_GROUP_NAME = N'B', TANKA_GROUP_NAME_RYAKU = N'B', TANKA_GROUP_FURIGANA = N'Ｂ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TANKA_GROUP)
UPDATE T SET TANKA_GROUP_NAME = N'C', TANKA_GROUP_NAME_RYAKU = N'C', TANKA_GROUP_FURIGANA = N'Ｃ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TANKA_GROUP)
UPDATE T SET TANKA_GROUP_NAME = N'驕譁ｹ繧ｨ繝ｪ繧｢', TANKA_GROUP_NAME_RYAKU = N'驕譁ｹ繧ｨ繝ｪ繧｢', TANKA_GROUP_FURIGANA = N'エンポウエリア', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TANKA_GROUP)
UPDATE T SET TANKA_GROUP_NAME = N'騾壼ｸｸ', TANKA_GROUP_NAME_RYAKU = N'騾壼ｸｸ', TANKA_GROUP_FURIGANA = N'ツウジョウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

