-- UPDATE script for table M_TORIHIKI_KBN (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 2

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TORIHIKI_KBN)
UPDATE T SET TORIHIKI_KBN_NAME = N'現金', TORIHIKI_KBN_NAME_RYAKU = N'現金', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TORIHIKI_KBN)
UPDATE T SET TORIHIKI_KBN_NAME = N'掛け', TORIHIKI_KBN_NAME_RYAKU = N'掛け', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

