-- UPDATE script for table M_TODOUFUKEN (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 47

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'北海道', TODOUFUKEN_NAME_RYAKU = N'北海道', TODOUFUKEN_NAME_FURIGANA = N'ホッカイドウ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'青森県', TODOUFUKEN_NAME_RYAKU = N'青森県', TODOUFUKEN_NAME_FURIGANA = N'アオモリケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'岩手県', TODOUFUKEN_NAME_RYAKU = N'岩手県', TODOUFUKEN_NAME_FURIGANA = N'イワテケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'宮城県', TODOUFUKEN_NAME_RYAKU = N'宮城県', TODOUFUKEN_NAME_FURIGANA = N'ミヤギケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'秋田県', TODOUFUKEN_NAME_RYAKU = N'秋田県', TODOUFUKEN_NAME_FURIGANA = N'アキタケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'山形県', TODOUFUKEN_NAME_RYAKU = N'山形県', TODOUFUKEN_NAME_FURIGANA = N'ヤマガタケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'福島県', TODOUFUKEN_NAME_RYAKU = N'福島県', TODOUFUKEN_NAME_FURIGANA = N'フクシマケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'茨城県', TODOUFUKEN_NAME_RYAKU = N'茨城県', TODOUFUKEN_NAME_FURIGANA = N'イバラキケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'栃木県', TODOUFUKEN_NAME_RYAKU = N'栃木県', TODOUFUKEN_NAME_FURIGANA = N'トチギケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'群馬県', TODOUFUKEN_NAME_RYAKU = N'群馬県', TODOUFUKEN_NAME_FURIGANA = N'グンマケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'埼玉県', TODOUFUKEN_NAME_RYAKU = N'埼玉県', TODOUFUKEN_NAME_FURIGANA = N'サイタマケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'千葉県', TODOUFUKEN_NAME_RYAKU = N'千葉県', TODOUFUKEN_NAME_FURIGANA = N'チバケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'東京都', TODOUFUKEN_NAME_RYAKU = N'東京都', TODOUFUKEN_NAME_FURIGANA = N'トウキョウト', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'神奈川県', TODOUFUKEN_NAME_RYAKU = N'神奈川県', TODOUFUKEN_NAME_FURIGANA = N'カナガワケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'新潟県', TODOUFUKEN_NAME_RYAKU = N'新潟県', TODOUFUKEN_NAME_FURIGANA = N'ニイガタケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'富山県', TODOUFUKEN_NAME_RYAKU = N'富山県', TODOUFUKEN_NAME_FURIGANA = N'トヤマケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'石川県', TODOUFUKEN_NAME_RYAKU = N'石川県', TODOUFUKEN_NAME_FURIGANA = N'イシカワケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'福井県', TODOUFUKEN_NAME_RYAKU = N'福井県', TODOUFUKEN_NAME_FURIGANA = N'フクイケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'山梨県', TODOUFUKEN_NAME_RYAKU = N'山梨県', TODOUFUKEN_NAME_FURIGANA = N'ヤマナシケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'長野県', TODOUFUKEN_NAME_RYAKU = N'長野県', TODOUFUKEN_NAME_FURIGANA = N'ナガノケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'岐阜県', TODOUFUKEN_NAME_RYAKU = N'岐阜県', TODOUFUKEN_NAME_FURIGANA = N'ギフケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'静岡県', TODOUFUKEN_NAME_RYAKU = N'静岡県', TODOUFUKEN_NAME_FURIGANA = N'シズオカケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'愛知県', TODOUFUKEN_NAME_RYAKU = N'愛知県', TODOUFUKEN_NAME_FURIGANA = N'アイチケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'三重県', TODOUFUKEN_NAME_RYAKU = N'三重県', TODOUFUKEN_NAME_FURIGANA = N'ミエケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'滋賀県', TODOUFUKEN_NAME_RYAKU = N'滋賀県', TODOUFUKEN_NAME_FURIGANA = N'シガケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'京都府', TODOUFUKEN_NAME_RYAKU = N'京都府', TODOUFUKEN_NAME_FURIGANA = N'キョウトフ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'大阪府', TODOUFUKEN_NAME_RYAKU = N'大阪府', TODOUFUKEN_NAME_FURIGANA = N'オオサカフ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'兵庫県', TODOUFUKEN_NAME_RYAKU = N'兵庫県', TODOUFUKEN_NAME_FURIGANA = N'ヒョウゴケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'奈良県', TODOUFUKEN_NAME_RYAKU = N'奈良県', TODOUFUKEN_NAME_FURIGANA = N'ナラケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'和歌山県', TODOUFUKEN_NAME_RYAKU = N'和歌山県', TODOUFUKEN_NAME_FURIGANA = N'ワカヤマケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'鳥取県', TODOUFUKEN_NAME_RYAKU = N'鳥取県', TODOUFUKEN_NAME_FURIGANA = N'トットリケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'島根県', TODOUFUKEN_NAME_RYAKU = N'島根県', TODOUFUKEN_NAME_FURIGANA = N'シマネケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'岡山県', TODOUFUKEN_NAME_RYAKU = N'岡山県', TODOUFUKEN_NAME_FURIGANA = N'オカヤマケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'広島県', TODOUFUKEN_NAME_RYAKU = N'広島県', TODOUFUKEN_NAME_FURIGANA = N'ヒロシマケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'山口県', TODOUFUKEN_NAME_RYAKU = N'山口県', TODOUFUKEN_NAME_FURIGANA = N'ヤマグチケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'徳島県', TODOUFUKEN_NAME_RYAKU = N'徳島県', TODOUFUKEN_NAME_FURIGANA = N'トクシマケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'香川県', TODOUFUKEN_NAME_RYAKU = N'香川県', TODOUFUKEN_NAME_FURIGANA = N'カガワケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'愛媛県', TODOUFUKEN_NAME_RYAKU = N'愛媛県', TODOUFUKEN_NAME_FURIGANA = N'エヒメケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'高知県', TODOUFUKEN_NAME_RYAKU = N'高知県', TODOUFUKEN_NAME_FURIGANA = N'コウチケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'福岡県', TODOUFUKEN_NAME_RYAKU = N'福岡県', TODOUFUKEN_NAME_FURIGANA = N'フクオカケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'佐賀県', TODOUFUKEN_NAME_RYAKU = N'佐賀県', TODOUFUKEN_NAME_FURIGANA = N'サガケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'長崎県', TODOUFUKEN_NAME_RYAKU = N'長崎県', TODOUFUKEN_NAME_FURIGANA = N'ナガサキケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'熊本県', TODOUFUKEN_NAME_RYAKU = N'熊本県', TODOUFUKEN_NAME_FURIGANA = N'クマモトケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'大分県', TODOUFUKEN_NAME_RYAKU = N'大分県', TODOUFUKEN_NAME_FURIGANA = N'オオイタケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'宮崎県', TODOUFUKEN_NAME_RYAKU = N'宮崎県', TODOUFUKEN_NAME_FURIGANA = N'ミヤザキケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'鹿児島県', TODOUFUKEN_NAME_RYAKU = N'鹿児島県', TODOUFUKEN_NAME_FURIGANA = N'カゴシマケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_TODOUFUKEN)
UPDATE T SET TODOUFUKEN_NAME = N'沖縄県', TODOUFUKEN_NAME_RYAKU = N'沖縄県', TODOUFUKEN_NAME_FURIGANA = N'オキナワケン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 47;

