-- UPDATE script for table M_UNIT (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 29

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'ｔ', UNIT_NAME_RYAKU = N'ｔ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'm3', UNIT_NAME_RYAKU = N'm3', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'kg', UNIT_NAME_RYAKU = N'kg', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'ﾘｯﾄﾙ', UNIT_NAME_RYAKU = N'ﾘｯﾄﾙ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'個・台', UNIT_NAME_RYAKU = N'個・台', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'枚', UNIT_NAME_RYAKU = N'枚', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'式', UNIT_NAME_RYAKU = N'式', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'回', UNIT_NAME_RYAKU = N'回', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'本', UNIT_NAME_RYAKU = N'本', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'袋', UNIT_NAME_RYAKU = N'袋', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'ｹｰｽ', UNIT_NAME_RYAKU = N'ｹｰｽ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'車', UNIT_NAME_RYAKU = N'車', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'個', UNIT_NAME_RYAKU = N'個', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'台', UNIT_NAME_RYAKU = N'台', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'ｈ', UNIT_NAME_RYAKU = N'ｈ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'IBC01', UNIT_NAME_RYAKU = N'IBC01', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'Trip', UNIT_NAME_RYAKU = N'Trip', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'contai', UNIT_NAME_RYAKU = N'contai', CREATE_USER = N'竹ノ内　豊', UPDATE_USER = N'竹ノ内　豊' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'日', UNIT_NAME_RYAKU = N'日', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'ｋｇ', UNIT_NAME_RYAKU = N'ｋｇ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'バラ', UNIT_NAME_RYAKU = N'バラ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'ﾌﾚｺﾝ', UNIT_NAME_RYAKU = N'ﾌﾚｺﾝ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'カーゴ', UNIT_NAME_RYAKU = N'カーゴ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'缶', UNIT_NAME_RYAKU = N'缶', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'G', UNIT_NAME_RYAKU = N'ガロン', CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'3t車', UNIT_NAME_RYAKU = N'3t車', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'4tC', UNIT_NAME_RYAKU = N'4tC', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'㎥3', UNIT_NAME_RYAKU = N'㎥3', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNIT)
UPDATE T SET UNIT_NAME = N'㎥', UNIT_NAME_RYAKU = N'㎥', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 29;

