-- UPDATE script for table M_UNPAN_HOUHOU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 5

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNPAN_HOUHOU)
UPDATE T SET UNPAN_HOUHOU_NAME = N'車両', UNPAN_HOUHOU_NAME_RYAKU = N'車両', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNPAN_HOUHOU)
UPDATE T SET UNPAN_HOUHOU_NAME = N'船舶', UNPAN_HOUHOU_NAME_RYAKU = N'船舶', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNPAN_HOUHOU)
UPDATE T SET UNPAN_HOUHOU_NAME = N'鉄道', UNPAN_HOUHOU_NAME_RYAKU = N'鉄道', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNPAN_HOUHOU)
UPDATE T SET UNPAN_HOUHOU_NAME = N'その他', UNPAN_HOUHOU_NAME_RYAKU = N'その他', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNPAN_HOUHOU)
UPDATE T SET UNPAN_HOUHOU_NAME = N'4ｔＵ', UNPAN_HOUHOU_NAME_RYAKU = N'4ｔＵ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

