-- UPDATE script for table M_UNCHIN_TANKA (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 5

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNCHIN_TANKA)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNCHIN_HINMEI_NAME = N'高速代', UNIT_NAME = N'台', SHASHU_NAME = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNCHIN_TANKA)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'赤松運輸', UNCHIN_HINMEI_NAME = N'高速代', UNIT_NAME = N'kg', SHASHU_NAME = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNCHIN_TANKA)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'赤松運輸', UNCHIN_HINMEI_NAME = N'燃料代', UNIT_NAME = N'kg', SHASHU_NAME = N'2tダンプ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNCHIN_TANKA)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'エジソン商事', UNCHIN_HINMEI_NAME = N'収集運搬費用', UNIT_NAME = N'車', SHASHU_NAME = N'', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNCHIN_TANKA)
UPDATE T SET UNPAN_GYOUSHA_NAME = N'ウベ運輸', UNCHIN_HINMEI_NAME = N'高速代', UNIT_NAME = N'回', SHASHU_NAME = N'4tダンプ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 5;

