-- UPDATE script for table M_UNCHIN_HINMEI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 6

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNCHIN_HINMEI)
UPDATE T SET UNCHIN_HINMEI_NAME = N'高速代', UNCHIN_HINMEI_FURIGANA = N'コウソクダイ', UNIT_NAME = N'回', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNCHIN_HINMEI)
UPDATE T SET UNCHIN_HINMEI_NAME = N'燃料代', UNCHIN_HINMEI_FURIGANA = N'ネンリョウダイ', UNIT_NAME = N'台', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNCHIN_HINMEI)
UPDATE T SET UNCHIN_HINMEI_NAME = N'収集運搬費用', UNCHIN_HINMEI_FURIGANA = N'シュウシュウ', UNIT_NAME = N'車', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNCHIN_HINMEI)
UPDATE T SET UNCHIN_HINMEI_NAME = N'車検代', UNCHIN_HINMEI_FURIGANA = N'シャケンダｋダイ', UNIT_NAME = N'式', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNCHIN_HINMEI)
UPDATE T SET UNCHIN_HINMEI_NAME = N'車両整備費', UNCHIN_HINMEI_FURIGANA = N'シャリョウセイビヒ', UNIT_NAME = N'式', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_UNCHIN_HINMEI)
UPDATE T SET UNCHIN_HINMEI_NAME = N'タイヤ交換', UNCHIN_HINMEI_FURIGANA = N'タイヤコウカン', UNIT_NAME = N'式', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

