-- UPDATE script for table M_WANSIGN_KEIYAKU_INFO (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 12

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WANSIGN_KEIYAKU_INFO)
UPDATE T SET DOCUMENT_NAME = N'20310330-003-つくばね食品_運搬委託契約書', POST_NM = N'ソリューション営業部　ソリューション支援課', NAME_NM = N'柴　裕喜', PARENT_DOCUMENT_NAME = N'', CHILD_DOCUMENT_NAME = N'', REGISTERED_USER_NAME = N'柴裕喜', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WANSIGN_KEIYAKU_INFO)
UPDATE T SET DOCUMENT_NAME = N'220404_1_運搬委託契約_ワトソンズ', POST_NM = N'ソリューション営業部', NAME_NM = N'エジソン　太郎', PARENT_DOCUMENT_NAME = N'', CHILD_DOCUMENT_NAME = N'', REGISTERED_USER_NAME = N'エジソン　太郎', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WANSIGN_KEIYAKU_INFO)
UPDATE T SET DOCUMENT_NAME = N'三條建設様_建廃委託契約書_99999', POST_NM = N'ソリューション営業部　ソリューション支援課', NAME_NM = N'柴裕喜', PARENT_DOCUMENT_NAME = N'', CHILD_DOCUMENT_NAME = N'', REGISTERED_USER_NAME = N'柴裕喜', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WANSIGN_KEIYAKU_INFO)
UPDATE T SET DOCUMENT_NAME = N'カミツ鉄工様_産廃委託契約書_9999', POST_NM = N'ソリューション営業部　ソリューション支援課', NAME_NM = N'柴裕喜', PARENT_DOCUMENT_NAME = N'', CHILD_DOCUMENT_NAME = N'', REGISTERED_USER_NAME = N'柴裕喜', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WANSIGN_KEIYAKU_INFO)
UPDATE T SET DOCUMENT_NAME = N'運搬許可_東京_013', POST_NM = N'ソリューション営業部', NAME_NM = N'エジソン　太郎', PARENT_DOCUMENT_NAME = N'', CHILD_DOCUMENT_NAME = N'', REGISTERED_USER_NAME = N'エジソン　太郎', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WANSIGN_KEIYAKU_INFO)
UPDATE T SET DOCUMENT_NAME = N'産廃委託契約書_吉田環境', POST_NM = N'ソリューション営業部　ソリューション支援課', NAME_NM = N'柴裕喜', PARENT_DOCUMENT_NAME = N'', CHILD_DOCUMENT_NAME = N'', REGISTERED_USER_NAME = N'柴裕喜', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WANSIGN_KEIYAKU_INFO)
UPDATE T SET DOCUMENT_NAME = N'さくら歯科医院_30_委託契約書', POST_NM = N'ソリューション営業部', NAME_NM = N'エジソン　太郎', PARENT_DOCUMENT_NAME = N'', CHILD_DOCUMENT_NAME = N'', REGISTERED_USER_NAME = N'エジソン　太郎', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WANSIGN_KEIYAKU_INFO)
UPDATE T SET DOCUMENT_NAME = N'三條建設様_建廃委託契約書_99999', POST_NM = N'ソリューション営業部　ソリューション支援課', NAME_NM = N'柴裕喜', PARENT_DOCUMENT_NAME = N'', CHILD_DOCUMENT_NAME = N'', REGISTERED_USER_NAME = N'柴裕喜', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WANSIGN_KEIYAKU_INFO)
UPDATE T SET DOCUMENT_NAME = N'産廃委託契約書_二五商事', POST_NM = N'ソリューション営業部', NAME_NM = N'エジソン　太郎', PARENT_DOCUMENT_NAME = N'', CHILD_DOCUMENT_NAME = N'', REGISTERED_USER_NAME = N'エジソン　太郎', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WANSIGN_KEIYAKU_INFO)
UPDATE T SET DOCUMENT_NAME = N'産業廃棄物収集・運搬及び処分委託契約書(えじそん商事株式会社)', POST_NM = N'ソリューション営業部', NAME_NM = N'エジソン　太郎', PARENT_DOCUMENT_NAME = N'', CHILD_DOCUMENT_NAME = N'', REGISTERED_USER_NAME = N'エジソン　太郎', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WANSIGN_KEIYAKU_INFO)
UPDATE T SET DOCUMENT_NAME = N'WAN-Sign_サービス説明資料', POST_NM = N'', NAME_NM = N'', PARENT_DOCUMENT_NAME = N'', CHILD_DOCUMENT_NAME = N'', REGISTERED_USER_NAME = N'エジソン　太郎', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WANSIGN_KEIYAKU_INFO)
UPDATE T SET DOCUMENT_NAME = N'リコージャパン_覚書_群馬県処分業者', POST_NM = N'', NAME_NM = N'', PARENT_DOCUMENT_NAME = N'', CHILD_DOCUMENT_NAME = N'', REGISTERED_USER_NAME = N'エジソン　太郎', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 12;

