-- UPDATE script for table M_WORK_CLOSED_SHARYOU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 7

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WORK_CLOSED_SHARYOU)
UPDATE T SET CREATE_USER = N'西田　栄一', UPDATE_USER = N'西田　栄一' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WORK_CLOSED_SHARYOU)
UPDATE T SET CREATE_USER = N'やまだ', UPDATE_USER = N'やまだ' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WORK_CLOSED_SHARYOU)
UPDATE T SET CREATE_USER = N'やまだ', UPDATE_USER = N'やまだ' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WORK_CLOSED_SHARYOU)
UPDATE T SET CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'やまだ' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WORK_CLOSED_SHARYOU)
UPDATE T SET CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WORK_CLOSED_SHARYOU)
UPDATE T SET CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_WORK_CLOSED_SHARYOU)
UPDATE T SET CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

