-- UPDATE script for table M_YOUKI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 8

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YOUKI)
UPDATE T SET YOUKI_NAME = N'BOX', YOUKI_NAME_RYAKU = N'BOX', YOUKI_FURIGANA = N'ＢＯＸ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YOUKI)
UPDATE T SET YOUKI_NAME = N'木パレ', YOUKI_NAME_RYAKU = N'木パレ', YOUKI_FURIGANA = N'モクパレ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YOUKI)
UPDATE T SET YOUKI_NAME = N'1100パレット', YOUKI_NAME_RYAKU = N'1100パレッ', YOUKI_FURIGANA = N'１１００パレット', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YOUKI)
UPDATE T SET YOUKI_NAME = N'コンテナ風袋', YOUKI_NAME_RYAKU = N'コンテナ風', YOUKI_FURIGANA = N'コンテナフウタイ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YOUKI)
UPDATE T SET YOUKI_NAME = N'パレットＡ（浅沼運輸', YOUKI_NAME_RYAKU = N'パレットＡ', YOUKI_FURIGANA = N'パレットアサヌマウン', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YOUKI)
UPDATE T SET YOUKI_NAME = N'パレットＢ（浅沼運輸', YOUKI_NAME_RYAKU = N'パレットＢ', YOUKI_FURIGANA = N'パレットｂアサヌマウ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YOUKI)
UPDATE T SET YOUKI_NAME = N'ようき', YOUKI_NAME_RYAKU = N'ようき', YOUKI_FURIGANA = N'ヨウキ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YOUKI)
UPDATE T SET YOUKI_NAME = N'サンプル', YOUKI_NAME_RYAKU = N'サンプル', YOUKI_FURIGANA = N'サンプル', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 8;

