-- UPDATE script for table M_YUUGAI_BUSSHITSU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 25

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'水銀又はその化合物', YUUGAI_BUSSHITSU_NAME_RYAKU = N'水銀', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'カドミウム又はその化合物', YUUGAI_BUSSHITSU_NAME_RYAKU = N'カドミウム', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'鉛又はその化合物', YUUGAI_BUSSHITSU_NAME_RYAKU = N'鉛', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'有機燐化合物', YUUGAI_BUSSHITSU_NAME_RYAKU = N'有機燐', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'六価クロム化合物', YUUGAI_BUSSHITSU_NAME_RYAKU = N'六価クロム', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'砒素又はその化合物', YUUGAI_BUSSHITSU_NAME_RYAKU = N'砒素', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'シアン化合物', YUUGAI_BUSSHITSU_NAME_RYAKU = N'シアン化合物', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'ＰＣＢ', YUUGAI_BUSSHITSU_NAME_RYAKU = N'ＰＣＢ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'トリクロロエチレン', YUUGAI_BUSSHITSU_NAME_RYAKU = N'トリクロロエチレン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'テトラクロロエチレン', YUUGAI_BUSSHITSU_NAME_RYAKU = N'テトラクロロエチレン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'ジクロロメタン', YUUGAI_BUSSHITSU_NAME_RYAKU = N'ジクロロメタン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'四塩化炭素', YUUGAI_BUSSHITSU_NAME_RYAKU = N'四塩化炭素', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'１・２－ジクロロエタン', YUUGAI_BUSSHITSU_NAME_RYAKU = N'ジクロロエタン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'１・１－ジクロロエチレン', YUUGAI_BUSSHITSU_NAME_RYAKU = N'ジクロロエチレン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'シス－１・２－ジクロロエチレン', YUUGAI_BUSSHITSU_NAME_RYAKU = N'２．ジクロロエチレン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'１・１・１－トリクロロエタン', YUUGAI_BUSSHITSU_NAME_RYAKU = N'１．トリクロロエタン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'１・１・２－トリクロロエタン', YUUGAI_BUSSHITSU_NAME_RYAKU = N'２．トリクロロエタン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'１・３－ジクロロプロペン（Ｄ－Ｄ）', YUUGAI_BUSSHITSU_NAME_RYAKU = N'ジクロロプロペン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'チウラム', YUUGAI_BUSSHITSU_NAME_RYAKU = N'チウラム', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'シマジン（ＣＡＴ）', YUUGAI_BUSSHITSU_NAME_RYAKU = N'シマジン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'チオベンカルブ（ベンチオカーブ）', YUUGAI_BUSSHITSU_NAME_RYAKU = N'チオベンカルブ', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'ベンゼン', YUUGAI_BUSSHITSU_NAME_RYAKU = N'ベンゼン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'セレン又はその化合物', YUUGAI_BUSSHITSU_NAME_RYAKU = N'セレン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'ダイオキシン類（有機塩素化合物）', YUUGAI_BUSSHITSU_NAME_RYAKU = N'ダイオキシン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_YUUGAI_BUSSHITSU)
UPDATE T SET YUUGAI_BUSSHITSU_NAME = N'１，４－ジオキサン', YUUGAI_BUSSHITSU_NAME_RYAKU = N'４．ジオキサン', CREATE_USER = N'edison', UPDATE_USER = N'edison' WHERE rn = 25;

