-- UPDATE script for table M_ZAIKO_HINMEI (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 79

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'在庫Ａ', ZAIKO_HINMEI_NAME_RYAKU = N'在庫Ａ', ZAIKO_HINMEI_FURIGANA = N'ザイコＡ', UNIT_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'紙おむつ', ZAIKO_HINMEI_NAME_RYAKU = N'紙おむつ', ZAIKO_HINMEI_FURIGANA = N'カミオムツ', UNIT_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'紙おむつ（在庫）', ZAIKO_HINMEI_NAME_RYAKU = N'紙おむつ（在庫）', ZAIKO_HINMEI_FURIGANA = N'カミオムツザイコカミオムツカミオムツザイ', UNIT_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'ＨＳ', ZAIKO_HINMEI_NAME_RYAKU = N'ＨＳ', ZAIKO_HINMEI_FURIGANA = N'ＨＳ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'Ｈ１', ZAIKO_HINMEI_NAME_RYAKU = N'Ｈ１', ZAIKO_HINMEI_FURIGANA = N'Ｈ１', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'Ｈ２', ZAIKO_HINMEI_NAME_RYAKU = N'Ｈ２', ZAIKO_HINMEI_FURIGANA = N'Ｈ２', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'Ｈ３', ZAIKO_HINMEI_NAME_RYAKU = N'Ｈ３', ZAIKO_HINMEI_FURIGANA = N'Ｈ３', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'銅線', ZAIKO_HINMEI_NAME_RYAKU = N'銅線', ZAIKO_HINMEI_FURIGANA = N'ドウセン', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'銅屑', ZAIKO_HINMEI_NAME_RYAKU = N'銅屑', ZAIKO_HINMEI_FURIGANA = N'ドウクズ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'雑線', ZAIKO_HINMEI_NAME_RYAKU = N'雑線', ZAIKO_HINMEI_FURIGANA = N'ザッセン', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'ケーブル', ZAIKO_HINMEI_NAME_RYAKU = N'ケーブル', ZAIKO_HINMEI_FURIGANA = N'ケーブル', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'真鍮', ZAIKO_HINMEI_NAME_RYAKU = N'真鍮', ZAIKO_HINMEI_FURIGANA = N'シンチュウ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'砲金', ZAIKO_HINMEI_NAME_RYAKU = N'砲金', ZAIKO_HINMEI_FURIGANA = N'ホウキン', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'鉛屑', ZAIKO_HINMEI_NAME_RYAKU = N'鉛屑', ZAIKO_HINMEI_FURIGANA = N'ナマリクズ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'亜鉛屑', ZAIKO_HINMEI_NAME_RYAKU = N'亜鉛屑', ZAIKO_HINMEI_FURIGANA = N'アエンクズ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'ステンレス屑', ZAIKO_HINMEI_NAME_RYAKU = N'ステンレス屑', ZAIKO_HINMEI_FURIGANA = N'ステンレスクズ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'クローム', ZAIKO_HINMEI_NAME_RYAKU = N'クローム', ZAIKO_HINMEI_FURIGANA = N'クローム', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'アルミ屑', ZAIKO_HINMEI_NAME_RYAKU = N'アルミ屑', ZAIKO_HINMEI_FURIGANA = N'アルミクズ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'雑品', ZAIKO_HINMEI_NAME_RYAKU = N'雑品', ZAIKO_HINMEI_FURIGANA = N'ザッピン', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'配電盤', ZAIKO_HINMEI_NAME_RYAKU = N'配電盤', ZAIKO_HINMEI_FURIGANA = N'ハイデンバン', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'モーター', ZAIKO_HINMEI_NAME_RYAKU = N'モーター', ZAIKO_HINMEI_FURIGANA = N'モーター', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'エアコン', ZAIKO_HINMEI_NAME_RYAKU = N'エアコン', ZAIKO_HINMEI_FURIGANA = N'エアコン', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'バッテリー', ZAIKO_HINMEI_NAME_RYAKU = N'バッテリー', ZAIKO_HINMEI_FURIGANA = N'バッテリー', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'新断', ZAIKO_HINMEI_NAME_RYAKU = N'新断', ZAIKO_HINMEI_FURIGANA = N'シンタチ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'ギロ材Ａ', ZAIKO_HINMEI_NAME_RYAKU = N'ギロ材Ａ', ZAIKO_HINMEI_FURIGANA = N'ギロザイＡ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'ギロ材Ｂ', ZAIKO_HINMEI_NAME_RYAKU = N'ギロ材Ｂ', ZAIKO_HINMEI_FURIGANA = N'ギロザイＢ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'スチール缶', ZAIKO_HINMEI_NAME_RYAKU = N'スチール缶', ZAIKO_HINMEI_FURIGANA = N'スチールカン', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'一斗缶', ZAIKO_HINMEI_NAME_RYAKU = N'一斗缶', ZAIKO_HINMEI_FURIGANA = N'イットカン', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'ドラム缶', ZAIKO_HINMEI_NAME_RYAKU = N'ドラム缶', ZAIKO_HINMEI_FURIGANA = N'ドラムカン', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'シュレッダー', ZAIKO_HINMEI_NAME_RYAKU = N'シュレッダー', ZAIKO_HINMEI_FURIGANA = N'シュレッダー', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'アルミ缶', ZAIKO_HINMEI_NAME_RYAKU = N'アルミ缶', ZAIKO_HINMEI_FURIGANA = N'アルミカン', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'アルミ板', ZAIKO_HINMEI_NAME_RYAKU = N'アルミ板', ZAIKO_HINMEI_FURIGANA = N'アルミイタ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'級外', ZAIKO_HINMEI_NAME_RYAKU = N'級外', ZAIKO_HINMEI_FURIGANA = N'キュウガイ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'ダライ粉', ZAIKO_HINMEI_NAME_RYAKU = N'ダライ粉', ZAIKO_HINMEI_FURIGANA = N'ダライコ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'解体ステンレス', ZAIKO_HINMEI_NAME_RYAKU = N'解体ステンレス', ZAIKO_HINMEI_FURIGANA = N'カイタイステンレス', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'ステンレス粉', ZAIKO_HINMEI_NAME_RYAKU = N'ステンレス粉', ZAIKO_HINMEI_FURIGANA = N'ステンレスコ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'アルミ粉', ZAIKO_HINMEI_NAME_RYAKU = N'アルミ粉', ZAIKO_HINMEI_FURIGANA = N'アルミコ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'アルミホイル', ZAIKO_HINMEI_NAME_RYAKU = N'アルミホイル', ZAIKO_HINMEI_FURIGANA = N'アルミホイル', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'プラスチック', ZAIKO_HINMEI_NAME_RYAKU = N'プラスチック', ZAIKO_HINMEI_FURIGANA = N'プラスチック', UNIT_NAME = NULL, CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'13ステン', ZAIKO_HINMEI_NAME_RYAKU = N'13ステン', ZAIKO_HINMEI_FURIGANA = N'１３ステン', UNIT_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'18ステン', ZAIKO_HINMEI_NAME_RYAKU = N'18ステン', ZAIKO_HINMEI_FURIGANA = N'１８ステン', UNIT_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'ダンボール', ZAIKO_HINMEI_NAME_RYAKU = N'ダンボール', ZAIKO_HINMEI_FURIGANA = N'ダンボール', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'紙管', ZAIKO_HINMEI_NAME_RYAKU = N'紙管', ZAIKO_HINMEI_FURIGANA = N'シカン', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'クラフト紙', ZAIKO_HINMEI_NAME_RYAKU = N'クラフト紙', ZAIKO_HINMEI_FURIGANA = N'クラフトシ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'雑誌', ZAIKO_HINMEI_NAME_RYAKU = N'雑誌', ZAIKO_HINMEI_FURIGANA = N'ザッシ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'新聞', ZAIKO_HINMEI_NAME_RYAKU = N'新聞', ZAIKO_HINMEI_FURIGANA = N'シンブン', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'牛乳パック', ZAIKO_HINMEI_NAME_RYAKU = N'牛乳パック', ZAIKO_HINMEI_FURIGANA = N'ギュウニュウパック', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'上白', ZAIKO_HINMEI_NAME_RYAKU = N'上白', ZAIKO_HINMEI_FURIGANA = N'ジョウハク', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'中白', ZAIKO_HINMEI_NAME_RYAKU = N'中白', ZAIKO_HINMEI_FURIGANA = N'チュウハク', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'ミックス', ZAIKO_HINMEI_NAME_RYAKU = N'ミックス', ZAIKO_HINMEI_FURIGANA = N'ミックス', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'OA用紙A', ZAIKO_HINMEI_NAME_RYAKU = N'OA用紙A', ZAIKO_HINMEI_FURIGANA = N'ＯＡヨウシＡ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'OA用紙B', ZAIKO_HINMEI_NAME_RYAKU = N'OA用紙B', ZAIKO_HINMEI_FURIGANA = N'ＯＡヨウシＢ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'機密書類', ZAIKO_HINMEI_NAME_RYAKU = N'機密書類', ZAIKO_HINMEI_FURIGANA = N'キミツショルイ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'ちらし', ZAIKO_HINMEI_NAME_RYAKU = N'ちらし', ZAIKO_HINMEI_FURIGANA = N'チラシ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'色紙', ZAIKO_HINMEI_NAME_RYAKU = N'色紙', ZAIKO_HINMEI_FURIGANA = N'イロガミ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'シュレッター屑', ZAIKO_HINMEI_NAME_RYAKU = N'シュレッター屑', ZAIKO_HINMEI_FURIGANA = N'シュレッタークズ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'鈴木　次郎' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'ライナー', ZAIKO_HINMEI_NAME_RYAKU = N'ライナー', ZAIKO_HINMEI_FURIGANA = N'ライナー', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'ウエス', ZAIKO_HINMEI_NAME_RYAKU = N'ウエス', ZAIKO_HINMEI_FURIGANA = N'ウエス', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'再生紙', ZAIKO_HINMEI_NAME_RYAKU = N'再生紙', ZAIKO_HINMEI_FURIGANA = N'サイセイシ', UNIT_NAME = NULL, CREATE_USER = N'佐藤　花子', UPDATE_USER = N'中西　大樹' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'ノートパソコン処理代', ZAIKO_HINMEI_NAME_RYAKU = N'ノートパソコン処理代', ZAIKO_HINMEI_FURIGANA = N'ノートパソコンショリダイ', UNIT_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'ペレット', ZAIKO_HINMEI_NAME_RYAKU = N'ペレット', ZAIKO_HINMEI_FURIGANA = N'ペレット', UNIT_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'PC・ABS（白）　プレス', ZAIKO_HINMEI_NAME_RYAKU = N'PC･ABS(白) ﾌﾟﾚｽ', ZAIKO_HINMEI_FURIGANA = N'PC', UNIT_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 62;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'PC・ABS（白）　プレス', ZAIKO_HINMEI_NAME_RYAKU = N'PC・ABS（白プレ', ZAIKO_HINMEI_FURIGANA = N'PCABS', UNIT_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 63;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'ダスト', ZAIKO_HINMEI_NAME_RYAKU = N'ダスト', ZAIKO_HINMEI_FURIGANA = N'ダスト', UNIT_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 64;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'Bブロック', ZAIKO_HINMEI_NAME_RYAKU = N'Bブロック', ZAIKO_HINMEI_FURIGANA = N'Bブロック', UNIT_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 65;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'Aブロック', ZAIKO_HINMEI_NAME_RYAKU = N'Aブロック', ZAIKO_HINMEI_FURIGANA = N'Aブロック', UNIT_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 66;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'Cブロック', ZAIKO_HINMEI_NAME_RYAKU = N'Cブロック', ZAIKO_HINMEI_FURIGANA = N'ｃブロック', UNIT_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 67;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'一本線', ZAIKO_HINMEI_NAME_RYAKU = N'一本線', ZAIKO_HINMEI_FURIGANA = N'イッポンセン', UNIT_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 68;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'銅', ZAIKO_HINMEI_NAME_RYAKU = N'銅', ZAIKO_HINMEI_FURIGANA = N'ドウ', UNIT_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 69;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'プラ', ZAIKO_HINMEI_NAME_RYAKU = N'プラ', ZAIKO_HINMEI_FURIGANA = N'プラ', UNIT_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 70;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'電線', ZAIKO_HINMEI_NAME_RYAKU = N'電線', ZAIKO_HINMEI_FURIGANA = N'デンセン', UNIT_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 71;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'在庫Ａ', ZAIKO_HINMEI_NAME_RYAKU = N'在庫Ａ', ZAIKO_HINMEI_FURIGANA = N'ザイコＡ', UNIT_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 72;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'在庫Ｂ', ZAIKO_HINMEI_NAME_RYAKU = N'在庫Ｂ', ZAIKO_HINMEI_FURIGANA = N'ザイコＢ', UNIT_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 73;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'一本線', ZAIKO_HINMEI_NAME_RYAKU = N'一本線', ZAIKO_HINMEI_FURIGANA = N'イッポンセン', UNIT_NAME = NULL, CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 74;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'鉄（テスト用）', ZAIKO_HINMEI_NAME_RYAKU = N'鉄（テスト用）', ZAIKO_HINMEI_FURIGANA = N'テツテストヨウ', UNIT_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 75;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'鉄（テスト用）2', ZAIKO_HINMEI_NAME_RYAKU = N'鉄（テスト用）2', ZAIKO_HINMEI_FURIGANA = N'テツテストヨウ２２', UNIT_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 76;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'特級同屑', ZAIKO_HINMEI_NAME_RYAKU = N'特級同屑', ZAIKO_HINMEI_FURIGANA = N'トッキュウドウクズ', UNIT_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 77;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'一号同屑', ZAIKO_HINMEI_NAME_RYAKU = N'一号同屑', ZAIKO_HINMEI_FURIGANA = N'イチゴウドウクズ', UNIT_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 78;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HINMEI)
UPDATE T SET ZAIKO_HINMEI_NAME = N'鉄（テスト用）3', ZAIKO_HINMEI_NAME_RYAKU = N'鉄（テスト用）3', ZAIKO_HINMEI_FURIGANA = N'テツテストウヨウ３', UNIT_NAME = NULL, CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 79;

