-- UPDATE script for table M_ZAIKO_HIRITSU (columns containing NAME, TEL, FAX, POST, ADDRESS, TANTOU, CREATE_USER, UPDATE_USER, FURIGANA)
-- Số dòng dữ liệu: 137

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', ZAIKO_HINMEI_NAME = N'ＨＳ', CREATE_USER = N'佐藤　花子', UPDATE_USER = N'新川　拓哉' WHERE rn = 1;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', ZAIKO_HINMEI_NAME = N'Ｈ１', CREATE_USER = N'佐藤　花子', UPDATE_USER = N'新川　拓哉' WHERE rn = 2;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'廃プラ', ZAIKO_HINMEI_NAME = N'Ｈ３', CREATE_USER = N'院玖珠　太朗', UPDATE_USER = N'やまだ' WHERE rn = 3;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'廃プラ', ZAIKO_HINMEI_NAME = N'銅線', CREATE_USER = N'院玖珠　太朗', UPDATE_USER = N'やまだ' WHERE rn = 4;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'木くず', ZAIKO_HINMEI_NAME = N'ＨＳ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 5;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'木くず', ZAIKO_HINMEI_NAME = N'雑線', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 6;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'金属くず', ZAIKO_HINMEI_NAME = N'雑線', CREATE_USER = N'安田　彬', UPDATE_USER = N'鈴木　次郎' WHERE rn = 7;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'金属くず', ZAIKO_HINMEI_NAME = N'雑品', CREATE_USER = N'やまだ', UPDATE_USER = N'やまだ' WHERE rn = 8;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'金属くず', ZAIKO_HINMEI_NAME = N'鉄（テスト用）', CREATE_USER = N'安田　彬', UPDATE_USER = N'やまだ' WHERE rn = 9;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'混合廃棄物', ZAIKO_HINMEI_NAME = N'Bブロック', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 10;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'混合廃棄物A', ZAIKO_HINMEI_NAME = N'Bブロック', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 11;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'混合廃棄物A', ZAIKO_HINMEI_NAME = N'Aブロック', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 12;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'混合廃棄物A', ZAIKO_HINMEI_NAME = N'Cブロック', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 13;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'焼却灰', ZAIKO_HINMEI_NAME = N'在庫Ａ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 14;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'デスクトップパソコン', ZAIKO_HINMEI_NAME = N'配電盤', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 15;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'デスクトップパソコン', ZAIKO_HINMEI_NAME = N'モーター', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 16;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'デスクトップパソコン', ZAIKO_HINMEI_NAME = N'バッテリー', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 17;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'紙おむつ', ZAIKO_HINMEI_NAME = N'紙おむつ（在庫）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 18;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'金属くず', ZAIKO_HINMEI_NAME = N'ＨＳ', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 19;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'金属くず', ZAIKO_HINMEI_NAME = N'Ｈ２', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 20;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ＨＳ', ZAIKO_HINMEI_NAME = N'ＨＳ', CREATE_USER = N'中西　大樹', UPDATE_USER = N'鈴木　次郎' WHERE rn = 21;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ＨＳ', ZAIKO_HINMEI_NAME = N'Ｈ２', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 22;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'Ｈ１', ZAIKO_HINMEI_NAME = N'Ｈ１', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 23;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'Ｈ２', ZAIKO_HINMEI_NAME = N'Ｈ２', CREATE_USER = N'中西　大樹', UPDATE_USER = N'鈴木　次郎' WHERE rn = 24;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'Ｈ３', ZAIKO_HINMEI_NAME = N'Ｈ３', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 25;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'銅線（1号）', ZAIKO_HINMEI_NAME = N'銅線', CREATE_USER = N'中西　大樹', UPDATE_USER = N'鈴木　次郎' WHERE rn = 26;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'銅線（1号）', ZAIKO_HINMEI_NAME = N'銅屑', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'鈴木　次郎' WHERE rn = 27;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'銅屑', ZAIKO_HINMEI_NAME = N'銅屑', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 28;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'雑線', ZAIKO_HINMEI_NAME = N'雑線', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 29;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ケーブル', ZAIKO_HINMEI_NAME = N'ケーブル', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 30;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'真鍮', ZAIKO_HINMEI_NAME = N'真鍮', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 31;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'砲金', ZAIKO_HINMEI_NAME = N'砲金', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 32;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'鉛屑', ZAIKO_HINMEI_NAME = N'鉛屑', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 33;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'亜鉛屑', ZAIKO_HINMEI_NAME = N'亜鉛屑', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 34;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ステンレス屑', ZAIKO_HINMEI_NAME = N'ステンレス屑', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 35;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'クローム', ZAIKO_HINMEI_NAME = N'クローム', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 36;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'アルミ屑', ZAIKO_HINMEI_NAME = N'アルミ屑', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 37;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'雑品', ZAIKO_HINMEI_NAME = N'雑品', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 38;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'配電盤', ZAIKO_HINMEI_NAME = N'ステンレス屑', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 39;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'配電盤', ZAIKO_HINMEI_NAME = N'プラスチック', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 40;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'モーター', ZAIKO_HINMEI_NAME = N'モーター', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 41;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'エアコン', ZAIKO_HINMEI_NAME = N'銅線', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 42;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'エアコン', ZAIKO_HINMEI_NAME = N'アルミ屑', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 43;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'エアコン', ZAIKO_HINMEI_NAME = N'プラスチック', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 44;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'バッテリー', ZAIKO_HINMEI_NAME = N'鉛屑', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 45;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'バッテリー', ZAIKO_HINMEI_NAME = N'プラスチック', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 46;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'新断', ZAIKO_HINMEI_NAME = N'新断', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 47;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ギロ材Ａ', ZAIKO_HINMEI_NAME = N'ギロ材Ａ', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 48;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ギロ材Ｂ', ZAIKO_HINMEI_NAME = N'ギロ材Ｂ', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 49;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'スチール缶', ZAIKO_HINMEI_NAME = N'スチール缶', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 50;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'一斗缶', ZAIKO_HINMEI_NAME = N'スチール缶', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 51;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ドラム缶', ZAIKO_HINMEI_NAME = N'ドラム缶', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 52;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'アルミ缶', ZAIKO_HINMEI_NAME = N'アルミ缶', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 53;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'アルミ板', ZAIKO_HINMEI_NAME = N'アルミ板', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 54;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ダライ粉', ZAIKO_HINMEI_NAME = N'ダライ粉', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 55;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'パーマ', ZAIKO_HINMEI_NAME = N'鉄（テスト用）3', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 56;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'13ステン', ZAIKO_HINMEI_NAME = N'13ステン', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 57;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'18ステン', ZAIKO_HINMEI_NAME = N'18ステン', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 58;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'銅線（特級銅屑60・一', ZAIKO_HINMEI_NAME = N'特級同屑', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 59;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'銅線（特級銅屑60・一', ZAIKO_HINMEI_NAME = N'一号同屑', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 60;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ダンボール', ZAIKO_HINMEI_NAME = N'ダンボール', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 61;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'紙管', ZAIKO_HINMEI_NAME = N'紙管', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 62;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'クラフト紙', ZAIKO_HINMEI_NAME = N'クラフト紙', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 63;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'雑誌', ZAIKO_HINMEI_NAME = N'雑誌', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 64;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'新聞', ZAIKO_HINMEI_NAME = N'新聞', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 65;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'牛乳パック', ZAIKO_HINMEI_NAME = N'牛乳パック', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 66;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'上白', ZAIKO_HINMEI_NAME = N'上白', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 67;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'中白', ZAIKO_HINMEI_NAME = N'中白', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 68;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ミックス', ZAIKO_HINMEI_NAME = N'ミックス', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 69;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'OA用紙A', ZAIKO_HINMEI_NAME = N'OA用紙A', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 70;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'OA用紙B', ZAIKO_HINMEI_NAME = N'OA用紙B', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 71;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'機密書類', ZAIKO_HINMEI_NAME = N'機密書類', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 72;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ちらし', ZAIKO_HINMEI_NAME = N'ちらし', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 73;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'色紙', ZAIKO_HINMEI_NAME = N'色紙', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 74;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'シュレッター屑', ZAIKO_HINMEI_NAME = N'シュレッター屑', CREATE_USER = N'中西　大樹', UPDATE_USER = N'鈴木　次郎' WHERE rn = 75;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ライナー', ZAIKO_HINMEI_NAME = N'ライナー', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 76;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ウエス', ZAIKO_HINMEI_NAME = N'ウエス', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 77;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'再生紙', ZAIKO_HINMEI_NAME = N'再生紙', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 78;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ペットボトル', ZAIKO_HINMEI_NAME = N'ペレット', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'鈴木　次郎' WHERE rn = 79;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'一本線', ZAIKO_HINMEI_NAME = N'銅', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 80;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'一本線', ZAIKO_HINMEI_NAME = N'プラ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 81;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'電線', ZAIKO_HINMEI_NAME = N'電線', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 82;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'電線ＡＢ', ZAIKO_HINMEI_NAME = N'在庫Ａ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 83;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'電線ＡＢ', ZAIKO_HINMEI_NAME = N'在庫Ｂ', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 84;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'一本線', ZAIKO_HINMEI_NAME = N'一本線', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 85;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', ZAIKO_HINMEI_NAME = N'ケーブル', CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 86;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'廃プラスチック類', ZAIKO_HINMEI_NAME = N'真鍮', CREATE_USER = N'佐藤　花子', UPDATE_USER = N'佐藤　花子' WHERE rn = 87;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'紙おむつ', ZAIKO_HINMEI_NAME = N'紙おむつ（在庫）', CREATE_USER = N'鈴木　次郎', UPDATE_USER = N'新川　拓哉' WHERE rn = 88;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ＨＳ', ZAIKO_HINMEI_NAME = N'ＨＳ', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 89;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'Ｈ１', ZAIKO_HINMEI_NAME = N'鉄（テスト用）', CREATE_USER = N'中西　大樹', UPDATE_USER = N'鈴木　次郎' WHERE rn = 90;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'Ｈ２', ZAIKO_HINMEI_NAME = N'Ｈ２', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 91;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'Ｈ３', ZAIKO_HINMEI_NAME = N'Ｈ３', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 92;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'銅線', ZAIKO_HINMEI_NAME = N'銅線', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 93;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'銅屑', ZAIKO_HINMEI_NAME = N'銅屑', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 94;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'雑線', ZAIKO_HINMEI_NAME = N'雑線', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 95;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ケーブル', ZAIKO_HINMEI_NAME = N'ケーブル', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 96;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'真鍮', ZAIKO_HINMEI_NAME = N'真鍮', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 97;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'砲金', ZAIKO_HINMEI_NAME = N'砲金', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 98;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'鉛屑', ZAIKO_HINMEI_NAME = N'鉛屑', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 99;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'亜鉛屑', ZAIKO_HINMEI_NAME = N'亜鉛屑', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 100;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ステンレス屑', ZAIKO_HINMEI_NAME = N'ステンレス屑', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 101;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'クローム', ZAIKO_HINMEI_NAME = N'クローム', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 102;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'アルミ屑', ZAIKO_HINMEI_NAME = N'アルミ屑', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 103;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'雑品', ZAIKO_HINMEI_NAME = N'雑品', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 104;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'配電盤', ZAIKO_HINMEI_NAME = N'配電盤', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 105;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'モーター', ZAIKO_HINMEI_NAME = N'モーター', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 106;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'エアコン', ZAIKO_HINMEI_NAME = N'エアコン', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 107;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'バッテリー', ZAIKO_HINMEI_NAME = N'バッテリー', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 108;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'アルミ缶', ZAIKO_HINMEI_NAME = N'アルミ缶', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 109;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'級外', ZAIKO_HINMEI_NAME = N'級外', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 110;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ダライ粉', ZAIKO_HINMEI_NAME = N'ダライ粉', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 111;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'解体ステンレス', ZAIKO_HINMEI_NAME = N'解体ステンレス', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 112;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ステンレス粉', ZAIKO_HINMEI_NAME = N'ステンレス粉', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 113;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'アルミ粉', ZAIKO_HINMEI_NAME = N'アルミ粉', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 114;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'アルミホイル', ZAIKO_HINMEI_NAME = N'アルミホイル', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 115;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'18ステン', ZAIKO_HINMEI_NAME = N'18ステン', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 116;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ダンボール', ZAIKO_HINMEI_NAME = N'ダンボール', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 117;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'紙管', ZAIKO_HINMEI_NAME = N'紙管', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 118;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'クラフト紙', ZAIKO_HINMEI_NAME = N'クラフト紙', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 119;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'雑誌', ZAIKO_HINMEI_NAME = N'雑誌', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 120;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'新聞', ZAIKO_HINMEI_NAME = N'新聞', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 121;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'牛乳パック', ZAIKO_HINMEI_NAME = N'牛乳パック', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 122;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'上白', ZAIKO_HINMEI_NAME = N'上白', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 123;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'中白', ZAIKO_HINMEI_NAME = N'中白', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 124;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ミックス', ZAIKO_HINMEI_NAME = N'ミックス', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 125;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'OA用紙A', ZAIKO_HINMEI_NAME = N'OA用紙A', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 126;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'OA用紙B', ZAIKO_HINMEI_NAME = N'OA用紙B', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 127;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'機密書類', ZAIKO_HINMEI_NAME = N'機密書類', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 128;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ちらし', ZAIKO_HINMEI_NAME = N'ちらし', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 129;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'色紙', ZAIKO_HINMEI_NAME = N'色紙', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 130;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'シュレッター', ZAIKO_HINMEI_NAME = N'シュレッター', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 131;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ライナー', ZAIKO_HINMEI_NAME = N'ライナー', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 132;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'ウエス', ZAIKO_HINMEI_NAME = N'ウエス', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 133;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'再生紙', ZAIKO_HINMEI_NAME = N'再生紙', CREATE_USER = N'中西　大樹', UPDATE_USER = N'中西　大樹' WHERE rn = 134;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'銅（出荷）', ZAIKO_HINMEI_NAME = N'銅', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 135;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'電線（出荷', ZAIKO_HINMEI_NAME = N'電線', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 136;

;WITH T AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn FROM M_ZAIKO_HIRITSU)
UPDATE T SET HINMEI_NAME = N'一本線（出荷）', ZAIKO_HINMEI_NAME = N'一本線', CREATE_USER = N'新川　拓哉', UPDATE_USER = N'新川　拓哉' WHERE rn = 137;

